### ISSUE TITLE
Mermaid 图片预览功能

### ISSUE THREAD

**Issue by solider245** [kangfenmao/cherry-studio#100]
报错:mermaid图似乎应该给与一个预览按键

![image](https://github.com/user-attachments/assets/0ef33414-0fab-4294-ac7c-8b2416fc8733)
![image](https://github.com/user-attachments/assets/cf90c586-10b8-41b4-934f-4fc81f774fc1)

这是我在使用软件的时候发生的情况。用chatbox的时候，他会给一个源码。这样的话，可以在其他软件上看看是否代码有问题。

**Comment by kangfenmao** [comment]
已经支持
