### ISSUE TITLE
The formula not parsed properly

### ISSUE THREAD

**Issue by Howardzhangdqs** [kangfenmao/cherry-studio#101]
![image](https://github.com/user-attachments/assets/f60ca39a-e479-420a-b294-030212c8ec7c)

I am unable to determine the problem. However, it seems that when a formula ends with certain specific commands, the dollar sign (\$) cannot be closed properly.

**Comment by kangfenmao** [comment]
已经修复，下个版本发布

**Comment by kangfenmao** [comment]
<img width="1066" alt="image" src="https://github.com/user-attachments/assets/815b0a3b-09e8-4e6c-aece-eba6ff0f84c3">
