### ISSUE TITLE
模型服务不支持Azure，模型输出最下面的删除栏一会在左一会在右

### ISSUE THREAD

**Issue by fresh-men** [kangfenmao/cherry-studio#102]
1、模型服务不支持Azure，希望能支持下。

2、模型输出最下面的删除栏一会在左一会在右。
右边：
![image](https://github.com/user-attachments/assets/cf0623cb-b103-463e-9cd7-20ce94f20b9b)
左边：
![image](https://github.com/user-attachments/assets/da0b205b-d535-46da-a1ee-f52c12e6072e)

**Comment by kangfenmao** [comment]
模型输出下面左右问题是故意这样设计的。只有最后一条消息操作按钮是放在左边的，方便看完消息进行操作。历史消息操作按钮默认是隐藏的，放在了右边。当你使用清除上下文之后，最后一条消息变成了历史消息，所以你看到了这个情况。

这样做是为了更好的显示效果，token 显示放在右边会让界面看起来更加混乱。如果有更好的建议可以在下面留言。

服务商集成的问题合并到了这里：https://github.com/kangfenmao/cherry-studio/issues/68#issuecomment-2364937279
