### ISSUE TITLE
最新的releases出现了windows窗口控制按钮和内置样式重叠的问题

### ISSUE THREAD

**Issue by TNXG** [kangfenmao/cherry-studio#109]
如题
![image](https://github.com/user-attachments/assets/4ece3d24-15a8-4d05-8374-06bbf7a15679)

**Comment by kangfenmao** [comment]
能看下版本号吗，我测试最新的版本好像没有遇到这个问题

**Comment by kangfenmao** [comment]
能粘贴一下导致布局错乱的 AI 回复内容吗，我好修一下

**Comment by TNXG** [comment]
我已经清除了相关对话内容并更新到了0.7.7，但是大概的GLM返回给我的内容就是大段的React代码，我在提问的时候也附带了很长一串的React代码（

**Comment by kangfenmao** [comment]
已修复，增加了一个用户消息使用 Markdown 渲染的开关。需要更新到最新版
