### ISSUE TITLE
Gemini模型增加权限安全控制参数的配置

### ISSUE THREAD

**Issue by keethebest** [kangfenmao/cherry-studio#110]
调用gemini接口的时候，出现报错：
Error: [GoogleGenerativeAI Error]: Candidate was blocked due to SAFETY。

经查询，貌似是调用接口的时候有安全参数配置项，默认的安全设置是会容易触发这个报错。

(HarmCategory.HARM_CATEGORY_HATE_SPEECH, HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, HarmCategory.HARM_CATEGORY_HARASSMENT)

**Comment by keethebest** [comment]
补充下文档：https://ai.google.dev/gemini-api/docs/safety-settings?hl=zh-cn

**Comment by Yizhouuu** [comment]
补充一下，aistudio 默认的安全等级是 Block some，对上 api 应该是 BLOCK_MEDIUM_AND_ABOVE，可以用于默认安全参数设定的参考

**Comment by kangfenmao** [comment]
先增加一个默认的配置吧，后面需求的人多了再加滑杆设置

**Comment by Yizhouuu** [comment]
> 先增加一个默认的配置吧，后面需求的人多了再加滑杆设置

是指只用默认的 BLOCK_MEDIUM_AND_ABOVE 配置，不添加自定义参数吗？这样的话 Gemini 输出的内容会非常有限

如果暂时不加参数配置的话，或许可以把默认配置里的安全等级全开最低，毕竟 LLM 客户端大家都是自用，不用担心安全性

**Comment by kangfenmao** [comment]
> > 先增加一个默认的配置吧，后面需求的人多了再加滑杆设置
> 
> 是指只用默认的 BLOCK_MEDIUM_AND_ABOVE 配置，不添加自定义参数吗？这样的话 Gemini 输出的内容会非常有限
> 
> 如果暂时不加参数配置的话，或许可以把默认配置里的安全等级全开最低，毕竟 LLM 客户端大家都是自用，不用担心安全性

有一点我不是很确定，是每一条都需要指定，还是用比如下面的配置

```
[{ category: HarmCategory.HARM_CATEGORY_UNSPECIFIED, threshold: HarmBlockThreshold.BLOCK_NONE }]
```

如果每一条都需要指定的话大概就是这样的，https://github.com/kangfenmao/cherry-studio/commit/93710c1e78b474295a8b496fa887d9cd440e8486

**Comment by Yizhouuu** [comment]
应该是每一条都要指定

**Comment by keethebest** [comment]
每一条都要指定，建议设置成 HarmBlockThreshold.BLOCK_NONE。 这样能保证不会再出现这种错误

**Comment by kangfenmao** [comment]
> 每一条都要指定，建议设置成 HarmBlockThreshold.BLOCK_NONE。 这样能保证不会再出现这种错误

OK 改成了 BLOCK_NONE
