### ISSUE TITLE
有一个小问题 openai O1没法用

### ISSUE THREAD

**Issue by jiangyouwang6** [kangfenmao/cherry-studio#116]
提供商为AiHubMix时设置O1模型，报错，是不是与O1api接口有更改？
出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥
Error: 400 Unsupported value: 'temperature' does not support 0.7 with this model. Only the default (1) value is supported. (request id: 2024092314482079503238779634958)

**Comment by Komorebi-yaodong** [comment]
O1模型好像不提供流式输出，而cherry-studio默认流式输出，另一方面，你的报错说O1模型温度默认为1，不支持0.7，你调一下试试？

**Comment by kangfenmao** [comment]
还没有加流输出开关，准备加一个按钮可以控制

**Comment by kangfenmao** [comment]
如果需要用可以把 AiMixHub 配置移动到 OpenAI 服务那边，就会对 o1 默认开启关闭流输出

**Comment by jiangyouwang6** [comment]
谢谢二位，这个问题已经解决，我先关闭了
