### ISSUE TITLE
带图片的话题删除之后文件页图片没有全部删除

### ISSUE THREAD

**Issue by czz404** [kangfenmao/cherry-studio#123]
操作：导出备份-卸载老版-在D盘安装可以改路径的新版-导入备份-发现此前话题中的图片不显示了，于是删除此前所有话题

此时文件还残留有一张图片

![pic_1727245415.png](https://s2.loli.net/2024/09/25/cEIYH9FPoBiqps4.png)

**Comment by kangfenmao** [comment]
啊，不好意思把你的数据给你弄丢了。我应该在备份数据的时候把文件相关的数据一起备份。

记录的位置在这里，按快捷键 Ctrl + Shift + I 打开控制台操作

![CleanShot 2024-09-25 at 14 39 13@2x](https://github.com/user-attachments/assets/188e1378-05fb-4aa6-b29a-11c3e1f4e0aa)

文件的文字在这里：

C:\Users\用户名\AppData\Roaming\CherryStudio\Data\Files

**Comment by czz404** [comment]
感谢，图片我本地是保存了的，倒是没有丢，不过确实是应该备份的时候把文件一起备份
文件那里残留的一个图片文件记录有办法删掉吗

**Comment by kangfenmao** [comment]
> 感谢，图片我本地是保存了的，倒是没有丢，不过确实是应该备份的时候把文件一起备份 文件那里残留的一个图片文件记录有办法删掉吗

你参考一下上吗那个图，那条记录可以点击右键->删除，然后就可以了

**Comment by czz404** [comment]
可以了，谢谢
