### ISSUE TITLE
Gemini 模型错误

### ISSUE THREAD

**Issue by Mymoliy** [kangfenmao/cherry-studio#126]
（1）出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥
Error: [GoogleGenerativeAI Error]: First content should be with role 'user', got model

Gemini 非常容易出现这个问题。

（2）Gemini的安全配置，能否交由用户控制
 

软件非常好用，真的非常感谢。

**Comment by kangfenmao** [comment]
这个问题我知道怎么回事，我会尽快解决一下

**Comment by kangfenmao** [comment]
这个已经修复了，等下个版本我发布之后再来观察一下

**Comment by kangfenmao** [comment]
更新到新版本解决了这个问题。另外安全控制选项如果需求的人比较多我再弄，毕竟还有很多东西没有开发呢

**Comment by hijos** [comment]
这个问题还是没有解决啊，我又遇到了... 科学上网是正常的，用的其他客户端就没问题。
![image](https://github.com/user-attachments/assets/b1487cc0-3fc8-4976-8885-77242b1161da)

**Comment by kangfenmao** [comment]
> 这个问题还是没有解决啊，我又遇到了... 科学上网是正常的，用的其他客户端就没问题。
> 
> ![image](https://github.com/user-attachments/assets/b1487cc0-3fc8-4976-8885-77242b1161da)
> 
> 
> 
> 点检查都是没问题的。不知道为啥聊天就用不了
> 
> ![image](https://github.com/user-attachments/assets/6c5a385c-d287-4b09-b696-4223af5f2d01)
> 
> 
> 
> 

付费了吗
