### ISSUE TITLE
需要优化的点

### ISSUE THREAD

**Issue by kangfenmao** [kangfenmao/cherry-studio#129]
1、类似 Everything 的全局搜索功能
2、话题加入日期时间概念，为最后消息时间，精确到秒。个人感觉# 符号可以替换为日期
3、输入框处无法ctrl+z
4、文件处可改为 话题名-文件名的对应方式。当前看文件完全不知道是哪个话题里面的。

**Comment by fresh-men** [comment]
都是挺不错的很实用的优化

**Comment by DrayChou** [comment]
是否考虑增加配置同步的功能？比如 webdav 或者 sftp 或者其他网盘同步的方式？

**Comment by kangfenmao** [comment]
考虑弄同步功能，等基础功能完善后开始弄这个

**Comment by kangfenmao** [comment]
文件名显示后面会修改，聊天中的文件不会出现在文件列表内。文件列表将来会显示知识库文件内容
