### ISSUE TITLE
用ollama的GLM4-9

### ISSUE THREAD

**Issue by lizhenkani** [kangfenmao/cherry-studio#13]
聊天就回这个GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

**Comment by kangfenmao** [comment]
能否截图看一下，然后还需要看看 Ollama 其他模型是否有同样的问题 @lizhenkani

**Comment by lizhenkani** [comment]
> 能否截图看一下，然后还需要看看 Ollama 其他模型是否有同样的问题 @lizhenkani


Glm4:latest
08/03 22:46
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG                       切换成ollama  llama3.1能回答 GLM是不是不兼容，用ollama  glm4命令行问答回答正常

**Comment by kangfenmao** [comment]
<img width="834" alt="image" src="https://github.com/user-attachments/assets/d2ed32d1-682e-43ac-a72a-3ca46c034cad">
