### ISSUE TITLE
导入数据后图片文件无法显示

### ISSUE THREAD

**Issue by ZzzzRyan** [kangfenmao/cherry-studio#130]
版本：v0.7.8

卸载软件重新安装后，导入原先的数据，但图片文件无法显示了。

![image](https://github.com/user-attachments/assets/55ea583a-9b20-4d88-bb29-f6ca652d3c0e)

![image](https://github.com/user-attachments/assets/d5831581-6ee2-4347-bcbb-534d3631218a)

请问图片数据是嵌入到导出的数据中的，还是单独存放的呢？

**Comment by kangfenmao** [comment]
ref: https://github.com/kangfenmao/cherry-studio/issues/123

这个问题的来源在于备份的时候文件目录没有一起打包备份

**Comment by kangfenmao** [comment]
备份全部数据的功能已经开发出来了，下个版本上。

**Comment by kangfenmao** [comment]
已经上线
