### ISSUE TITLE
增加更新开关

### ISSUE THREAD

**Issue by jiangyouwang6** [kangfenmao/cherry-studio#131]
频繁的更新必然带来很多新特性和新功能，但是对于某些复古用户可能更希望停留在稳定能用的老版本，希望开发者能增加一个是否检测更新的按钮在设置中（虽然我一直都在追新版）

**Comment by kangfenmao** [comment]
好的建议，我会加一个自动检查更新的开关。开关关闭的时候不再自动检查更新，需要手动去更新。
