### ISSUE TITLE
分屏下无法拖拽缩小

### ISSUE THREAD

**Issue by Leonhardt92** [kangfenmao/cherry-studio#136]
![aff2b9df6ed961a8b7cc14ebd615fef](https://github.com/user-attachments/assets/361d2089-d668-4762-b3b5-e066a1251ebd)
![bd97555fa0f081f25fdf9fc1256eae2](https://github.com/user-attachments/assets/405273ef-e75a-4a97-8139-3b00b68a9655)

**Comment by kangfenmao** [comment]
这里有一个最小宽度，暂时还没有增加小窗口功能。所以，如果屏幕尺寸比较小的话，等我开发出小窗功能吧。

**Comment by kangfenmao** [comment]
由于这两个是一个问题，我先合并 issue

ref: https://github.com/kangfenmao/cherry-studio/issues/55
