### ISSUE TITLE
阿里百炼的qwen-long模型无法正常调用

### ISSUE THREAD

**Issue by OFFOM** [kangfenmao/cherry-studio#138]
![image](https://github.com/user-attachments/assets/337a679b-e9da-4fc3-8392-4177e0fb055a)
出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥
Error: 400 Input error. Input should be a valid string: input.messages.14.content (request id: )
确认了我本地调用没问
其他模型也不会出现这个问题

**Comment by kangfenmao** [comment]
这个服务应该是没有完全兼容 OpenAI sdk，我去试试

**Comment by OFFOM** [comment]
好的 辛苦看看

**Comment by kangfenmao** [comment]
<img width="800" alt="image" src="https://github.com/user-attachments/assets/8fb527ef-2497-4a47-8b2d-8f3eae4079b0">

我这里能正常用，看看是不是这里设置为 0 了，上个版本这里如果是 0 就不能正常回复

**Comment by OFFOM** [comment]
好像是这样 往上调就可以了
