### ISSUE TITLE
prompt模板功能改进建议

### ISSUE THREAD

**Issue by hyzhou404** [kangfenmao/cherry-studio#14]
感谢作者，非常好用的app，完美解决了痛点

但目前我认为还有两点不足：
1. 智能体页面，也就是提供prompt模板那里，这些模板目前似乎是无法修改的，只能添加到对话中，但很多时候模板并不能满足需求。
2. 对话页面可以修改当前对话框的prompt，但也许会因为某些原因导致对话框被误删，这时就需要重新写prompt，在prompt比较复杂的时候显得不太友好（用户可能不记得prompt是什么了）。

所以我认为做如下改进比较合理：
1. 允许修改或添加智能体页面prompt模板并保存
2. 在对话页面点击+号的时候弹出选择对话框，选择默认助手或者已有prompt模板

另外这么优秀的项目，作者不考虑加个打赏链接吗：）

**Comment by kangfenmao** [comment]
打赏没弄过，后面再说。你的建议不错，采纳

**Comment by kangfenmao** [comment]
你之前的痛点是啥，能简单说两句吗 @hyzhou404

**Comment by hyzhou404** [comment]
> 你之前的痛点是啥，能简单说两句吗 @hyzhou404

主要是我需要用不同的prompt来完成不同的任务，并且可能需要切换模型，cherryai已经符合需求了～

**Comment by kangfenmao** [comment]
下周可以发布这个功能

**Comment by hyzhou404** [comment]
好的感谢，刚才觉得似乎发布之后关issue比较合适，就又打开了

**Comment by kangfenmao** [comment]
> 好的感谢，刚才觉得似乎发布之后关issue比较合适，就又打开了

是的，我要用这个 issue ID 做记录

**Comment by hyzhou404** [comment]
更新速度好快，试用了一下和修改1设想的一样👍

**Comment by kangfenmao** [comment]
https://github.com/kangfenmao/cherry-studio/releases/tag/v0.5.0
