### ISSUE TITLE
设置Context为0

### ISSUE THREAD

**Issue by yingzwang** [kangfenmao/cherry-studio#140]
在最新版v0.7.9中，设置Context为0会导致错误。
在之前的版本中，我一直设Context为0，根据其tooltip ("The number of previous messages to keep in the context"), 我认为Context指的是历史对话。但在0.7.9中， Context至少要设为1, 即包括当前最新message.
请问Context的定义变了吗？

**Comment by kangfenmao** [comment]
有调整，估计是出问题了

**Comment by kangfenmao** [comment]
问题解决了，下个版本修掉

**Comment by kangfenmao** [comment]
更新到新版本(°∀°)ﾉ
