### ISSUE TITLE
右侧边栏会消失。

### ISSUE THREAD

**Issue by Sucorde** [kangfenmao/cherry-studio#142]
![屏幕截图 2024-09-29 102120](https://github.com/user-attachments/assets/903c0332-7c3f-4850-9de0-39d6b0766c9a)
某些会话会导致侧边栏不正常，有的时候一点都看不到。
从0.7.6就有了。最新版还是有。

**Comment by kangfenmao** [comment]
能否复制一下出问题的那条回复内容

**Comment by Sucorde** [comment]
严重的那个没了。有一个轻微的。`function New-Form() {
    [CmdletBinding()]
    [OutputType([System.Windows.Forms.Form])]
    param (
        [Int]    $Width,
        [Int]    $Height,
        [String] $Text,
        [String] $BackColor = $BrandColors.Win.Dark,
        [Bool]   $Minimize = $true,
        [Bool]   $Maximize = $true,
        [ValidateSet('FixedSingle', 'FixedSingle', 'Fixed3D', 'FixedDialog', 'Sizable', 'FixedToolWindow', 'SizableToolWindow')]
        [String] $FormBorderStyle = 'FixedSingle',
        [ValidateSet('Manual', 'CenterScreen', 'WindowsDefaultLocation', 'WindowsDefaultBounds', 'CenterParent')]
        [String] $StartPosition = 'CenterScreen',
        [Bool]   $TopMost = $false
    )`

**Comment by Sucorde** [comment]
`function New-Form() { [CmdletBinding()] [OutputType([System.Windows.Forms.Form])] param ( [Int]    $Width, [Int]    $Height, [String] $Text, [String] $BackColor = $BrandColors.Win.Dark, [Bool]   $Minimize = $true, [Bool]   $Maximize = $true, [ValidateSet('FixedSingle', 'FixedSingle', 'Fixed3D', 'FixedDialog', 'Sizable', 'FixedToolWindow', 'SizableToolWindow')] [String]  [String] [String] [String] [String] [String] [String] [String]$FormBorderStyle = 'FixedSingle', [ValidateSet('Manual', 'CenterScreen', 'WindowsDefaultLocation', 'WindowsDefaultBounds', 'CenterParent')] [String] $StartPosition = 'CenterScreen', [Bool]   $TopMost = $false )`  这个是严重的。[String] [String] [String] [String] [String]  这里多放了几个

**Comment by Sucorde** [comment]
这个复制到了么？

**Comment by kangfenmao** [comment]
> 这个复制到了么？

复现了，我修一下

**Comment by kangfenmao** [comment]
<img width="1459" alt="image" src="https://github.com/user-attachments/assets/0390d91e-9048-47b2-9cf7-53c72d7dc61e">

**Comment by kangfenmao** [comment]
更新到新版本
