### ISSUE TITLE
判断代码内容不准确。

### ISSUE THREAD

**Issue by Sucorde** [kangfenmao/cherry-studio#143]
![image](https://github.com/user-attachments/assets/158643a4-637a-4553-9afb-6b5cddbb09d7)
只判断了if以后的语句，虽然AI也能识别内容，看是观赏体验感不好。

**Comment by DrayChou** [comment]
这个是因为生成的代码没有被 markdown 的 代码格式包围起来吧，然后下面缩进去的代码被 markdown 格式认为是嵌入的代码了。

**Comment by Sucorde** [comment]
是发送的，不是回复的。要不添加一个<>按钮？

**Comment by ZzzzRyan** [comment]
准确的自动识别应该是很难做到的。

如果是发送的内容，使用markdown语法中的 ` ``` ` 把代码全部框起来可以正常渲染了，在其中使用 `#` 也不会导致被识别为标题。

示例：
![image](https://github.com/user-attachments/assets/904de17b-e7df-4235-b987-d6a7cc8eb33e)

![image](https://github.com/user-attachments/assets/055ab192-c0c7-456e-83a8-bce8fa3f0c4e)

**Comment by kangfenmao** [comment]
可以加一个选项，输入内容不用 markdown 渲染

**Comment by kangfenmao** [comment]
再设置面板中添加了一个 Markdown 渲染的开关，把开关关闭就好了
