### ISSUE TITLE
建议出个可以分享模型服务的

### ISSUE THREAD

**Issue by Win-E** [kangfenmao/cherry-studio#146]
这样就可以直接将自己的模型列表分享出来了

**Comment by Win-E** [comment]
像我的接口渠道就比较杂,每个接口都要去新建一个模型服务

或者可以直接复制模型服务

**Comment by Sucorde** [comment]
他这个不是会自动判断有什么模型么？

**Comment by Win-E** [comment]
> 他这个不是会自动判断有什么模型么？

也有些奇葩接口不支持 获取模型,....

**Comment by kangfenmao** [comment]
手动添加模型确实麻烦。目前软件用户数量还不多，后面用户多了这个需求可能会增加，后面需求多了再来考虑这个问题吧。

**Comment by Win-E** [comment]
> 手动添加模型确实麻烦。目前软件用户数量还不多，后面用户多了这个需求可能会增加，后面需求多了再来考虑这个问题吧。

刚刚我注意到有一个备份恢复的功能，这也能够实现。

非常感谢！

**Comment by kangfenmao** [comment]
将来做了云服务再考虑弄这个
