### ISSUE TITLE
需求：文字大小与快捷键

### ISSUE THREAD

**Issue by AlanZ-Git** [kangfenmao/cherry-studio#149]
先感谢，再提一下建议希望能实现

1. 文字大小可调
2. 支持（自定义）快捷键操作，尤其是对话中使用最频繁的新话题、清除回话消息

**Comment by ZzzzRyan** [comment]
目前消息文字大小支持调整。

![image](https://github.com/user-attachments/assets/5bd0e411-d155-468e-b0f5-adabd5068d49)

**Comment by kangfenmao** [comment]
Ctrl + N 新建话题

**Comment by kangfenmao** [comment]
文本合并： https://github.com/kangfenmao/cherry-studio/issues/85
