### ISSUE TITLE
输出结果无法解析markdown

### ISSUE THREAD

**Issue by caecfd** [kangfenmao/cherry-studio#15]
大模型返回的结果经常以markdown形式，而软件似乎无法解析markdown格式。

![](https://faee0-1253397841.cos.ap-chengdu.myqcloud.com/wizimg/202408040212505.png)

**Comment by kangfenmao** [comment]
需要你把上图回复内容复制过来，我看看回复内容

**Comment by caecfd** [comment]
要将0.0127 °F/ft换算成°C/m，我们需要使用以下换算关系：

1 °F = (5/9) °C
1 ft = 0.3048 m
首先，我们将0.0127 °F/ft转换为°C/ft：

[ 0.0127 \text{ °F/ft} \times \frac{5}{9} \text{ °C/°F} = 0.0127 \times \frac{5}{9} \text{ °C/ft} ]

计算：

[ 0.0127 \times \frac{5}{9} = 0.007055555555555556 \text{ °C/ft} ]

接下来，我们将0.007055555555555556 °C/ft转换为°C/m：

[ 0.007055555555555556 \text{ °C/ft} \times \frac{1 \text{ ft}}{0.3048 \text{ m}} = 0.007055555555555556 \times \frac{1}{0.3048} \text{ °C/m} ]

计算：

[ 0.007055555555555556 \times \frac{1}{0.3048} = 0.0231522 \text{ °C/m} ]

因此，0.0127 °F/ft换算成°C/m的结果是：

[ \boxed{0.0231522} ]

**Comment by caecfd** [comment]
这个使用的是Deepseek-coder模型，用别的模型好像也一样，Cherry把方括号前面的反斜杠给去掉了，导致公式解析不了，但是在其他的前端工具里头并没有这种情况

**Comment by caecfd** [comment]
别的工具输出结果一样，但显示效果是这样的：
![](https://faee0-1253397841.cos.ap-chengdu.myqcloud.com/wizimg/202408040959206.png)

**Comment by caecfd** [comment]
别的工具输出结果一样，但显示效果是这样的：
![](https://faee0-1253397841.cos.ap-chengdu.myqcloud.com/wizimg/202408041001045.png)

**Comment by kangfenmao** [comment]
> 别的工具输出结果一样，但显示效果是这样的：
> 
> ![](https://faee0-1253397841.cos.ap-chengdu.myqcloud.com/wizimg/202408041001045.png)

OK，今天修复

**Comment by caecfd** [comment]
模型实际输出：

要将0.0127 °F/ft换算成°C/m，我们需要使用以下换算关系：

1. 温度换算：1 °F = \(\frac{5}{9}\) °C
2. 长度换算：1 ft = 0.3048 m

首先，我们将0.0127 °F/ft转换为°C/ft：

\[
0.0127 \text{ °F/ft} \times \frac{5}{9} \text{ °C/°F} = 0.0127 \times \frac{5}{9} \text{ °C/ft}
\]

计算：

\[
0.0127 \times \frac{5}{9} = 0.00705556 \text{ °C/ft}
\]

接下来，我们将0.00705556 °C/ft转换为°C/m：

\[
0.00705556 \text{ °C/ft} \times \frac{1 \text{ ft}}{0.3048 \text{ m}} = 0.00705556 \div 0.3048 \text{ °C/m}
\]

计算：

\[
0.00705556 \div 0.3048 = 0.02315 \text{ °C/m}
\]

因此，0.0127 °F/ft换算成°C/m的结果是：

\[
\boxed{0.02315}
\]

**Comment by caecfd** [comment]
模型的实际输出是这样的：
![](https://faee0-1253397841.cos.ap-chengdu.myqcloud.com/wizimg/202408041003295.png)

**Comment by caecfd** [comment]
应该是反斜杠被搞不见了，导致数学公式不能很好的解析。

**Comment by kangfenmao** [comment]
<img width="777" alt="image" src="https://github.com/user-attachments/assets/bef2094b-b8fa-40fa-838d-efca235f9075">

测试完成后发布

**Comment by kangfenmao** [comment]
新版本已经发布 @caecfd 

https://github.com/kangfenmao/cherry-studio/releases/tag/v0.4.8

我发现是因为数学公式 `[]` 引用的这个公式默认已经不会渲染了，需要 `$$___$$` 这种格式才行，所以，如果显示效果不好，可以暂时修改提示词增加一句话来描述。

提示词：公式要使用 $$ 格式
