### ISSUE TITLE
无法配置 alist 的 webdav

### ISSUE THREAD

**Issue by martinzu** [kangfenmao/cherry-studio#150]
使用 Windows 资源管理器可以通过 webdav 方式访问 alist，如图：
![图片](https://github.com/user-attachments/assets/65d2f189-10f6-4daf-8161-27ed400caed0)

使用 Cherry Studio 无法链接：
![图片](https://github.com/user-attachments/assets/70cc82fe-8938-4e37-bf94-a81977cdb830)

尝试配置全路径也不行：
![图片](https://github.com/user-attachments/assets/7af6462f-b059-4019-8444-136467f75e75)

还请大佬修复，亦或者提供配置方法，谢谢~

**Comment by martinzu** [comment]
亦或者除了 Webdav 之外，还有什么办法可以在多设备中同步配置和助手的聊天资料？

我可以用别的方案，比如软链接 + OneDrive 的方式漫游配置和数据，比如可以把 %APPDATA%\CherryStudio 文件夹放入 OD，然后把各设备的 %APPDATA%\CherryStudio 指向 OD 即可。。。

**Comment by kangfenmao** [comment]
英文目录有测试过吗

**Comment by martinzu** [comment]
英文目录也不行，如图：
![image](https://github.com/user-attachments/assets/7f1878c0-1d7f-4de0-86a3-a4dcd241b1be)

![image](https://github.com/user-attachments/assets/77d81673-bcf0-4d59-984a-c485ecb8073f)

亦或者除了 Webdav 之外，还有什么办法可以在多设备中同步配置和助手的聊天资料？@kangfenmao

**Comment by kangfenmao** [comment]
加我微信看看：kangfenmao

**Comment by kangfenmao** [comment]
经过检查发现是天翼云不支持 PUT 方法
