### ISSUE TITLE
需求：在右侧边栏里面的设置添加功能

### ISSUE THREAD

**Issue by Sucorde** [kangfenmao/cherry-studio#151]
添加一个清空所有的对话记录。有的时候太多了。一个一个删太麻烦。
删之前给个提示就好了。

还有右键，除了输出面板和对话记录那里，其他的地方禁用了吧。

**Comment by kangfenmao** [comment]
<img width="367" alt="image" src="https://github.com/user-attachments/assets/09d3130e-2e9c-4079-aa0b-b986ed51f40d">

**Comment by Sucorde** [comment]
这位置属实没想到。
