### ISSUE TITLE
Azure的api调用

### ISSUE THREAD

**Issue by lyopop1** [kangfenmao/cherry-studio#153]
很不错的应用，但是Azure openai不支持，希望能加入支持

**Comment by kangfenmao** [comment]
这个功能已经开发出来了，只不过我没有账号去测试。如果能提供账号给我测试的话，可以微信我 @lyopop1 

微信账号：kangfenmao

**Comment by kangfenmao** [comment]
感谢 @夏至 提供的 API KEY。这个功能已经开发完成，下个版本发布

**Comment by kangfenmao** [comment]
<img width="418" alt="image" src="https://github.com/user-attachments/assets/c5000636-2f08-41ef-9683-45c01f803153">
