### ISSUE TITLE
渲染的公式没有居中

### ISSUE THREAD

**Issue by fresh-men** [kangfenmao/cherry-studio#154]
这个是gpt逆向api生成的结果，这个公式按道理应该会居中，但是并没有：
![image](https://github.com/user-attachments/assets/2468dfbe-42ec-42b6-99ad-bd7a618b884c)

对应的gpt回复的内容：

以下是您提供内容的中文翻译：

---

**5. 从残差初始化分析梯度流**

我们现在研究残差初始化的情况。我们考虑形式为 (3) 的线性网络：

\[ W_k(t) = I + \frac{s}{\sqrt{Ld}} N_k + \frac{1}{L} \theta_k(t), \]

其中每个矩阵是一个 \( d \times d \) 矩阵，\( N_k \) 填充了独立同分布的高斯条目 \( N(0,1) \)。我们在第 1 节中提到过关于 \( N_k \) 前的缩放因子的讨论。根据残差网络的标准初始化，我们假设 \( \theta_k \) 初始化为零。注意，\( \theta_k \) 前的缩放因子 \( 1/L \) 对动态没有影响；这在展示和计算上是方便的，因为我们证明了在训练后，\( \theta_k \) 的阶数为 \( O(1) \)。

在陈述本节关于梯度流收敛的主要结果之前，回忆一下 \( \mathbf{r} \in \mathbb{R}^d \) 是附加在残差网络末尾的固定向量，用于将其输出投影回 \( \mathbb{R} \)。

**定理 4.** 在假设 (A1) 下，存在 \( C_1, \ldots, C_5 > 0 \)，仅依赖于 \( s \)，如果：

\[ L > C_1, \quad d > C_2, \quad R_L(W(0)) - R_{\text{min}} \leq \frac{C_3 \lambda^2 \|w\|^2_2}{\Lambda}, \]

那么，至少以概率：

\[ 1 - 16 \exp(-C_4 d) \]

梯度流动态 (4) 收敛到全局最小化器 \( W^R \) 的风险。此外，最小化器 \( W^{RI} \) 满足：

\[ W^R_k = I + \frac{s}{\sqrt{Ld}} N_k + \frac{1}{L} R_k \]

且 

\[ \| W^{RI}_k \|_F \leq C_5, \quad 1 \leq k \leq L. \]

--- 

如果您需要进一步的帮助，请告诉我！

**Comment by kangfenmao** [comment]
已经修复
