### ISSUE TITLE
自建的newapi无法访问

### ISSUE THREAD

**Issue by TanXiang7o** [kangfenmao/cherry-studio#155]
![image](https://github.com/user-attachments/assets/80fed50d-8747-45b4-92d7-0d90d415a6c7)
如图所示，url完全一样的，左边是lobechat是正常访问的，右边是cherry-studio，这错误是啥意思，感觉直接没发出去？

**Comment by 1355873789** [comment]
OneAPI及其二开项目都测试过没问题的，检查下参数是不是有问题

**Comment by kangfenmao** [comment]
出错的信息贴出来看看 @TanXiang7o

**Comment by TanXiang7o** [comment]
@kangfenmao 
![image](https://github.com/user-attachments/assets/ae1945c7-de11-4b65-a4fd-9451ba06100c)
我这边换了很多newapi的项目都不能用啊，点这个检查直接就报网络错误
![image](https://github.com/user-attachments/assets/c14f9172-5434-47eb-8cb0-8cd03adb4314)
都没到设置参数的步骤，对话也是错误
![image](https://github.com/user-attachments/assets/c354f5b5-0637-4141-89c7-af578b7a7843)

**Comment by kangfenmao** [comment]
看起来像是网络问题，看看有没有对软件设置代理服务

**Comment by fl0w1nd** [comment]
我用的new api测试是没有问题的

**Comment by TanXiang7o** [comment]
应该是ssl证书的问题，有的站不行，有的站可以，估计是免费证书的问题

**Comment by qcy615** [comment]
可以设置不检查ssl证书吗

**Comment by ansemz** [comment]
> 可以设置不检查ssl证书吗

我确实也需要跳过ssl证书检查，用自签证书比较方便。
