### ISSUE TITLE
API地址的高级选项

### ISSUE THREAD

**Issue by Sucorde** [kangfenmao/cherry-studio#157]
OpenAI API的后缀都是一致的。但是其他的一些推理架构的后缀不一样。
希望可以添加一个API地址的高级选项。
可以自定义地址的后缀路径。默认情况是OpenAI的，打开开关以后增加一个输入框。可以输入后续的地址。
例如Ollama和vllm的后缀都是不一样的，我又不想反代。
有的是/v1/chat/completions,有的是/generate，而且这个路径需要确保发送到 /generate 端点的 POST 请求中包含 "prompt" 键。

或者你干脆单独支持一个vllm方式吧。

**Comment by Sucorde** [comment]
API URL地址自定义什么时候能有啊。

**Comment by kangfenmao** [comment]
> API URL地址自定义什么时候能有啊。

下周上线

**Comment by Sucorde** [comment]
看到更新了。
这个路径需要确保发送到 /generate 端点的 POST 请求中包含 "prompt" 键。这个加了么？最近没时间弄

**Comment by kangfenmao** [comment]
> 看到更新了。 这个路径需要确保发送到 /generate 端点的 POST 请求中包含 "prompt" 键。这个加了么？最近没时间弄

还没有测试，不知道对其他服务商有没有影响

**Comment by kangfenmao** [comment]
> /generate

这个应该是不兼容 OpenAI SDK 的请求吧 /generate

**Comment by kangfenmao** [comment]
目前已经实现了 3 种适配

<img width="528" alt="image" src="https://github.com/user-attachments/assets/ce41c599-322c-4f8c-8013-405d03b29092">

**Comment by Sucorde** [comment]
其实我是比较建议单独设置一个VLLM的接入，

**Comment by kangfenmao** [comment]
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/bb9bd567-7e7e-45f8-a6a1-9147a4e16bc3">

vLLM 已经支持了 OpenAI 兼容请求，是否还有必要增加这个服务商 @Sucorde

**Comment by Sucorde** [comment]
> <img alt="image" width="1160" src="https://private-user-images.githubusercontent.com/8253512/380640743-bb9bd567-7e7e-45f8-a6a1-9147a4e16bc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTg2MzAsIm5iZiI6MTczMDExODMzMCwicGF0aCI6Ii84MjUzNTEyLzM4MDY0MDc0My1iYjliZDU2Ny03ZTdlLTQ1ZjgtYTZhMS05MTQ3YTRlMTZiYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTIyNTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Y2OTAwYzVkZmEzZjNjNGE5ZDA0MjdmN2M1YTJmYTQxZmU5Y2I4ZTljMWU4Yzc3MDExNmYwZWRmMDgxODM0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.DjPdC9AJIBOogk18h3Yr3ScCLHQzsjihAVDQvA5Xe2I">
> vLLM 已经支持了 OpenAI 兼容请求，是否还有必要增加这个服务商 @Sucorde

我试过了。确实已经支持了。所以没必要加入了。因为自定义的端口不确定，增加没意义。
