### ISSUE TITLE
优化建议：markdown表格目前还没有支持<br>换行，希望可以支持下！

### ISSUE THREAD

**Issue by icychick-liu** [kangfenmao/cherry-studio#160]
如下图，markdown表格输出时不支持`<br>`标签换行，这个影响输出内容的显示效果。
![image](https://github.com/user-attachments/assets/8f9355dd-549b-4a27-92f3-01814c2f3dc0)

**Comment by icychick-liu** [comment]
以下表格列出了不同规模企业数字化中心团队的建议规模、人员组成和主要职责：

| 企业规模 (人数) | 团队规模 (人数) | 人员组成                                       | 主要职责                                                         |
|-----------------|-----------------|-------------------------------------------------|-----------------------------------------------------------------|
| 20人以内       | 1-3人           | RPA开发者/业务分析师（兼职）/IT支持（兼职/外包） | - 流程自动化 (RPA)<br>- 数据收集和基本分析<br>- 系统维护和支持 |
| 50人以内       | 3-5人           | RPA开发者/业务分析师/数据分析师/IT支持             | - 流程自动化 (RPA)<br>- 数据分析和报表<br>- 系统维护和支持<br>- 数字化工具调研 |
| 100人以内      | 5-10人          | RPA开发者/业务分析师/数据分析师/IT支持/项目经理       | - 流程自动化 (RPA/低代码)<br>- 数据分析和可视化<br>- 系统维护和安全<br>- 数字化项目管理<br>- 初步的数字化战略规划 |
| 200人以内      | 10-20人         | RPA/低代码开发团队/数据分析团队/IT支持团队/项目经理/产品经理 | - 复杂的流程自动化<br>- 数据挖掘和商业智能<br>- 系统集成和优化<br>- 数字化项目管理<br>- 制定和实施数字化战略<br>- 产品创新 |
| 200人以上      | 20人以上        | 开发团队/数据科学团队/IT支持团队/项目经理/产品经理/安全专家/架构师 | - 全面的流程自动化和数字化转型<br>- 高级数据分析和预测<br>- 企业级系统架构和管理<br>- 信息安全保障<br>- 制定和执行长期数字化战略<br>- 技术创新和研发 |


**一些补充说明:**

* **兼职:**  在小型企业中，一些角色可以由同一个人兼任，以节省成本。
* **外包:**  一些职能，例如IT支持，可以考虑外包给专业服务提供商。
* **低代码平台:** 随着企业规模的扩大，可以考虑引入低代码平台，以提高开发效率和降低技术门槛。
* **团队结构的灵活性:**  以上只是一个建议，实际的团队规模和人员组成需要根据企业的具体情况进行调整。
* **职责的交叉:** 随着团队成员经验的增长，鼓励跨职能合作和技能提升，例如RPA开发者学习数据分析技能。

希望这个表格能够帮助你更好地规划不同规模企业数字化中心团队的建设。

**Comment by icychick-liu** [comment]
> 把内容贴一下吧

以下表格列出了不同规模企业数字化中心团队的建议规模、人员组成和主要职责：

| 企业规模 (人数) | 团队规模 (人数) | 人员组成                                       | 主要职责                                                         |
|-----------------|-----------------|-------------------------------------------------|-----------------------------------------------------------------|
| 20人以内       | 1-3人           | RPA开发者/业务分析师（兼职）/IT支持（兼职/外包） | - 流程自动化 (RPA)<br>- 数据收集和基本分析<br>- 系统维护和支持 |
| 50人以内       | 3-5人           | RPA开发者/业务分析师/数据分析师/IT支持             | - 流程自动化 (RPA)<br>- 数据分析和报表<br>- 系统维护和支持<br>- 数字化工具调研 |
| 100人以内      | 5-10人          | RPA开发者/业务分析师/数据分析师/IT支持/项目经理       | - 流程自动化 (RPA/低代码)<br>- 数据分析和可视化<br>- 系统维护和安全<br>- 数字化项目管理<br>- 初步的数字化战略规划 |
| 200人以内      | 10-20人         | RPA/低代码开发团队/数据分析团队/IT支持团队/项目经理/产品经理 | - 复杂的流程自动化<br>- 数据挖掘和商业智能<br>- 系统集成和优化<br>- 数字化项目管理<br>- 制定和实施数字化战略<br>- 产品创新 |
| 200人以上      | 20人以上        | 开发团队/数据科学团队/IT支持团队/项目经理/产品经理/安全专家/架构师 | - 全面的流程自动化和数字化转型<br>- 高级数据分析和预测<br>- 企业级系统架构和管理<br>- 信息安全保障<br>- 制定和执行长期数字化战略<br>- 技术创新和研发 |


**一些补充说明:**

* **兼职:**  在小型企业中，一些角色可以由同一个人兼任，以节省成本。
* **外包:**  一些职能，例如IT支持，可以考虑外包给专业服务提供商。
* **低代码平台:** 随着企业规模的扩大，可以考虑引入低代码平台，以提高开发效率和降低技术门槛。
* **团队结构的灵活性:**  以上只是一个建议，实际的团队规模和人员组成需要根据企业的具体情况进行调整。
* **职责的交叉:** 随着团队成员经验的增长，鼓励跨职能合作和技能提升，例如RPA开发者学习数据分析技能。

希望这个表格能够帮助你更好地规划不同规模企业数字化中心团队的建设。

**Comment by kangfenmao** [comment]
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/5ff736b7-6d6a-4658-ae52-ee881675a913">

**Comment by icychick-liu** [comment]
> <img alt="image" width="1160" src="https://private-user-images.githubusercontent.com/8253512/374567028-5ff736b7-6d6a-4658-ae52-ee881675a913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDUyNDQsIm5iZiI6MTcyODQ0NDk0NCwicGF0aCI6Ii84MjUzNTEyLzM3NDU2NzAyOC01ZmY3MzZiNy02ZDZhLTQ2NTgtYWU1Mi1lZTg4MTY3NWE5MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDMzNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdiY2M1MDQzZmEzMzFkMDQ1NjIxMThiZDUzNjU4ODdlZGY2YjMwNDAxMTRmMjE1YTM3ODBhOTIzYTQxYmM2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-Vp1tGBwi3ScA2yaKdmS1Wmp26s1BiRIXcSCfgPhzpg">

奇怪，是不是gemini生成的格式有问题？但是直接拷贝后粘贴到obsidian后显示又是正常的

**Comment by kangfenmao** [comment]
> > <img alt="image" width="1160" src="https://private-user-images.githubusercontent.com/8253512/374567028-5ff736b7-6d6a-4658-ae52-ee881675a913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDUyNDQsIm5iZiI6MTcyODQ0NDk0NCwicGF0aCI6Ii84MjUzNTEyLzM3NDU2NzAyOC01ZmY3MzZiNy02ZDZhLTQ2NTgtYWU1Mi1lZTg4MTY3NWE5MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDMzNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdiY2M1MDQzZmEzMzFkMDQ1NjIxMThiZDUzNjU4ODdlZGY2YjMwNDAxMTRmMjE1YTM3ODBhOTIzYTQxYmM2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-Vp1tGBwi3ScA2yaKdmS1Wmp26s1BiRIXcSCfgPhzpg">
> 
> 奇怪，是不是gemini生成的格式有问题？但是直接拷贝后粘贴到obsidian后显示又是正常的

不是，是应用本身问题。我已经修复了，等下个版本更新就好了。新版本我还没有发

**Comment by icychick-liu** [comment]
> > > <img alt="image" width="1160" src="https://private-user-images.githubusercontent.com/8253512/374567028-5ff736b7-6d6a-4658-ae52-ee881675a913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDUyNDQsIm5iZiI6MTcyODQ0NDk0NCwicGF0aCI6Ii84MjUzNTEyLzM3NDU2NzAyOC01ZmY3MzZiNy02ZDZhLTQ2NTgtYWU1Mi1lZTg4MTY3NWE5MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDMzNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdiY2M1MDQzZmEzMzFkMDQ1NjIxMThiZDUzNjU4ODdlZGY2YjMwNDAxMTRmMjE1YTM3ODBhOTIzYTQxYmM2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-Vp1tGBwi3ScA2yaKdmS1Wmp26s1BiRIXcSCfgPhzpg">
> > 
> > 
> > 奇怪，是不是gemini生成的格式有问题？但是直接拷贝后粘贴到obsidian后显示又是正常的
> 
> 不是，是应用本身问题。我已经修复了，等下个版本更新就好了。新版本我还没有发

嗯嗯，好的。👍👍👍
