### ISSUE TITLE
不支持 上传图片问答

### ISSUE THREAD

**Issue by 1137882300** [kangfenmao/cherry-studio#164]
上传图片后问答，会直接报错

**Comment by kangfenmao** [comment]
> 上传图片后问答，会直接报错

给一些详细的信息看看

**Comment by kangfenmao** [comment]
服务商信息也发一下 @1137882300

**Comment by 1137882300** [comment]
<img width="468" alt="image" src="https://github.com/user-attachments/assets/7c05e035-2d69-4a33-99e0-396f73f37d30">
这是截图，就是不支持多模态的模型，但是呢又上传了模型，后面提问都是报错。需要删除上下文就可以了

**Comment by kangfenmao** [comment]
OpenAI 是支持多模态的，图片识别也没问题。你是否使用的是官方 API，如果不是官方 API 需要联系你的 API 服务商问一下。 @1137882300

**Comment by 1137882300** [comment]
> OpenAI 是支持多模态的，图片识别也没问题。你是否使用的是官方 API，如果不是官方 API 需要联系你的 API 服务商问一下。 @1137882300

用的是github models，暂时不支持

**Comment by kangfenmao** [comment]
这个问题应该反馈给 Github Models, 他们模型还不能使用图片。这个可能原因是他们要减少成本。 @1137882300

**Comment by 1137882300** [comment]
嗯嗯 thanks

**Comment by kangfenmao** [comment]
那我先关闭这个了，等后面有什么进展再更新
