### ISSUE TITLE
需求：增加一个一键返回到prompt或者回答最上方的按键

### ISSUE THREAD

**Issue by ZhenhongDu** [kangfenmao/cherry-studio#166]
使用场景：有的时候prompt内容（例如复制了整篇文章或书籍的内容）或者GPT回应的文字长度比较长，去查看上一次的回答结果需要翻动很久（比如说at了不同的机器人进行了回应，但是回复的长度会比较长）。

需求：能否在prompt和GPT回应的下方操作面板（下图），添加一个返回最上方的按钮呢
![image](https://github.com/user-attachments/assets/f8d25962-8016-43ea-8932-8af5aaadfd11)

Prompt过长示例：
![image](https://github.com/user-attachments/assets/9575840e-8f84-445e-b32c-e5e25023d50e)

**Comment by kangfenmao** [comment]
<img width="185" alt="image" src="https://github.com/user-attachments/assets/0773fbb4-d743-405f-ac68-9514b982224a">

点击这里返回消息顶部
