### ISSUE TITLE
Azure 调用失败

### ISSUE THREAD

**Issue by lamlados** [kangfenmao/cherry-studio#167]
Azure OpenAI Studio 的 Endpoint：
- https://xxx.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2023-03-15-preview

所以我在配置的时候填的API地址是 https://xxx.openai.azure.com
API版本是 2023-03-15-preview
API密钥检查提示连接成功
报错：
<img width="618" alt="Screenshot 2024-10-10 at 13 55 35" src="https://github.com/user-attachments/assets/5cdbbec9-f8a8-4e37-8f23-00491aa22a8d">

**Comment by kangfenmao** [comment]
能否联系我微信，我帮你看一下
微信账号：kangfenmao

**Comment by kangfenmao** [comment]
<img width="545" alt="image" src="https://github.com/user-attachments/assets/5610721a-8b5c-4f84-9862-93d8e8576ade">

默认启用的模型有问题，需要手动删除启用的模型，然后自己按上图显示的方式添加

出问题的模型包括，gpt-4o, gpt-4o-mini

**Comment by kangfenmao** [comment]
已上线
