### ISSUE TITLE
回答输出中，latex解析不支持矩阵环境

### ISSUE THREAD

**Issue by Kozmosa** [kangfenmao/cherry-studio#169]
问题复现：

询问GLM-4-Plus：增广矩阵法求矩阵逆的变换过程中允许使用列变换吗？

回答：
增广矩阵法（高斯-约当消元法）求矩阵逆的过程中，通常只使用行变换，而不使用列变换。这是因为行变换能够保持矩阵的行结构，从而在将原矩阵转换为单位矩阵的同时，逐步构建出其逆矩阵。

### 为什么只使用行变换？

1. **行变换的目标**：
   - 行变换的主要目标是通过对增广矩阵的行进行操作，将左侧的原矩阵部分转换为单位矩阵。在这个过程中，右侧的初始单位矩阵会相应地变换为原矩阵的逆矩阵。

2. **保持行结构**：
   - 行变换操作（如行交换、行倍乘、行加减）直接影响矩阵的行，而不改变列的结构。这对于逐步构建逆矩阵是必要的。

3. **列变换的影响**：
   - 列变换会改变矩阵的列结构，这可能会导致无法正确地将原矩阵部分转换为单位矩阵，从而无法得到正确的逆矩阵。

### 具体步骤回顾

假设我们有一个矩阵 \( A \)：

\[ A = \begin{pmatrix}
2 & 1 \\
1 & 1
\end{pmatrix} \]

我们要求 \( A \) 的逆矩阵。

#### 1. 构造增广矩阵

\[ [A | I] = \left[\begin{array}{cc|cc}
2 & 1 & 1 & 0 \\
1 & 1 & 0 & 1
\end{array}\right] \]

#### 2. 行变换

**目标**：将左侧部分转换为单位矩阵。

**步骤1**：将第一行的首元素变为1。

\[ R1 \leftarrow \frac{1}{2} R1 \]

\[ \left[\begin{array}{cc|cc}
1 & \frac{1}{2} & \frac{1}{2} & 0 \\
1 & 1 & 0 & 1
\end{array}\right] \]

**步骤2**：消去第二行的首元素。

\[ R2 \leftarrow R2 - R1 \]

\[ \left[\begin{array}{cc|cc}
1 & \frac{1}{2} & \frac{1}{2} & 0 \\
0 & \frac{1}{2} & -\frac{1}{2} & 1
\end{array}\right] \]

**步骤3**：将第二行的第二个元素变为1。

\[ R2 \leftarrow 2 R2 \]

\[ \left[\begin{array}{cc|cc}
1 & \frac{1}{2} & \frac{1}{2} & 0 \\
0 & 1 & -1 & 2
\end{array}\right] \]

**步骤4**：消去第一行的第二个元素。

\[ R1 \leftarrow R1 - \frac{1}{2} R2 \]

\[ \left[\begin{array}{cc|cc}
1 & 0 & 1 & -1 \\
0 & 1 & -1 & 2
\end{array}\right] \]

#### 3. 结果

此时，增广矩阵的左侧部分已经变为单位矩阵，右侧部分即为 \( A \) 的逆矩阵：

\[ A^{-1} = \begin{pmatrix}
1 & -1 \\
-1 & 2
\end{pmatrix} \]

### 总结

在增广矩阵法求矩阵逆的过程中，只使用行变换，不使用列变换。这是因为行变换能够保持矩阵的行结构，逐步将原矩阵部分转换为单位矩阵，同时构建出其逆矩阵。列变换会改变矩阵的列结构，可能导致无法正确得到逆矩阵。

希望这个解释能帮助你理解为什么在增广矩阵法中只使用行变换。如果有任何进一步的问题，欢迎继续提问！

问题显示：
![image](https://github.com/user-attachments/assets/6479b820-62be-42a2-9e4a-ec21d466a924)
其中_\begin{pmatrix}_之后的环境并没有被正确解析。

可能的修复方案：
支持常见的latex矩阵环境

**Comment by Kozmosa** [comment]
经过验证，mathjax能够正确解析glm4-plus输出的含矩阵环境的latex代码
![1728566072726](https://github.com/user-attachments/assets/7f7684e2-c5ec-4e4f-8bb9-9beca2aa1707)

**Comment by Kozmosa** [comment]
https://github.com/kangfenmao/cherry-studio/blob/c254b52b515a61e966f7867bc6f0479832151363/src/renderer/src/pages/home/Markdown/Markdown.tsx#L9

项目中目前似乎采用了ReactMarkdown来解析markdown文本，且使用了remark-math插件。

[remark-math/example-mathjax](https://github.com/remarkjs/remark-math?tab=readme-ov-file#example-mathjax)中介绍了将katex更换为mathjax的方式。

**Comment by kangfenmao** [comment]
> https://github.com/kangfenmao/cherry-studio/blob/c254b52b515a61e966f7867bc6f0479832151363/src/renderer/src/pages/home/Markdown/Markdown.tsx#L9
> 
> 项目中目前似乎采用了ReactMarkdown来解析markdown文本，且使用了remark-math插件。
> 
> [remark-math/example-mathjax](https://github.com/remarkjs/remark-math?tab=readme-ov-file#example-mathjax)中介绍了将katex更换为mathjax的方式。

行，我空了研究一下看看有没有好的方案

**Comment by Kozmosa** [comment]
我试着修了下，但是只按照他给出那个方案修改，模块导入会出问题，无法成功构建。不知道是包管理的问题还是插件本身太久没有维护。

**Comment by kangfenmao** [comment]
![增广矩阵法](https://github.com/user-attachments/assets/2c8075fa-d214-4fee-8bbe-68ff3af3ce91)
