### ISSUE TITLE
添加 deepseek API key 总是提示连接失败

### ISSUE THREAD

**Issue by z-jt-best** [kangfenmao/cherry-studio#17]
按照官方文档教程进行添加 deepseek 的 api key ，点击检查总是提示连接失败，连接失败是因为什么原因，是因为刚刚创建api key需要等一段时间才能检查成功吗？

![1](https://github.com/user-attachments/assets/f7d0e21c-f7e3-4ace-af70-59aa42e77692)

**Comment by kangfenmao** [comment]
看起来是没有任何问题的，如果 API 没错误的话。

这大概率是网络连接问题，能否使用快捷键 Ctrl + Shift + I 看看控制台有没有什么网络错误

<img width="1400" alt="image" src="https://github.com/user-attachments/assets/718c5f83-d423-4759-a4c8-f1708d5c9296">

**Comment by z-jt-best** [comment]
好的谢谢

**Comment by kangfenmao** [comment]
有查到什么原因吗 @z-jt-best

**Comment by AkenClub** [comment]
> 有查到什么原因吗 @z-jt-best

在硅基流动添加 key 之后有类似问题，
![image](https://github.com/user-attachments/assets/67fa611f-7699-4e71-aee5-7fe5e5be3c0a)
原因是我还没有实名，检查的时候用了 meta 的模型，导致接口返回 403，删除 meta 的模型后检查 “连接成功”。
![image](https://github.com/user-attachments/assets/abdb637f-4ca7-4414-ba8a-f5d38286b547)

建议检查硅基流动的 key 可用时候不用 meta 的模型？另外建议在出现错误时候指引用户去哪里查看日志，快捷方式那里也加上 ctrl+shift+i 可以打开控制台，因为直接在控制台查看日志是排查最快捷的
（我是刚新装的软件）

**Comment by sbkk000** [comment]
同问，硅基流动的api没有问题，但是deepseek就不行，最近想用deepseek v3也不行，特意申请了一个新的api，加入cherrystudio里面还是提示连接失败

**Comment by Lt-Adam** [comment]
我也是实名错误

![Image](https://github.com/user-attachments/assets/90d92649-508e-4961-a872-30577aa972f2)

**Comment by tengfeima888-ctrl** [comment]
可能是没充钱，充了钱就能检测成功
