### ISSUE TITLE
o1模型设置使用优化

### ISSUE THREAD

**Issue by SHLE1** [kangfenmao/cherry-studio#172]
在用户选择模型为`o1`系列模型时，自动将`温度`设置为`1`，将`流式输出`选项关闭，减少操作频率

**Comment by kangfenmao** [comment]
现在是默认关闭了流输出

**Comment by SHLE1** [comment]
默认关闭，但是每次用o1就要手动调整，用普通模型就要再调整一次。同时，新建助手也必须要输入系统提示词，而o1不支持系统提示词……

**Comment by kangfenmao** [comment]
开发完成，下个版本上线
