### ISSUE TITLE
阿里云灵积更新为阿里云百炼，添加腾讯混元大模型的支持

### ISSUE THREAD

**Issue by pengshp** [kangfenmao/cherry-studio#173]
- 原来的阿里云灵积已经迁移到`阿里云百炼`，希望更新一下
   https://bailian.console.aliyun.com/

- 希望添加`腾讯混元大模型`的支持
   https://hunyuan.tencent.com/

**Comment by kangfenmao** [comment]
OK

**Comment by kangfenmao** [comment]
https://github.com/kangfenmao/cherry-studio/commit/3326074076b8edbbb4df5e54d97b78acd8f4f476

**Comment by kangfenmao** [comment]
阿里云百炼已经更新完成

混元大模型合并到了这里：

https://github.com/kangfenmao/cherry-studio/issues/68
