### ISSUE TITLE
使用滚动条显示不全

### ISSUE THREAD

**Issue by Sucorde** [kangfenmao/cherry-studio#176]
在选择模型的弹窗上。还有一个，滚动条太细了。就比如我今天下午鼠标滚轮坏了。所有滚动条的地方用起来抓狂。
![image](https://github.com/user-attachments/assets/adaed33c-7dc9-4497-9ef6-f2f3a4d129f5)

**Comment by kangfenmao** [comment]
下版本改粗一些

**Comment by Sucorde** [comment]
还有最后一个模型显示不全。看下图。

**Comment by kangfenmao** [comment]
> 还有最后一个模型显示不全。看下图。

这个也修掉了，下个版本发
