### ISSUE TITLE
ollama问题

### ISSUE THREAD

**Issue by vsd269** [kangfenmao/cherry-studio#177]
![image](https://github.com/user-attachments/assets/f5ff01a4-cb47-439d-8a12-af0d90a8c638)
这里的密钥，该怎么获取呢？怎么填？还有api地址对么？

**Comment by Sucorde** [comment]
随便填写

**Comment by kangfenmao** [comment]
> ![image](https://private-user-images.githubusercontent.com/142389217/375953287-f5ff01a4-cb47-439d-8a12-af0d90a8c638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDcyMzYsIm5iZiI6MTcyODc0NjkzNiwicGF0aCI6Ii8xNDIzODkyMTcvMzc1OTUzMjg3LWY1ZmYwMWE0LWNiNDctNDM5ZC04YTEyLWFmMGQ5MGE4YzYzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxNTI4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDI2MTQwNjk5NGE2ZGFhMTBhYTc5MDIzYWYzOWY2YTA5ZDBmYTA2NDIxY2QzZWYyZGE4ZDk1MTBlZjhkYjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IeXBBk1oXwWXBP-Jhrf8mJA5VaozLjAqFj2HDVbl9oc) 这里的密钥，该怎么获取呢？怎么填？还有api地址对么？

看你的模型名字是错的，点击左侧管理按钮进行添加。不要自己填写，自己填写容易写错
