### ISSUE TITLE
webdav备份恢复的逻辑似乎有点问题

### ISSUE THREAD

**Issue by sandlong** [kangfenmao/cherry-studio#178]
比如备份完成之后，换一台电脑首次安装应用，填入webdav信息之后点恢复备份，就会报错。
![1](https://github.com/user-attachments/assets/f72b4154-3007-4c11-972d-3654b6c1e1c5)

这里的逻辑似乎是本地先要有cherry-studio.backup.zip才能恢复备份，但对于新安装的应用这就是一个问题。

**Comment by kangfenmao** [comment]
这是个 BUG，我得修一下

**Comment by kangfenmao** [comment]
感谢提供反馈，这个问题已经修复，下个版本上线 @sandlong
