### ISSUE TITLE
字体、查找等功能增加与BUG

### ISSUE THREAD

**Issue by 3377** [kangfenmao/cherry-studio#179]
**功能新增**
1. 自定义字体
2. 查找时候增加模型名，时间增加秒
3. work输出
4. 代码新增行数

**BUG**
1. 无滚动条
2. 长文本输入时生成文件后文本依旧保留

**Comment by kangfenmao** [comment]
需求合并 https://github.com/kangfenmao/cherry-studio/issues/158
