### ISSUE TITLE
设置问题反馈

### ISSUE THREAD

**Issue by xiaoshengwpp** [kangfenmao/cherry-studio#18]
基于 openAI 添加模型自定义服务商（聊着聊着 连续对话）  会出现
`Error: 400 messages: first message must use the "user" role`
错误提示；
咨询了上游服务商 ，说是 需要调整max tokens 的数值。
我尝试 使用ChatGPT Next  复现上面的报错 ，在ChatGPT Next设置中 调大max tokens 数值后 得到了解决

问题：没有在软件 中找到设置 这个的参数

ChatGPT Next  这个里面有这个
能否增加 或 其它解决方案

**Comment by kangfenmao** [comment]
可以增加这个配置 @xiaoshengwpp

**Comment by kangfenmao** [comment]
功能开发完成，等下一个版本发布

**Comment by kangfenmao** [comment]
已发布 https://github.com/kangfenmao/cherry-studio/releases/tag/v0.5.0

@xiaoshengwpp
