### ISSUE TITLE
请停止对我的邮件进行骚扰

### ISSUE THREAD

**Issue by liuran001** [kangfenmao/cherry-studio#182]
我不认为一款出色的开源软件需要和诈骗邮件一样反复推送给我
![Screenshot_2024-10-14-06-33-51-50_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/fa7598f1-c7db-4caa-882e-accf1f6c0442)

**Comment by kangfenmao** [comment]
收到，邮件发送逻辑有误导致重复发送，抱歉给你带来困扰
