### ISSUE TITLE
缺陷：检查更新按钮不生效

### ISSUE THREAD

**Issue by CraxGrix** [kangfenmao/cherry-studio#184]
https://github.com/user-attachments/assets/aae09e35-9877-49e4-9e70-d753e188b3ae

检查更新后可以考虑弹出提示？

**Comment by kangfenmao** [comment]
行，这里估计是网络异常情况下没有能够正常检查出来。这里依赖的是 Github API，你可能要检查一下能否正常访问 Github

**Comment by CraxGrix** [comment]
> 行，这里估计是network异常情况下没有能够正常检查出来。这里依赖的是 Github API，你可能要检查一下能否正常访问 Github

我这边是全局🪜，所以应该不会出现无法访问Github的情况
