### ISSUE TITLE
请问文件如何删除？

### ISSUE THREAD

**Issue by wenbiao-ops** [kangfenmao/cherry-studio#185]
![2024-10-14_15-49-41](https://github.com/user-attachments/assets/832f98e2-6b0b-4cc5-b93a-b206adf33983)

**Comment by kangfenmao** [comment]
暂时只能先删除掉和文件关联的那条聊天记录

**Comment by kangfenmao** [comment]
如果有文件无法正常删除，联系我的微信：kangfenmao
