### ISSUE TITLE
文件上传无法解析

### ISSUE THREAD

**Issue by jie0102** [kangfenmao/cherry-studio#188]
上传文件（包括PDF、TXT，其它未尝试）后，无论提出什么问题，提问几次，都是类似回复“Understood! If you have any specific requests or need further assistance, feel free to let me know.”的无用回答

**Comment by kangfenmao** [comment]
文件超过了 token 限制了吧

**Comment by kangfenmao** [comment]
是否有新进展 @jie0102

**Comment by jie0102** [comment]
> 是否有新进展 @jie0102 
已解决，如你所说

**Comment by kangfenmao** [comment]
行，那我先关闭 issue 了，有其他问题随时开新 issue
