### ISSUE TITLE
讯飞星火还不支持吗？

### ISSUE THREAD

**Issue by li5bo5** [kangfenmao/cherry-studio#189]
讯飞星火还不支持吗？

**Comment by 1355873789** [comment]
后面会加

**Comment by hdestiny** [comment]
讯飞星火也有OpenAI兼容的接口，自己添加就行了

**Comment by kangfenmao** [comment]
需求合并到这里：https://github.com/kangfenmao/cherry-studio/issues/68#issuecomment-2413421330

**Comment by kangfenmao** [comment]
<img width="754" alt="image" src="https://github.com/user-attachments/assets/387c7a8b-1bdf-44dc-92d7-67f5c588ff4c">

每个模型都有单独的 key，你自己手动添加吧 @li5bo5
