### ISSUE TITLE
支持聊天历史记录搜索功能

### ISSUE THREAD

**Issue by z-jt-best** [kangfenmao/cherry-studio#19]
建议在聊天上下文中添加搜索功能，方便根据关键字找到历史回复信息，不然聊天的消息长了，找到之前的回复需要手动滚动查看

**Comment by kangfenmao** [comment]
采纳建议 @z-jt-best

**Comment by DrayChou** [comment]
请问，后面会考虑支持类似于 lobe 那样的插件吗？

**Comment by DrayChou** [comment]
请问，后面会支持导出导入配置吗？

**Comment by kangfenmao** [comment]
> 请问，后面会支持导出导入配置吗？

支持

**Comment by kangfenmao** [comment]
> 请问，后面会考虑支持类似于 lobe 那样的插件吗？

会添加一些核心插件功能，至于开放插件 API 暂时还没有考虑到哪一步，现在优先开发大家最需要的功能

**Comment by shaoyun** [comment]
建议支持dall-e-3画图

**Comment by kangfenmao** [comment]
> 建议支持dall-e-3画图

近期支持

**Comment by Thinkerzhangqian** [comment]
希望问答内容支持导出 markdown或者word

**Comment by Thinkerzhangqian** [comment]
希望能导出整个对话为markdown。有的对话鼠标悬停也不会出现保存图标
![Uploading 1724206015526.jpg…]()

**Comment by Thinkerzhangqian** [comment]
希望能导出整个对话为markdown。有的对话鼠标悬停也不会出现保存图标
![WeChat0c76a03e34b6cd7f4a765cba24710055](https://github.com/user-attachments/assets/c8c8630d-b651-4e54-8c0d-60850852bf51)

**Comment by kangfenmao** [comment]
收到，我已加入到开发计划列表 @Thinkerzhangqian

**Comment by shaoyun** [comment]
发送快捷键建议改为全局设置

**Comment by kangfenmao** [comment]
> 发送快捷键建议改为全局设置

现在就是全局设置

**Comment by Mymoliy** [comment]
希望支持图片和文件功能

**Comment by kangfenmao** [comment]
> 希望支持图片和文件功能

已经在开发中了

**Comment by kangfenmao** [comment]
> 后续有实现快捷提问或翻译的计划吗，支持快捷键或者任务栏图标，类似chatgpt客户端、豆包哪种桌面快速启动的这种：
> 
> 
> 
> <img width="768" alt="image" src="https://github.com/user-attachments/assets/418bde04-551a-47c8-8153-88f77cfb511a">
> 
> 
> 
> <img width="816" alt="image" src="https://github.com/user-attachments/assets/c1cd6c6b-261b-43ea-b60c-e68aa50597a8">
> 
> 
> 
> 

计划了，增强翻译将会有更多功能，包括文档翻译等

**Comment by valens7** [comment]
厉害了, 谢谢大佬开发这么好用的工具. 看了一遍所有的issue, 这趋势cherry以后可以说是豆包的平替了(甚至更强大).  
豆包只支持他们自己的模型，而cherry可以选择很多模型.

**Comment by kangfenmao** [comment]
历史记录搜索功能已经开发的差不多了，国庆期间上线

**Comment by kangfenmao** [comment]
历史记录搜索功能：https://github.com/kangfenmao/cherry-studio/releases/tag/v0.7.12
