### ISSUE TITLE
功能需求：希望输入框能够支持拖拽添加附件

### ISSUE THREAD

**Issue by icychick-liu** [kangfenmao/cherry-studio#190]
如动图，当前拖拽附件到输入框时，会显示“复制”，但到输入框中释放文件时，文件不会添加到附件中。
![cherrystudio无法拖拽粘贴](https://github.com/user-attachments/assets/fd09b6cb-3569-43f7-be29-e818fe0c49b7)

**Comment by kangfenmao** [comment]
可以，可以 Ctrl + v

**Comment by kangfenmao** [comment]
开发完成

**Comment by icychick-liu** [comment]
> 开发完成

大佬威武！！！
