### ISSUE TITLE
是否可以添加多KEY？

### ISSUE THREAD

**Issue by Sucorde** [kangfenmao/cherry-studio#194]
如果我有一个厂商有多个KEY。是否可以都添加去？
先检测第一个KEY，可以用就输出，如果不可用，就检测第二个KEY。
例如我有23个KEY，是否可以批量添加？
然后一个KEY一个输入框，检测的时候，当KEY不能用了这个输入框就变红。可以选择是否删除。

这个功能好像很多客户端都没有。

**Comment by kangfenmao** [comment]
可能这个是小众需求吧，提这个问题的人比较少，后续需求的人多了再做吧，毕竟开发者精力是有限的，先挑重要的弄

**Comment by Sucorde** [comment]
这个不急，有时间弄以下也可以的。

**Comment by kangfenmao** [comment]
更新到新版本

**Comment by Sucorde** [comment]
问你个问题啊。你这个多Key是使用,号分隔的，时间长了难免有很多很多很多很多没有用的key了。这种情况是否会增加轮询的时间？因为太多了，我也不确定那些能用，那些不能用，就不停的往后面加新的key。

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/d7b78d94-78c8-40ba-96e4-186eccbce224)
有的时候会提示没有配置key，但是重新问一下又可以了。

**Comment by kangfenmao** [comment]
有 key 无效了

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/0c70c601-1d1e-452a-9291-e8070dcb7b79)
我画了个草图，你看下。

**Comment by Sucorde** [comment]
那个啥，能不能添加一个多行填写？就是现在的key一般都是有特定的开头的，如果输入一堆KEY的时候可以自动排序。然后也别规定死使用逗号，也可以一行一个的填写方式。

**Comment by Sucorde** [comment]
sb-bhbcvxnebbehbzbnbgdpqbfewbbpmcbhzrlxbxbqqnbyflcb
sb-exwmvbbebjsfltcxzqpgmezxgydnypibbsilxtbbxbqzxebb
sb-rbbwbnrgibbbetdybdbgjwnhjhpggvxbfwsdbnbinblmesfl
sb-qymbqfmsbzwpzighbfmttnfwzqsqgxbplnblbbbidvbbdvhy
sb-lbqjqyzihpblevblgmzetrsbbbzsmmlbbehgcdyclqbmbbbg
sb-elxnzxybwxyblbwnybbnbjvtefphbwplbbtyfwsxnyfdvcpw
sb-ipwptbbcmbeletqbvgbsnbrlbtepvvvjbtlvmqvbmyibbbbg
sb-bbeszmbczqvbhmbqndrwfifmlcbcztxymdqwbnfhvwpjbjbe
sb-xrzmdbtdttibsjbnebzfdnsreybxvjphmwcrxeizcbczifbd
sb-fzbgtwbpmwhbbnjbxmbvxtbbybcrlbbhmjczbjqxvvwjbgtn
sb-pwbyvfbbivcpbmbjlbwelbzdbxibbcbmgjbbqsbbbdptvrbm
sb-zblsgmzqlbrhvbcgbvrlczypfvcmxmlhdjbcspzdibnwrbbb
sb-ysvbrrihezlrcvqqbghfllvbzqvebxjsnzxbjttwbbelnfdr
sb-sxmbbjcqslgnbbbwctvlwdlbbnjrggswfejlnresbdqgtvjt
sb-jwrgdfqegtjnqxsnipqtbblbbvhwprxbxgngzbwnjbgrwzzb
sb-rbbcfypnzbxirsrbidqbqhgzmxejbsmbdzcwxfgpfyfybppb
sb-tzfdyzbyxszeblpzzwzbbtgbyxeehbemeefvmpcschivlibb
sb-qmeysbzgqydrxbmhbcvejyqbfmbbttpwqvblxcyjbpdmbbis
sb-fdpnjcdnztflcbbtztxbebtzbmbsecnqbxjydbevbiblbzri
sb-bhgjndtbzbpbxeemfbzfcnrljdbczyrhjwvqybblqixdwiwn
sb-dsjiscptbhrvfcmjbybbtvhxplbcjxqbzbzdmbbpcjbnvfnr
sb-bbgpemddffjmewrbeembbbfwgbjigpbbvrygjlffybpvbtev
sb-tefvpfdehegybrrvhwvbejhbpbxgebzbtnijbgbbgvftbsmv
sb-mbqjvgvzrvswbhccbnbbwxtyzspbxeycrrnzxcbwtzpbibzn
sb-bbxqhlgfmvrjbhhdfdplmvvbbrhitbvlgmbjsgydnsbrbtbc
sb-phehvphyigplybrbwrjysysvvhlbqzdcqbbsmstibwdbsgqh
sb-pbxdbbsplcblzivlslbgmeexbmbjhmmrrbwymbvefpxgixzy
sb-whqmgnlyflqbwbzmcsetbbybwrncyqzlmfxegtzsfjtinblv
sb-tbrdcbbnviybbsftbmlnbmxwftlbssevlzmeggjfwweicxyy
sb-yqjiybpnertrwvpmncbbytqvbxswbqcsivbpehbsvjbqivby
sb-bvmppwbybbszlhmcynzbgnbcbrshcpndvqpvsflbhbnpmbyy
sb-gbiptpbtmyjxsqghbpzcwdbvjijmfbexcbjnbfdvwbzpnfnv
sb-ltlbibrmjjzrsiibivfrvbfrhbviynwlzpnfddqbtfvblnqx
sb-yxdjbgvpqjdzvbgysrderqbcbvcwlbhdebbzzilzgtberidl
sb-bcbswtwidctyqidxxqhscntbdycbcvbleeqrbydbwcwyecrn
sb-bcnbezphhigjfltbtbqegtenyiigtwbbwbbivbhxtmbnfbmm
sb-gwfbwzbbnjdnyybxjbbtclevndmthbqbhbtbxfbjembhlbbq
sb-cbptdbbynyfqwbwielhbnfyrwvbzqhdtzljncwwqznmzbbft
sb-binebbzbibbwmbnfdgqdtbdvslspmllszbzifcxnvpbdzzxm
sb-bvbdsgdmxjstpbrcnbigpnnqjdgbbicsplbewpzqmbblsbjr
sb-nmydmptsnvzcpbjgmqrepbsbbcxznbhxigybdfpzqbvmnbdm
sb-bbblcmdbzpcsfcbfcsbjpbeqnjbcqbbxdlbimqimhhexeeth
sb-ibqelxwvyssqbizethlyzjdpfzgbfzrphdmbyhlzbyzdtlmd
sb-rbtbbbqgnishjgbnrbicidzmbmsrpiwppppdiybgbyssyxff
sb-vbmvhdbrxjeeifjtezbgxqebbqqsexybdvqsbwbrbbfiezhb
sb-lpgyhbrqbqjenbbfjbgzpebvibvzrieprpmcmnvgsrvbbmbb
sb-bibqbwnzybpvbbnxvmgbbfmylbmzrnbqblemspbqzbqdqhmb
sb-zqqcfebsbbgjncrqzszzwchhibjiiygzbyqpbbpyvxbbzvtb
sb-qhsgbiwsbjtprjbzvgcbscnbcxinihbbbwbbtwdsprbxnihg 例如这样的填写方式。

**Comment by Sucorde** [comment]
不在了吗？现有的方式真的很不好用。

**Comment by kangfenmao** [comment]
> 不在了吗？现有的方式真的很不好用。

可以，我加上这个
