### ISSUE TITLE
今年的计划有工作流么？

### ISSUE THREAD

**Issue by Sucorde** [kangfenmao/cherry-studio#195]
可视化的工作流，真的是很好用。

**Comment by kangfenmao** [comment]
今年估计弄不出来了，还有很多功能没有开发完善，先把短板补齐了吧

**Comment by kangfenmao** [comment]
> 有计划大概什么时候会改为闭源吗？ 例如出个企业版什么的。

开源一直都在，未来也会在。闭源的也在同步进行。两个定位不一样

**Comment by Sucorde** [comment]
我建议一下哈，开源的可以卖个会员，会员可以调用你们的API，企业的基本上都是希望使用本地模型架设。最好也有一键架设所需服务，可以在服务端直接从你们的服务器上下载模型，模型也要全。
