### ISSUE TITLE
Can reka ai's support be added?

### ISSUE THREAD

**Issue by fxcl** [kangfenmao/cherry-studio#197]
https://docs.reka.ai/quick-start

**Comment by kangfenmao** [comment]
<img width="1463" alt="image" src="https://github.com/user-attachments/assets/aeb602eb-4198-430a-901f-45eb0d1270e8">

Try setting it like this

**Comment by fxcl** [comment]
![Uploading image.png…]()

**Comment by fxcl** [comment]
![image](https://github.com/user-attachments/assets/3d0e04b4-757e-4a80-90fc-acc5181795a4)
