### ISSUE TITLE
你们的默认字号太小了，希望加入字号字体调整

### ISSUE THREAD

**Issue by Ali1995A** [kangfenmao/cherry-studio#199]
你们的默认字号太小了，希望加入字号字体调整

**Comment by kangfenmao** [comment]
> 你们的默认字号太小了，希望加入字号字体调整

消息的字大小已经支持调整了，你在设置面板里面修改

**Comment by SCzfdf** [comment]
> > 你们的默认字号太小了，希望加入字号字体调整
> 
> 消息的字大小已经支持调整了，你在设置面板里面修改

能更换字体吗?  聊天的字体太丑了, 还不如直接用UI的字体

**Comment by kangfenmao** [comment]
还没做：https://github.com/kangfenmao/cherry-studio/issues/179

**Comment by kangfenmao** [comment]
需求合并：https://github.com/kangfenmao/cherry-studio/issues/158
