### ISSUE TITLE
配置openai的时候，不支持配置第三方的url

### ISSUE THREAD

**Issue by kuangquanshuisn** [kangfenmao/cherry-studio#2]
配置openai的时候，不支持配置第三方的url，不能修改url

**Comment by kangfenmao** [comment]
准备新增一个功能可以添加自定义的服务商 @kuangquanshuisn

**Comment by kangfenmao** [comment]
请问你用的是哪个第三方，我也去接入测试一下 @kuangquanshuisn

**Comment by kuangquanshuisn** [comment]
https://api.tu-zi.com/  ，基于[One API](https://github.com/songquanpeng/one-api)

**Comment by kangfenmao** [comment]
> https://api.tu-zi.com/ ，基于[One API](https://github.com/songquanpeng/one-api)

好的，我这两天增加一个添加自定义服务的功能

**Comment by kangfenmao** [comment]
功能已经开发完了，等上线吧

<img width="844" alt="image" src="https://github.com/user-attachments/assets/e4863430-bba1-4d48-808e-c284bd78820f">
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/2bb12fae-3d06-4391-920e-178aed56fce2">
