### ISSUE TITLE
不会自动换行。

### ISSUE THREAD

**Issue by magickzl** [kangfenmao/cherry-studio#20]
![image](https://github.com/user-attachments/assets/5b0e3c43-aa97-4034-8523-2ea36f37bef7)
![image](https://github.com/user-attachments/assets/97dcee10-6bb9-4063-885b-1b0f82550fca)

发送过长文字时，有时它不会自动换行。右边内容直接不可见了，右侧话题设置栏直接消失了。
然后最新版暗黑模式按钮似乎也有问题。

**Comment by kangfenmao** [comment]
明天修复，需要你复制一下没有换行的这条消息粘贴到下面 @magickzl

**Comment by magickzl** [comment]
@kangfenmao 任意找一个网站，代码多一些的，直接复制所有网站代码发过去，一定会触发。

**Comment by kangfenmao** [comment]
感谢🙏我已定位和修复问题 @magickzl

**Comment by kangfenmao** [comment]
已经上线 https://github.com/kangfenmao/cherry-studio/releases/tag/v0.5.3

**Comment by kangfenmao** [comment]
@magickzl 闲了帮忙验证一下看是否修好吧

**Comment by magickzl** [comment]
已经修好了，作者好厉害，这么快。
