### ISSUE TITLE
.java 格式文件上传支持

### ISSUE THREAD

**Issue by ufvice** [kangfenmao/cherry-studio#201]
希望支持.java后缀的文件上传
软件版本：0.8.1-x86_64.AppImage

**Comment by ufvice** [comment]
em ，直接close了吗？
我在archlinux上，拖动.java代码文件拖不进去，用dolphin文件管理器也会自动把.java类型过滤掉。
而其他的txt和docx就可以正常上传

**Comment by kangfenmao** [comment]
> em ，直接close了吗？ 我在archlinux上，拖动.java代码文件拖不进去，用dolphin文件管理器也会自动把.java类型过滤掉。 而其他的txt和docx就可以正常上传

<img width="453" alt="image" src="https://github.com/user-attachments/assets/f49e541b-ce97-47a0-bbbd-5947c57261bc">

**Comment by kangfenmao** [comment]
已经第一时间改完了，只不过，你要等新版本发布。或者自己构建一下也行
