### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by deanhzed** [kangfenmao/cherry-studio#203]
```
\[
1 \text{欧元} \times 7.5 \text{人民币/欧元} = 7.5 \text{人民币}
\]
```
显示成了
![图片](https://github.com/user-attachments/assets/5099ce24-7033-452d-ab42-c302fd192a71)

**Comment by kangfenmao** [comment]
> \[
> 1 \text{欧元} \times 7.5 \text{人民币/欧元} = 7.5 \text{人民币}
> \]

这个问题是由于第三方库导致的问题，第三方库对中文公式显示有问题，暂时无法解决这个问题

https://github.com/remarkjs/remark-math/tree/main

**Comment by kangfenmao** [comment]
<img width="1216" alt="image" src="https://github.com/user-attachments/assets/7e6b465d-f0c7-4011-9764-a17ece6ba9e2">

有新的进展，这里增加了新的选项可以解决这个问题
