### ISSUE TITLE
[Bug] GPT-4o will report an error when asking for images by Github models

### ISSUE THREAD

**Issue by frondesce** [kangfenmao/cherry-studio#204]
As shown in the picture:
![image](https://github.com/user-attachments/assets/3a36af9c-aa59-4bcd-8665-2d4d2c842621)

The error code is: Error: 431 status code (no body)，But it's no problem to test the connection in the configuration.

![image](https://github.com/user-attachments/assets/dad595f8-aed9-4c40-a462-0bb6c9688dbe)

**Comment by kangfenmao** [comment]
Github Models 不支持图片

**Comment by frondesce** [comment]
> Github Models 不支持图片

While, I tried to use other front-end programs, such as next-web, which can respond to pictures. GitHub's model description also makes no mention of the inability to use images.
Is it a current bug or is the program design not yet supported?

**Comment by kangfenmao** [comment]
是我理解错误，我还没做请求图片回复的功能

**Comment by frondesce** [comment]
> 是我理解错误，我还没做请求图片回复的功能

Got it. Thanks~

**Comment by kangfenmao** [comment]
The issue has been fixed, and the new version will be released over the weekend

**Comment by frondesce** [comment]
> The issue has been fixed, and the new version will be released over the weekend

I tried the new version, and it can indeed recognize pictures perfectly, which is great! grateful!
