### ISSUE TITLE
文件保存相关问题

### ISSUE THREAD

**Issue by duanshuai-0229** [kangfenmao/cherry-studio#208]
1.默认保存的名称为时间且其中存在空格，无法直接保存，需要重命名。
2.保存为.md格式，打开文件后数学公式无法正常显示。

**Comment by kangfenmao** [comment]
> 1.默认保存的名称为时间且其中存在空格，无法直接保存，需要重命名。 2.保存为.md格式，打开文件后数学公式无法正常显示。

能否贴一下 md 文件

**Comment by duanshuai-0229** [comment]
[222.md](https://github.com/user-attachments/files/17434073/222.md)
[pugan公式.md](https://github.com/user-attachments/files/17434198/pugan.md)

文件分别由deepseek和Qwen回答生成后保存

只有vs code在安装插件后可以正常显示，Typora、Obsidian等都无法正常显示。

用txt打开会发现公式都没有$$


> > 1.默认保存的名称为时间且其中存在空格，无法直接保存，需要重命名。 2.保存为.md格式，打开文件后数学公式无法正常显示。
> 
> 能否贴一下 md 文件

**Comment by duanshuai-0229** [comment]
![QQ20241018-185233](https://github.com/user-attachments/assets/01dd1dbd-f408-4f23-b898-e77850ba9c03)
![QQ20241018-185305](https://github.com/user-attachments/assets/a48c5c4e-d3df-4e8e-85b5-3f2eaf7ad2dd)


> > 1.默认保存的名称为时间且其中存在空格，无法直接保存，需要重命名。 2.保存为.md格式，打开文件后数学公式无法正常显示。
> 
> 能否贴一下 md 文件

**Comment by kafkazov** [comment]
第1个问题确实存在，每次都是需要重命名。以及，顺便提一个需求，不能将整个对话记录保存为md文件吗？比较需要这个功能，还是说是我自己没找到怎么做？

**Comment by kangfenmao** [comment]
保存整个对话功能在另外一个 issue 已经提到了，还没做

**Comment by kangfenmao** [comment]
公式导出出去，其他软件不能识别，应该是其他软件的问题或者模型回复的问题。

1. 文件保存命名问题已经解决
2. 现在已经支持保存整个对话记录

新版本已经发布，如果有进一步的想法，可以新开 issue 讨论
