### ISSUE TITLE
备份到WebDav: 405 Method Not Allowed

### ISSUE THREAD

**Issue by forrany** [kangfenmao/cherry-studio#209]
确认账号、密码配置正确

并且，可以创建对应的目录，但是过一会会弹出备份失败：

<img width="478" alt="image" src="https://github.com/user-attachments/assets/fd2f1afe-bf1c-4c4a-9277-ec5066cfc1bd">

**Comment by kangfenmao** [comment]
> 确认账号、密码配置正确
> 
> 并且，可以创建对应的目录，但是过一会会弹出备份失败：
> 
> <img alt="image" width="478" src="https://private-user-images.githubusercontent.com/29779326/377813730-fd2f1afe-bf1c-4c4a-9277-ec5066cfc1bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDQ4OTEsIm5iZiI6MTcyOTI0NDU5MSwicGF0aCI6Ii8yOTc3OTMyNi8zNzc4MTM3MzAtZmQyZjFhZmUtYmYxYy00YzRhLTkyNzctZWM1MDY2Y2ZjMWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA5NDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NjcxOTFmZmQ2ZWE3ZDg5ODBkNmVmZmUwYTEyNDM4MmRiM2QzZjYyOTMzNzc1N2MzNmE4M2ZhNTVjMTlhNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3f4pfdXBWUj_wPMlUedQp_eUNg9pUe4Rt5PnN3RgHGw">

上游服务不支持，你可以换一个服务。目前已知电信云盘不行

**Comment by kangfenmao** [comment]
换服务能否解决问题？

**Comment by forrany** [comment]
> 换服务能否解决问题？

感谢回复～

排查了下，的确是我webdav的问题。

我用的cloudreve自建的，搭配的腾讯云cos存储桶。 发现这两天服务器ip被墙了（美国的机器），然后可能腾讯云的回调有问题，上传文件会失败。。。

这个 issue 可以先关闭，再次感谢回复🙏
