### ISSUE TITLE
会不会和这个功能一样了？

### ISSUE THREAD

**Issue by zhuzhuyule** [kangfenmao/cherry-studio#21]
类似这个项目https://github.com/lobehub/lobe-chat？
这玩意加个壳子和本项目好像一样了

**Comment by kangfenmao** [comment]
感谢你提出疑问，每个项目都有相似的地方也各有各的特点。虽然目前可能有很多类似的地方，但是后面发展和侧重点也会不同。

在AI的项目中，多样化是非常重要的，各种不同的软件可以满足不同人群的需求和偏好。

举个例子：即使像奔驰这样的知名品牌已经足够好，但其他品牌的出现和发展可以带来更多的选择和创新。

@zhuzhuyule

**Comment by zhuzhuyule** [comment]
嗯嗯，那你可以考虑考虑搬一些功能进来 哈哈。
加油💪🏻
