### ISSUE TITLE
Github model只支持8k上下文，这个可以调整吗？

### ISSUE THREAD

**Issue by vimbackground** [kangfenmao/cherry-studio#210]
如图：使用github model时，模型的上下文限制在了8000tokens。

请问这个是平台本身的限制，还是可以通过本地的设置、或者平台的设置让上下文更长一些？

![ghc_limit](https://github.com/user-attachments/assets/a319ab62-ea7c-41f9-91bf-9897df04f3fd)

**Comment by Sucorde** [comment]
这个是平台本身的限制，不仅限制长度，还限制回复次数。

**Comment by vimbackground** [comment]
好的，谢谢回复
