### ISSUE TITLE
希望支持 gemini api ，以及支持字体大小调节

### ISSUE THREAD

**Issue by corwin1949** [kangfenmao/cherry-studio#22]
感谢作者。冒昧提几个功能建议：

1. 现在谷歌 gemini1.5-exp 也很强了，不知道会不会支持它的api。

2. claude的api请求地址可以自定义吗，或者在用户增加新接口的加上其他接口模式，如claude格式。
毕竟直接用claude有点难，创建账号都有点麻烦。

3. 可以让用户设置字体大小吗，年纪大了，小字体看的我眼睛疼。

**Comment by kangfenmao** [comment]
建议非常好，我先解答一下：

1. 我会增加一个 Gemini 的 Provider
2. Claude API 没有开放自定义，后面版本我会把这个设置成可以编辑模式。
3. 我会加一个字体大小调节的地方，你可以暂时用 Command(或Ctrl) + "➕" 快捷键放大一下，Command + 0 恢复

等开发完成了，我会在这里跟你说 @corwin1949

**Comment by deanhzed** [comment]
gemini不就是
https://generativelanguage.googleapis.com
么

**Comment by kangfenmao** [comment]
@corwin1949 你的 Claude API key 在哪里买的，我去官方没有申请成功

**Comment by kangfenmao** [comment]
- [ ] Gemini
- [ ] Claude API 地址支持编辑
- [ ] 设置字体大小

**Comment by corwin1949** [comment]
> 建议非常好，我先解答一下：
> 
> 1. 我会增加一个 Gemini 的 Provider
> 2. Claude API 没有开放自定义，后面版本我会把这个设置成可以编辑模式。
> 3. 我会加一个字体大小调节的地方，你可以暂时用 Command(或Ctrl) + "➕" 快捷键放大一下，Command + 0 恢复
> 
> 等开发完成了，我会在这里跟你说 @corwin1949

感谢！反馈好快。

**Comment by corwin1949** [comment]
> @corwin1949 你的 Claude API key 在哪里买的，我去官方没有申请成功

我现在Claude 的用量不大，是共用朋友的 API。

之前我用过这个：https://www.ohmygpt.com，价格是原价的1.1倍。
还看过到这个https://one.gptnb.ai，但是没用过。

这两个我不确定质量好不好，因为现在没在用。

等晚上我把这贴删了，不做它们广告，不清楚质量。

**Comment by corwin1949** [comment]
> @corwin1949 你的 Claude API key 在哪里买的，我去官方没有申请成功

@kangfenmao 原来github是没有私信的……

我现在用量少，是朋友分享的。你要用的话可以看下面几家。

- [ohmygpt](https://www.ohmygpt.com?aff=VzMNAEL3)，用过，原价1.1倍
- [gptnb](https://one.gptnb.ai)，没用过，貌似便宜点
- [oaipro](https://api.oaipro.com)，没用过，听说比较稳定

这贴晚上删吧，不给它们打广告，嘻嘻

**Comment by kangfenmao** [comment]
<img width="754" alt="image" src="https://github.com/user-attachments/assets/7db4f682-b523-4d20-a2a4-329945827215">

模型加载 OK

**Comment by kangfenmao** [comment]
已经开发完毕，下个版本发布

**Comment by corwin1949** [comment]
> 已经开发完毕，下个版本发布
> 
> <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/8253512/357340649-7a3c0ee7-4eaa-4a97-a0bf-0c1ac8089838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDIzODQsIm5iZiI6MTcyMzU0MjA4NCwicGF0aCI6Ii84MjUzNTEyLzM1NzM0MDY0OS03YTNjMGVlNy00ZWFhLTRhOTctYTBiZi0wYzFhYzgwODk4MzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDk0MTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODYwOTg4OTAzMzdkOWMwZWFiOTlkN2NmZjI2ZWU4ODQ0ZWQxMzkwZTAyMmFiOTQ5MDcwMDI2NWZmMDM2MDFjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dq8ugx7Ds3sFE754jK3Anbi9rD2_UZVpOSvllxX-BPc">

牛逼！太强了👍
