### ISSUE TITLE
代码折叠功能

### ISSUE THREAD

**Issue by jinxiayuandong** [kangfenmao/cherry-studio#221]
显示代码的时候，右上角的复制按钮可以一直显示在右上角，而不是一直固定在代码最开始的地方。
类似这种效果（claude）
![image](https://github.com/user-attachments/assets/7b241dac-4b41-45b2-8801-a9a660975856)

**Comment by kangfenmao** [comment]
> 显示代码的时候，右上角的复制按钮可以一直显示在右上角，而不是一直固定在代码最开始的地方。 类似这种效果（claude） ![image](https://private-user-images.githubusercontent.com/131273517/378167396-7b241dac-4b41-45b2-8801-a9a660975856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NzAwNjksIm5iZiI6MTcyOTQ2OTc2OSwicGF0aCI6Ii8xMzEyNzM1MTcvMzc4MTY3Mzk2LTdiMjQxZGFjLTRiNDEtNDViMi04ODAxLWE5YTY2MDk3NTg1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwMDE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODNkZDU2NDgxZGYwOGUyNDI0YTBhNjI0NTFlZmI0MjE3ZTcwODU2MThlNzYyMWRhYTJmMTNlNzQzZWQxYTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lnZFZQviMMbKKar-IKDBDS-Wi-omKjHzBBLqP7KGPno)

这样做有什么优势吗

**Comment by mokoru** [comment]
> > 显示代码的时候，右上角的复制按钮可以一直显示在右上角，而不是一直固定在代码最开始的地方。 类似这种效果（claude） ![image](https://private-user-images.githubusercontent.com/131273517/378167396-7b241dac-4b41-45b2-8801-a9a660975856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NzAwNjksIm5iZiI6MTcyOTQ2OTc2OSwicGF0aCI6Ii8xMzEyNzM1MTcvMzc4MTY3Mzk2LTdiMjQxZGFjLTRiNDEtNDViMi04ODAxLWE5YTY2MDk3NTg1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwMDE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODNkZDU2NDgxZGYwOGUyNDI0YTBhNjI0NTFlZmI0MjE3ZTcwODU2MThlNzYyMWRhYTJmMTNlNzQzZWQxYTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lnZFZQviMMbKKar-IKDBDS-Wi-omKjHzBBLqP7KGPno)
> 
> 这样做有什么优势吗

代码内容很长时复制不用再滚动上去了

**Comment by kangfenmao** [comment]
现在代码比较长，我在考虑加一个开关限制代码高度，这样就可以在代码块内部滚动了，不会占用太多空间

**Comment by jinxiayuandong** [comment]
> 现在代码比较长，我在考虑加一个开关限制代码高度，这样就可以在代码块内部滚动了，不会占用太多空间

感谢接受建议。

**Comment by kangfenmao** [comment]
已经支持
