### ISSUE TITLE
识别图片错误

### ISSUE THREAD

**Issue by kxh4892636** [kangfenmao/cherry-studio#223]
使用零一万物-vision api 识别图片, 图片没有上传, 从零一万物平台查看 token 用量, 图片就是没有上传
![Cherry_Studio_77NHN0znOZ](https://github.com/user-attachments/assets/37e1f838-99fb-4991-ae9b-94160f06e726)

**Comment by kangfenmao** [comment]
其他模型有问题吗

**Comment by 1355873789** [comment]
测试没有问题的，你直接截屏粘贴试试可不可以识别。
另外你的图是手机发送到微信后下载的吗，有的图片经过微信压缩后会有概率出问题。

建议先排查下哪个环节有问题
1. 同个图片其他vision模型能识别但yi-vision识别不了——模型的问题
2. 不同图片有的能识别有的不能识别——图的问题
3. 所有识图模型都识别不了任何图片——软件的问题（试试卸载重装）

**Comment by kxh4892636** [comment]
我更换了多张图片, 均是图片没有上传, 不过我在零一万物官网上图片是可以识别的
此外我也没有其他的模型 api 了, 所以无法测试其他模型

**Comment by kxh4892636** [comment]
此外发现一个 bug, 我创建自己的 prompt 之后, 如果把软件重装一下, 我的智能体界面依旧存在 prompt, 但是添加助手界面就不存在了, 必须删除在重新创建才有

**Comment by kangfenmao** [comment]
已经发布
