### ISSUE TITLE
希望能添加实时语音支持

### ISSUE THREAD

**Issue by JasonxlxCharles** [kangfenmao/cherry-studio#225]
realtime的API已经出了，可是市面上支持实时语音的前端并不多

希望能添加该功能，非常感谢！

**Comment by JasonxlxCharles** [comment]
> 方便的话，可以帮我贴一些文档进来，我开发的时候可以作为参考

本人纯小白，具体的技术文档确实一窍不通，不过我找到了一个现在已经支持高级语音的客户端，再次感谢

https://github.com/Dooy/chatgpt-web-midjourney-proxy

**Comment by kangfenmao** [comment]
需求合并：https://github.com/kangfenmao/cherry-studio/issues/41
