### ISSUE TITLE
[BUG] 为什么选择附件的时候不支持图片类型？

### ISSUE THREAD

**Issue by bingal** [kangfenmao/cherry-studio#229]
<img width="726" alt="image" src="https://github.com/user-attachments/assets/9f1791aa-d105-47f9-81ac-8b6bb80f06ad">
我是 mac intel 环境，点击聊天窗口的图片或文件上传按钮之后，文件选择里图片类型是灰色的，似乎只支持文档代码格式，图片不管 jpg，png 格式都是灰色不能选择？

**Comment by kangfenmao** [comment]
1. 你选的模型是否支持图片？
2. 软件版本是多少

提供点信息给开发者

**Comment by bingal** [comment]
1、我的模型是硅基 QWEN2-VL-72B-INSTRUCT，支持图片，不过不是直接用硅基的 api，是通过我自己搭建的 one-api 接口调用的，设置为 openai 类型
2、软件版本是最新的 0.8.1

**Comment by kangfenmao** [comment]
> 1、我的模型是硅基 QWEN2-VL-72B-INSTRUCT，支持图片，不过不是直接用硅基的 api，是通过我自己搭建的 one-api 接口调用的，设置为 openai 类型 2、软件版本是最新的 0.8.1

Qwen2-VL 支持已经加上了，下个版本发布

**Comment by bingal** [comment]
太好了，顺便硅基提供的 InternVL2 也支持一下，感谢

**Comment by kangfenmao** [comment]
> 太好了，顺便硅基提供的 InternVL2 也支持一下，感谢

是的都支持了

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/3878ac55-604d-4729-9de4-82cb33546763">

**Comment by kangfenmao** [comment]
已发布
