### ISSUE TITLE
提供火山引擎的豆包模型支持

### ISSUE THREAD

**Issue by isbn9877007** [kangfenmao/cherry-studio#23]
非常感谢作者的付出，希望能够添加豆包大模型的支持，（毕竟送了那么多，不用可惜了），以及后续是否有关于api支持文件上传后，也能够支持文件上传，谢谢作者

**Comment by kangfenmao** [comment]
感谢建议，马上安排 @isbn9877007

**Comment by kangfenmao** [comment]
豆包模型已经接入，下个版本发布 @isbn9877007 

<img width="761" alt="image" src="https://github.com/user-attachments/assets/d5a4ade5-666c-4a3e-b97b-64aa2ee0b8b2">
<img width="732" alt="image" src="https://github.com/user-attachments/assets/34130641-af2d-4913-a853-5ddf698bca9a">

**Comment by kangfenmao** [comment]
新版本已发布，更新到 v0.5.5 版本

https://github.com/kangfenmao/cherry-studio/releases/tag/v0.5.5
