### ISSUE TITLE
开启Markdown渲染后回答中数学公式不能被单独选中复制

### ISSUE THREAD

**Issue by czz404** [kangfenmao/cherry-studio#230]
如回答中“\( F(9, 10) \)”部分，鼠标选择整句话时无法选中这些公式内容，造成想单独复制某句话时缺少内容

**Comment by kangfenmao** [comment]
> 如回答中“( F(9, 10) )”部分，鼠标选择整句话时无法选中这些公式内容，造成想单独复制某句话时缺少内容

因为公式不是文字，而是图。你可以复制出来之后再选中复制一下

**Comment by czz404** [comment]
好的谢谢，我记得之前好像还不是这样的

**Comment by kangfenmao** [comment]
<img width="275" alt="image" src="https://github.com/user-attachments/assets/6c398015-4390-4e49-b837-521041d47450">

已修复，再试试看

**Comment by czz404** [comment]
可以了，但复制效果不是很完美，有时候公式复制出来会出现很多换行和乱码字符之类的，有没有可能优化一下？

![pic_1729778551.png](https://s2.loli.net/2024/10/24/jqlxXbfvuSVrGdi.png)

比如这个复制出来：

![pic_1729778899.png](https://s2.loli.net/2024/10/24/gEM6NjV5hb9iqtF.png)

**Comment by kangfenmao** [comment]
这个还真的解决不掉呢，其他软件无法识别

**Comment by czz404** [comment]
好的，谢谢啦
