### ISSUE TITLE
公式又不居中了

### ISSUE THREAD

**Issue by fresh-men** [kangfenmao/cherry-studio#231]
**公式不居中了，之前还是好好的：**
![image](https://github.com/user-attachments/assets/08b6416b-b426-4702-91a8-9868681545c9)

**渲染的内容应该前面应该会有小点的，但是cherry渲染的没有：**
![image](https://github.com/user-attachments/assets/09ee673e-1b36-42c4-96fd-c3a970ccd6eb)

**gpt生成的内容：**
Adam优化器是一种常用的梯度下降优化算法，结合了动量和自适应学习率。以下是Adam优化器的迭代步骤：

1. **初始化参数**：
   - 设定学习率 \(\alpha\)（通常为0.001）。
   - 设置一阶动量参数 \(\beta_1\)（通常为0.9）。
   - 设置二阶动量参数 \(\beta_2\)（通常为0.999）。
   - 设置一个小常数 \(\epsilon\)（通常为 \(10^{-8}\)）以防止除零错误。
   - 初始化一阶矩估计 \(m_0 = 0\)。
   - 初始化二阶矩估计 \(v_0 = 0\)。
   - 初始化时间步 \(t = 0\)。

2. **迭代更新**：
   对每个时间步 \(t\)：
 
   - 增加时间步：\(t = t + 1\)。
 
   - 计算梯度 \(g_t\)。
 
   - 更新一阶矩估计：
     \[
     m_t = \beta_1 \cdot m_{t-1} + (1 - \beta_1) \cdot g_t
     \]
 
   - 更新二阶矩估计：
     \[
     v_t = \beta_2 \cdot v_{t-1} + (1 - \beta_2) \cdot g_t^2
     \]
 
   - 计算一阶矩估计的偏差修正：
     \[
     \hat{m}_t = \frac{m_t}{1 - \beta_1^t}
     \]
 
   - 计算二阶矩估计的偏差修正：
     \[
     \hat{v}_t = \frac{v_t}{1 - \beta_2^t}
     \]
 
   - 更新参数：
     \[
     \theta_t = \theta_{t-1} - \alpha \cdot \frac{\hat{m}_t}{\sqrt{\hat{v}_t} + \epsilon}
     \]

3. **重复**上述步骤，直到满足停止条件（如达到最大迭代次数或损失函数收敛）。

Adam优化器通过结合动量和自适应学习率，使得参数更新更加稳定和高效。

**Comment by kangfenmao** [comment]
之前的聊天记录还有吗，看看是否是居中显示的，最近没有改这个逻辑

**Comment by fresh-men** [comment]
#154 
之前的提出来的

**Comment by fresh-men** [comment]
> 之前的聊天记录还有吗，看看是否是居中显示的，最近没有改这个逻辑

#154 之前提出来的

**Comment by kangfenmao** [comment]
找到问题原因了

**Comment by kangfenmao** [comment]
<img width="275" alt="image" src="https://github.com/user-attachments/assets/11a89d10-d232-4fa9-b5f8-a25924c8ef1d">

已修复，更新版本

**Comment by fresh-men** [comment]
> <img alt="image" width="275" src="https://private-user-images.githubusercontent.com/8253512/379740179-11a89d10-d232-4fa9-b5f8-a25924c8ef1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjAzMDgsIm5iZiI6MTcyOTgyMDAwOCwicGF0aCI6Ii84MjUzNTEyLzM3OTc0MDE3OS0xMWE4OWQxMC1kMjMyLTRmYTktYjVmOC1hMjU5MjRjOGVmMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMDEzMzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2NiY2EwZjUyODk4Yzg4MDRhNzNjYmMxNjZjY2QxYWZiZTFkNjliZmMzMzc5NGU2ZWJmNjA2MTZiYTBkNDhkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OEaZFnysZKLIsugmiSgywYOaHYJ6lApEf1yIzdFyFLs">
> 已修复，更新版本


**$ $包裹的公式还是不居中：**
![image](https://github.com/user-attachments/assets/d62e9ec8-0cb6-4b79-b7d7-c38ecf34d5e3)

**gpt输出内容如下：**

你提供的已经是关于硬间隔 SVM 的完整推导过程了。为了更清晰地展现一些步骤的细节，我补充一些说明：

**1. 为什么转化为最小化 $\frac{1}{2}||\vec{w}||^2$**:

最大化 $\frac{2}{||\vec{w}||}$ 等价于最小化 $||\vec{w}||$，也等价于最小化 $\frac{1}{2}||\vec{w}||^2$。选择 $\frac{1}{2}||\vec{w}||^2$ 的原因是其求导更加方便，结果更简洁，不影响最终的优化结果。

**2. 拉格朗日对偶性的理解**:

原问题是一个带约束的优化问题，难以直接求解。通过引入拉格朗日乘子，将约束条件融入到拉格朗日函数中，转化为无约束优化问题。对偶问题是原问题的另一种表达形式，其最优解与原问题的最优解在一定条件下相等（强对偶性）。SVM 问题满足强对偶条件。

**3.  求解对偶问题的过程**:

对偶问题的求解通常使用一些专门的优化算法，例如 SMO 算法。SMO 算法通过迭代的方式求解对偶问题中的 $\alpha_i$，最终得到最优解。

**4.  KKT 条件的意义**:

KKT 条件是判断一个点是否为最优解的必要条件。在 SVM 中，KKT 条件的意义在于：

* $\alpha_i^* \ge 0$：这是对偶问题的约束条件。
* $y_i(\vec{w} \cdot \vec{x}_i + b) - 1 \ge 0$：这是原问题的约束条件。
* $\alpha_i^*[y_i(\vec{w} \cdot \vec{x}_i + b) - 1] = 0$：这是互补松弛条件，表明要么 $\alpha_i^* = 0$，要么 $y_i(\vec{w} \cdot \vec{x}_i + b) - 1 = 0$。

**5. 支持向量的作用**:

支持向量是决定最终分类超平面的关键样本点。只有支持向量的 $\alpha_i^* > 0$，其他样本点的 $\alpha_i^* = 0$，这意味着其他样本点对最终的分类超平面没有影响。这也体现了 SVM 的稀疏性。

**6.  $b^*$ 的计算**:

$b^*$ 的计算可以通过任意一个支持向量 $\vec{x}_s$ 计算：

$b^* = y_s - \sum_{i=1}^n \alpha_i^* y_i \vec{x}_i \cdot \vec{x}_s$

为了提高数值稳定性，通常会使用所有支持向量计算 $b^*$ 的平均值。


总而言之，你提供的证明过程是正确的和完整的。我的补充说明希望能帮助你更好地理解 SVM 的推导过程和一些关键概念。

**Comment by kangfenmao** [comment]
这个是行内公式吧

**Comment by fresh-men** [comment]
> 这个是行内公式吧，使用两个美元符号包裹起来的，要在行内显示。$\alpha_i^* \ge 0$

哦哦，我的问题

**Comment by kangfenmao** [comment]
> > 这个是行内公式吧，使用两个美元符号包裹起来的，要在行内显示。$\alpha_i^* \ge 0$
> 
> 哦哦，我的问题

公式这个问题很依赖第三方的库，希望他们能支持的完善一些。有些库就是比较固执，只有符合标准的公式才能正常显示，但是实际上很多公式还在用旧的标准。所以大模型回复的公式很有可能识别不出来。
