### ISSUE TITLE
ollama API怎么获取

### ISSUE THREAD

**Issue by niuniu54w** [kangfenmao/cherry-studio#234]
![微信截图_20241024014434](https://github.com/user-attachments/assets/d310f4a3-e445-46aa-8779-f624f0474fcd)
这个api我该怎么获取

**Comment by kangfenmao** [comment]
不填

**Comment by niuniu54w** [comment]
直接使用就可以么

**Comment by kangfenmao** [comment]
> 直接使用就可以么

是的

**Comment by niuniu54w** [comment]
![Uploading 微信截图_20241024113744.png…]()
出现这种情况怎么办

**Comment by kangfenmao** [comment]
图片看不到

**Comment by niuniu54w** [comment]
![微信截图_20241024113744](https://github.com/user-attachments/assets/7ffb082d-8bb6-4a7d-a27d-05794a6f382b)

**Comment by kangfenmao** [comment]
> ![微信截图_20241024113744](https://private-user-images.githubusercontent.com/118619402/379536331-7ffb082d-8bb6-4a7d-a27d-05794a6f382b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDE1OTMsIm5iZiI6MTcyOTc0MTI5MywicGF0aCI6Ii8xMTg2MTk0MDIvMzc5NTM2MzMxLTdmZmIwODJkLThiYjYtNGE3ZC1hMjdkLTA1Nzk0YTZmMzgyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwMzQxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2I3MmUxODQ2NTk4OTkwZWQ5ZmExOGVkZGQzZWNmODVhMzAzMDA5N2E4MGQ4NTZjZjUzNWZmNjNlNjczZTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XuZ3z0BEZ4viP4I3f13JNt_ztPJXb3KHuQ4xDxWTStE)

模型没有下载

**Comment by niuniu54w** [comment]
好的谢谢
