### ISSUE TITLE
回复提示，Max retries reached. Unable to complete the request.

### ISSUE THREAD

**Issue by wstanfeng** [kangfenmao/cherry-studio#237]
同样的api key，在open-webui与lobechat，用同样的模型都能正常回复， 但用这个软件提示Max retries reached. Unable to complete the request.

**Comment by kangfenmao** [comment]
请求受限制了，看看服务商是不是有频率限制

**Comment by kangfenmao** [comment]
有新的进展吗 @wstanfeng
