### ISSUE TITLE
v0.8.2 添加新的助手-使用默认助手的情况下，创建2个对话聊天的时候会自动复选2个新添加的助手

### ISSUE THREAD

**Issue by 18005575** [kangfenmao/cherry-studio#238]
v0.8.2 添加新的助手-使用默认助手的情况下，创建2个对话聊天的时候，会自动复选2个新添加的助手，无法编辑第二个助手，编辑就是2个一起改了，删除就是2个一起删除了。
使用环境：windows11
图片效果复现：升级v0.8.2版本后，新增2个默认助手对话，这个时候只有一个对话能用，编辑对话名称2个都会自动变更，删除则2个都会删除。
![QQ20241024-122634](https://github.com/user-attachments/assets/757f6adf-90a8-4fea-884f-9e4638ce2cbd)

**Comment by kangfenmao** [comment]
已修复，更新到新版
