### ISSUE TITLE
使用claude模型回复异常

### ISSUE THREAD

**Issue by ZhaoMo14** [kangfenmao/cherry-studio#24]
![image](https://github.com/user-attachments/assets/fa29d963-8f36-42a6-9a16-38e394654465)
使用claude模型时会回复两条，而且回复内容会有undefined
![image](https://github.com/user-attachments/assets/e7b2061f-6690-4858-957e-8315783188cf)
切换页面后内容会消失

**Comment by kangfenmao** [comment]
问题收到，开发 claude 的时候没有申请到 API Key 😂

**Comment by kangfenmao** [comment]
能否借用你的 API 调试一下，如果方便的话加下我的微信： kangfenmao

**Comment by Thinkerzhangqian** [comment]
@ZhaoMo14 麻烦说下代理怎么设置的，我使用的是clash x。非常感谢

**Comment by kangfenmao** [comment]
> @ZhaoMo14 麻烦说下代理怎么设置的，我使用的是clash x。非常感谢

<img width="808" alt="image" src="https://github.com/user-attachments/assets/b2cf4cf0-7ea2-45fb-b24d-5559390557b6">

然后把复制的内容里面的 sock5 开头的地址粘贴到这里

<img width="1347" alt="image" src="https://github.com/user-attachments/assets/f137e03d-8a35-49a4-a5a7-852ee205ba3a">

@Thinkerzhangqian

**Comment by Thinkerzhangqian** [comment]
@kangfenmao 感谢

**Comment by kangfenmao** [comment]
已修复，下个版本发布

**Comment by kangfenmao** [comment]
新版本已发布

https://github.com/kangfenmao/cherry-studio/releases/tag/v0.5.6
