### ISSUE TITLE
添加附件就出错，不添加附件就正常

### ISSUE THREAD

**Issue by brightleo** [kangfenmao/cherry-studio#241]
添加附件就出下面错，不添加附件就正常。哪里能看到啥原因？有日志啥的么
++++++++++++++++++++++++++++
出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥
Error: 500 Internal Server Error
++++++++++++++++++++++++++++

**Comment by kangfenmao** [comment]
> 添加附件就出下面错，不添加附件就正常。哪里能看到啥原因？有日志啥的么 ++++++++++++++++++++++++++++ 出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥 Error: 500 Internal Server Error ++++++++++++++++++++++++++++

咨询模型服务商，这个问题是由于你的模型服务导致的，可能他们不支持文件

**Comment by brightleo** [comment]
qwen2.5:32b这个模型，肯定是支持的。同样的配置，另一个环境就可以。没搞懂差别在哪里

**Comment by kangfenmao** [comment]
> qwen2.5:32b这个模型，肯定是支持的。同样的配置，另一个环境就可以。没搞懂差别在哪里

模型服务商是哪家？

**Comment by brightleo** [comment]
通过webui中转的，选openai和自定义都不行。

**Comment by brightleo** [comment]
应该是webui的设定问题，使用本地ollama是好的。

**Comment by kangfenmao** [comment]
给他们提交 issue 让他们解决一下吧
