### ISSUE TITLE
WebDAV 备份失败 - 请求体大小超出 `maxBodyLength` 限制

### ISSUE THREAD

**Issue by ufvice** [kangfenmao/cherry-studio#243]
环境：Archlinux：Linux 6.11.5-arch1-1 x86_64 GNU/Linux
软件版本：0.8.2-x86_64.AppImage

在使用 WebDAV 备份功能时，我遇到了请求体大小超出 `maxBodyLength` 限制的错误。我用数据备份到本地得到的zip文件是24.6MB大小，我使用的是坚果云 WebDAV 服务。备份无法完成并出现如下错误：

```plaintext
Error invoking remote method 'backup:backupToWebdav': Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
```

可以确定我填写的webdav信息无误，因为我用windows上完全没数据（数据备份到本地得到的zip文件只有几KB大小）的全新cherry-studio可以备份成功

**Comment by kangfenmao** [comment]
感谢反馈❤️

**Comment by kangfenmao** [comment]
试试看好了不 @ufvice

**Comment by ufvice** [comment]
确实是可以了，就是不太优雅，大文件这样备份上去要加载很久，并不方便。现在的样子只能算是可以用。
我有时会直接把PPT作为附件，其中真正被解析的文本占用的空间并不大，而那些没什么用的其他未被解析的内容却占据了很多空间。
我觉得可能增加这样的调整会好一点：
- 只同步文件解析出来的文本（我不知道这解析是在客户端上、还是由api来做的，还望勿怪）
- 或者增加个不同步太大的文件的过滤机制

> 试试看好了不 @ufvice

**Comment by kangfenmao** [comment]
这个我来想一下
