### ISSUE TITLE
support "ctrl+enter" as send shortcuts

### ISSUE THREAD

**Issue by ZzzzRyan** [kangfenmao/cherry-studio#244]
Add a new send shortcut: "ctrl+enter". It is a common option.

![image](https://github.com/user-attachments/assets/5ea5dd99-db9d-44e7-ba0b-58cb369a80eb)

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/2fbdb826-23d3-45bd-8ebf-4467ce9e0b32)

加上了，下个版本发布
