### ISSUE TITLE
add claude-3-5-sonnet-latest   support

### ISSUE THREAD

**Issue by brucel11qwe** [kangfenmao/cherry-studio#247]
ModelClaude3Dot5Sonnet20241022 Model = "claude-3-5-sonnet-20241022"

ModelClaude3Dot5SonnetLatest   Model = "claude-3-5-sonnet-latest"

https://github.com/search?q=repo%3Aliushuangls%2Fgo-anthropic%20claude-3-5&type=code

**Comment by kangfenmao** [comment]
Fixed, update in the next version, you will need to manually add the new model after the update
