### ISSUE TITLE
【问题】 经常出现 ”出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥 Error: Connection error.“

### ISSUE THREAD

**Issue by yuhuihu** [kangfenmao/cherry-studio#248]
经常出现 ”出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥 Error: Connection error.“

一旦出现这种情况， 无论我是本地模型还是远程模型都一样。 只有重启电脑。

<img width="671" alt="截屏2024-10-26 21 05 37" src="https://github.com/user-attachments/assets/7ed7d353-616e-4d89-8e09-557f1e199006">

**Comment by kangfenmao** [comment]
> 经常出现 ”出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥 Error: Connection error.“
> 
> 一旦出现这种情况， 无论我是本地模型还是远程模型都一样。 只有重启电脑。
> 
> <img alt="截屏2024-10-26 21 05 37" width="671" src="https://private-user-images.githubusercontent.com/4496921/380424760-7ed7d353-616e-4d89-8e09-557f1e199006.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTA0NTIsIm5iZiI6MTcyOTk1MDE1MiwicGF0aCI6Ii80NDk2OTIxLzM4MDQyNDc2MC03ZWQ3ZDM1My02MTZlLTRkODktOGUwOS01NTdmMWUxOTkwMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjZUMTM0MjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFmYjA0MWJmMzI5ZWJjNTIxNmEyYjk1M2ZmZGIzNTA1ZTI2MjhmNGYzNTNiZGYxNTM1ZWJkZmNiMTE0YjFiMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ag6nlj9GoFqGPj_PAjLtuatF6j1rHS22wsnyygeCf8Q">

看起来像是你设置了代理导致的连接问题，之前用户没有反馈过这个问题，重点排查一下本地网络

**Comment by kangfenmao** [comment]
问题有解决掉吗 @yuhuihu

**Comment by yuhuihu** [comment]
还真是。 似乎和代理软件有关， 请忽略吧。 不好意思。

**Comment by ryuu222** [comment]
> 还真是。 似乎和代理软件有关， 请忽略吧。 不好意思。

请问最后是如何修改本地代理的呢？我在使用官方gemini的api的时候也出现此问题
