### ISSUE TITLE
gemini模型一直报错连接失败

### ISSUE THREAD

**Issue by vencentml** [kangfenmao/cherry-studio#249]
gemini模型一直报错连接失败

**Comment by kangfenmao** [comment]
> gemini模型一直报错连接失败

截图看看

**Comment by kangfenmao** [comment]
@vencentml

**Comment by vencentml** [comment]
![image](https://github.com/user-attachments/assets/07138a5f-6e49-4bc9-9db5-c2e7553bd0c3)
api_key是从https://aistudio.google.com/app/apikey这里获取的，这个api_key用在dify上使用是正常的

**Comment by kangfenmao** [comment]
我们这边用是没问题的，一样的配置，检查一下 googleapis.com 这个域名是否翻墙，另外如果使用代理，需要把代理选择国外地区 @vencentml

**Comment by vencentml** [comment]
okay

**Comment by kangfenmao** [comment]
> okay

后来有尝试配置代理看看吗

**Comment by vencentml** [comment]
本地一直跑着全局模式的letsvpn(指纹浏览器使用是正常的)

**Comment by kangfenmao** [comment]
全局模式不代表能够代理到 Cherry Studio, 你需要开启 TNU 


![image](https://github.com/user-attachments/assets/eff18a44-7f63-41a0-ab1b-f45b0b8b8055)

**Comment by vencentml** [comment]
好的，多谢
