### ISSUE TITLE
创建好的智能体，可以隐藏或者折叠提示词吗？

### ISSUE THREAD

**Issue by Jerryplus** [kangfenmao/cherry-studio#25]
1、提示词是否可以隐藏或者折叠。
2、智能体头像可否使用url或者本地上传。
3、有没有增加知识库的计划。
谢谢

**Comment by kangfenmao** [comment]
1. 下个版本支持
2. 后续版本支持
3. 知识库是未来的重心功能，正在开发中

@Jerryplus

**Comment by kangfenmao** [comment]
新版本已经发布，优化了 prompt 显示 @Jerryplus 

设置 -> 关于 -> 检查更新

智能体头像问题，暂时先不调整，等知识库功能昨晚再做优化

https://github.com/kangfenmao/cherry-studio/releases/tag/v0.5.7
