### ISSUE TITLE
how to disabled keyboard shortcut

### ISSUE THREAD

**Issue by Viskeyy** [kangfenmao/cherry-studio#251]
Can't disable shortcuts on macOS, always creates a new topic when using `ctrl` + `H` when typing in input

**Comment by kangfenmao** [comment]
> shortcuts

It seems that only Command/Ctrl + N is being listened to, are you sure you're using H?

**Comment by Viskeyy** [comment]
> > shortcuts
>
> It seems that only Command/Ctrl + N is being listened to, are you sure you're using H?

it seems `ctrl` + `N`, but after the update I've found the shortcut key setup screen.
thanks
