### ISSUE TITLE
Mermaid 代码块不能正常渲染显示，切换 Topic 回来才正常显示

### ISSUE THREAD

**Issue by monsterhxw** [kangfenmao/cherry-studio#252]
Mermaid 代码块不能正常渲染显示，切换 Topic 回来才正常显示
具体看视频

https://github.com/user-attachments/assets/92ce9672-64ea-4afa-aea8-372f1d622448

版本: [v0.8.5](https://github.com/kangfenmao/cherry-studio/releases/tag/v0.8.5)

**Comment by kangfenmao** [comment]
已修复，更新到新版本
