### ISSUE TITLE
表格宏多个图标。

### ISSUE THREAD

**Issue by Sucorde** [kangfenmao/cherry-studio#253]
![image](https://github.com/user-attachments/assets/0103699a-7434-46f9-ba43-eca68beb9da7)

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/52f93b5c-71cd-4b97-93f5-f2acad3673d2)

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/e3178e06-5ded-4a16-9271-e77bed46c984)

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/2e38452c-3250-4473-bb0f-641e7813f4a4)

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/d491b940-d26a-4c90-97b6-cfabc1c3839c)

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/676ff569-a200-4d3d-83a4-6d12ae14af30)

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/664ab430-dd3b-4139-82b1-31862c1ac737)

**Comment by 1355873789** [comment]
下个版本解决

**Comment by kangfenmao** [comment]
已经修复
