### ISSUE TITLE
添加自定义的模型的分组总是成为大写字母

### ISSUE THREAD

**Issue by fl0w1nd** [kangfenmao/cherry-studio#257]
![CleanShot 2024-10-30 at 15 12 22@2x](https://github.com/user-attachments/assets/c368568b-2601-4649-8855-a93869860065)

如图所示，当我尝试添加一个自定义模型时，我设定了分组为'test'，这个test是小写字母，但是当我创建完成后，列表里显示的是大写。

![CleanShot 2024-10-30 at 15 14 18@2x](https://github.com/user-attachments/assets/3f0059e2-8d8f-447f-8db1-c938045439ea)

这就使得当我想要自定义添加一个模型到已有的模型分组中时，由于默认的模型分组名称中有小写英文字母，而我无论如何都不能添加进去，因为我自定义的模型的分组会变成大写。

**Comment by kangfenmao** [comment]
OK，后面改一下

**Comment by kangfenmao** [comment]
已经修复，这个先关闭了，等周末发布版本更新
