### ISSUE TITLE
j建议增加minimax api支持

### ISSUE THREAD

**Issue by Jontyshaw** [kangfenmao/cherry-studio#26]
minimax文档https://platform.minimaxi.com/document/Announcement?key=66701c5e1d57f38758d58180

**Comment by kangfenmao** [comment]
感谢建议，下个版本上

**Comment by kangfenmao** [comment]
已经接入

**Comment by Jontyshaw** [comment]
> 已经接入

效率好高，感谢

**Comment by kangfenmao** [comment]
> > 已经接入
> 
> 
> 
> 效率好高，感谢

等晚上版本发布之后就能用了
