### ISSUE TITLE
无法关闭快捷方式

### ISSUE THREAD

**Issue by ouening** [kangfenmao/cherry-studio#260]
快捷方式无法关闭，Ctrl+=的快捷键和Word的下标快捷方式冲突了，但是关闭不了
![image](https://github.com/user-attachments/assets/8761955a-ffd3-4d1c-8972-4b2c0791050f)

**Comment by kangfenmao** [comment]
> 快捷方式无法关闭，Ctrl+=的快捷键和Word的下标快捷方式冲突了，但是关闭不了 ![image](https://private-user-images.githubusercontent.com/15122811/381882643-8761955a-ffd3-4d1c-8972-4b2c0791050f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjUyOTMsIm5iZiI6MTczMDM2NDk5MywicGF0aCI6Ii8xNTEyMjgxMS8zODE4ODI2NDMtODc2MTk1NWEtZmZkMy00ZDFjLTg5NzItNGIyYzA3OTEwNTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA4NTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMzMxYjgzMGU2ODFhZGE1ZjM0Mjk4NDQyNDY1MmIyMDdmNGJjZDFlYzYzZmUwZmUzMTU2OGI3NDNhZTRhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H0I0WisHJIoDtmQItuAazxRdaSV7UhXbRrGJwsl4q5I)

更新到最新版本，已经解决了这个问题

**Comment by ouening** [comment]
最新版0.8.7还未解决此问题

**Comment by kangfenmao** [comment]
全局快捷键增加了开关的功能
