### ISSUE TITLE
新的提示词界面不美观，意义不明。建议改回旧版

### ISSUE THREAD

**Issue by DENGJIANGDI** [kangfenmao/cherry-studio#262]
旧版提示词界面信息丰富，美观。旧版已经非常优秀，是完美的状态。
![image](https://github.com/user-attachments/assets/6a4f8104-e830-47c0-a58f-833e60312de4)

新的提示词界面不美观，意义不明。相比旧版没有提升。
![image](https://github.com/user-attachments/assets/bb30df9f-e1c9-4e71-8e87-42b937e7f637)

**Comment by fresh-men** [comment]
赞同，新的太大，不好筛选

**Comment by 1355873789** [comment]
提示词界面和内容后面还会调整，先收集意见

**Comment by SHLE1** [comment]
赞同
