### ISSUE TITLE
从webdav恢复报错Error: FILE_ENDED

### ISSUE THREAD

**Issue by zeyueguo** [kangfenmao/cherry-studio#264]
window 11 系统，数据设置/webdav

【备份到webdav】 提示成功，在webdav看到有文件生成，cherry-studio.backup.zip 大小为0KB
点击【从webdav恢复】则报错
···
message.restore.failed
Error invoking remote method 'backup:restoreFromWebdav': Error: FILE_ENDED
···

**Comment by kangfenmao** [comment]
> window 11 系统，数据设置/webdav
> 
> 【备份到webdav】 提示成功，在webdav看到有文件生成，cherry-studio.backup.zip 大小为0KB 点击【从webdav恢复】则报错 ··· message.restore.failed Error invoking remote method 'backup:restoreFromWebdav': Error: FILE_ENDED ···

WebDAV 服务用的是哪一家

**Comment by zeyueguo** [comment]
自建的nextcloud里面有webdav服务

**Comment by kangfenmao** [comment]
> 自建的nextcloud里面有webdav服务

试试其他 webdav 服务商能否正常备份，这个可以帮助我排查问题

**Comment by kangfenmao** [comment]
有尝试一下第三方的 webdav 服务吗 @zeyueguo

**Comment by zeyueguo** [comment]
> 有尝试一下第三方的 webdav 服务吗 @zeyueguo 另外看一下手动备份后文件大小

1. 手动备份文件大小为12kb，再另外一台设备恢复正常
2. 坚果云的webdav备份和恢复成功
