### ISSUE TITLE
找了几个不影响使用的小小bug

### ISSUE THREAD

**Issue by Win-E** [kangfenmao/cherry-studio#266]
## 消息框随着图片比例变化  而且暗黑模式下颜色好别扭
- ![1730495118724](https://github.com/user-attachments/assets/73d30508-28a3-4520-ba73-fe29c90357fb)
## Ctrl + - 缩放时 缩到最小 再缩的话会报错
- ![1730495151476](https://github.com/user-attachments/assets/36adbec2-1114-4925-a716-103df1983ab0)
## 当选中的默认模型在模型服务中禁用后会出现一个json在这里
- ![1730495306019](https://github.com/user-attachments/assets/0a9a1c1f-173a-496a-a067-cf73d905ce49)

**Comment by kangfenmao** [comment]
最后一个支持拖拽排序，把需要的拖到前面去

**Comment by kangfenmao** [comment]
下个版本会有一个对话样式切换，可以选择气泡或者简洁模式

**Comment by kangfenmao** [comment]
这几个小问题都修复掉了，下个版本

**Comment by Win-E** [comment]
牛呀, 生产力爆棚
