### ISSUE TITLE
客户端关闭按钮丢失

### ISSUE THREAD

**Issue by SystemDev01** [kangfenmao/cherry-studio#267]
![PixPin_2024-11-02_16-26-11](https://github.com/user-attachments/assets/62ed39a1-5001-4eab-b102-19dcf3cb38f2)
版本 0.88
系统版本 win11 23H2
前几个版本使用还是好好的，更新到最新版大概几个小时 右上角的突然关闭、缩小按钮消失了，现在重新安装也不可以

**Comment by kangfenmao** [comment]
我去修一下

**Comment by kangfenmao** [comment]
不知道是否解决

**Comment by SystemDev01** [comment]
> 不知道是否解决

从 0.88 更新到 0.89 后问题依然存在，右上角的关闭 缩小 全屏按钮 依然是不见的
我把 0.88 版本完全卸载，删除了 cherry studio C盘 AppData下所有相关的文件 重新安装后正常了
