### ISSUE TITLE
异常地重复发出消息

### ISSUE THREAD

**Issue by ufvice** [kangfenmao/cherry-studio#270]
这个软件会自动超时重发吗？
我发了一个很长的提问，转了很久出来了。但我看后台记录，居然发了3次一模一样的问题，破产了。
![image](https://github.com/user-attachments/assets/47db2e7d-6b0b-4d51-8743-36242371f757)

软件版本：0.8.5-x86_64.AppImage

**Comment by kangfenmao** [comment]
使用的是 OpenAI SDK 默认逻辑，重试 2 次，建议合理使用这个。

如果没有重试逻辑会导致因为网络波动导致的无法回复频繁出现。
