### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by hankychou** [kangfenmao/cherry-studio#271]
可以在小程序添加DuckDuckGo AI Chat吗？可以免费且免登录使用 GPT-4o mini、Claude 3 Haiku 、Llama 3.1 70B 和 Mixtral 8x7B这四个模型。
![屏幕截图 2024-11-03 125413](https://github.com/user-attachments/assets/73dd55a6-f1fe-4971-8172-6957ab501f8b)

**Comment by kangfenmao** [comment]
下个版本加上

**Comment by hankychou** [comment]
感谢回复！网址是https://duck.ai
