### ISSUE TITLE
请问新增的“图片”功能的模型提供商在哪里设置

### ISSUE THREAD

**Issue by vimbackground** [kangfenmao/cherry-studio#273]
在模型服务设置页面里找不到的相关的模型提供商。

**Comment by vimbackground** [comment]
> 模型就是硅基流动的，设置它就好，不过确实没做好引导

设置好了，测试通过，谢谢提醒。

之前也在模型设置页，在硅基流动的那里刷新模型管理页很久，就是没有出现做图模型，还以为弄错了。

**Comment by WeiFengJL** [comment]
模型就是硅基流动的，设置它就好，不过确实没做好引导

**Comment by kangfenmao** [comment]
引导功能模块计划是年底做的，目前没有任何引导功能开发出来

**Comment by kangfenmao** [comment]
先关闭了，后面我做一下引导就好了
