### ISSUE TITLE
mistral.ai和cloudflare的ai的api服务也加一下吧，方便普通用户设置

### ISSUE THREAD

**Issue by vimbackground** [kangfenmao/cherry-studio#276]
虽然mistral家的服务，我已经在模型服务页里，自己直接添加成功了。

但是普通用户估计也不一定会上手，建议增加一下，尤其mistral是可以免费使用api的。

![Uploading 微信截图_20241103171327.png…]()

**Comment by vimbackground** [comment]
![微信截图_20241103171327](https://github.com/user-attachments/assets/ed7e7970-f9f7-4812-b130-77442f928df0)

**Comment by kangfenmao** [comment]
OK

**Comment by kangfenmao** [comment]
cloudflare 建议自行添加，需求多了我再集成

**Comment by kangfenmao** [comment]
mistral 已经集成
