### ISSUE TITLE
重启后始终显示重启应用以应用更改，点击手动重启后无限循环

### ISSUE THREAD

**Issue by hitcced89** [kangfenmao/cherry-studio#277]
卸载后重新安装，在运行的时候无法进入程序。显示用户数据目录将在重启后更新，请重启应用以应用更改。点击手动重启后始终卡在这一步循环。
![屏幕截图 2024-11-03 181944](https://github.com/user-attachments/assets/c9c736fa-44c4-40b7-8138-63acc62b6765)

**Comment by kangfenmao** [comment]
> 卸载后重新安装，在运行的时候无法进入程序。显示用户数据目录将在重启后更新，请重启应用以应用更改。点击手动重启后始终卡在这一步循环。 ![屏幕截图 2024-11-03 181944](https://private-user-images.githubusercontent.com/77442761/382563155-c9c736fa-44c4-40b7-8138-63acc62b6765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzQwODMsIm5iZiI6MTczMDYzMzc4MywicGF0aCI6Ii83NzQ0Mjc2MS8zODI1NjMxNTUtYzljNzM2ZmEtNDRjNC00MGI3LTgxMzgtNjNhY2M2MmI2NzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDExMzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmN2M3MWQ2ZmQ3NmYzZjU5YTY2MjZlMWM4NjgyOWZlOWU4N2ZhMjU0YjkzZmMxMWY2N2Y5YTNjNTRjOGU5NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tlgnOrB779NbE_g1Cl7tI4E20E0pBm3MGuBjC288aUo)

找到这个目录 C:\Users\用户名\AppData\Roaming\CherryStudio

如果目录名是 cherry-studio 手动修改为 CherryStudio

**Comment by kangfenmao** [comment]
@hitcced89 有效果吗
