### ISSUE TITLE
添加的助手提示词，没有起作用

### ISSUE THREAD

**Issue by crybest** [kangfenmao/cherry-studio#278]

**Comment by crybest** [comment]
![image](https://github.com/user-attachments/assets/aa2b59e0-7c68-410c-abe4-1d1595921da1)
![image](https://github.com/user-attachments/assets/4cf38425-07e0-4813-8b5d-d3c331d5dcbd)

**Comment by kangfenmao** [comment]
这个是会话总结的请求，不是你提问的请求。你可以看看那个提问的请求内容

**Comment by crybest** [comment]
> 这个是会话总结的请求，不是你提问的请求。你可以看看那个提问的请求内容

你说得对
