### ISSUE TITLE
【新功能】希望增加 Mistral AI 的支持

### ISSUE THREAD

**Issue by QwertyJack** [kangfenmao/cherry-studio#289]
Mistral AI 的 [La Plateforme](https://console.mistral.ai/) 提供了非常丰厚的免费额度，其中的 Mistral 系列在开源模型中处于第一梯队。
虽然 Mistral AI 提供了 OpenAI 兼容接口，但是 Mistral 原生接口对 Mistral 模型更加友好。

官方文档：https://docs.mistral.ai/

**Comment by kangfenmao** [comment]
开发完了，下个版本上

**Comment by kangfenmao** [comment]
先关掉了，等周末更新
