### ISSUE TITLE
[bug] github models和groq不支持图片， 模型是支持图像识别的

### ISSUE THREAD

**Issue by lgf5090** [kangfenmao/cherry-studio#291]
github models和groq不支持图片， 模型是支持图像识别的
![image](https://github.com/user-attachments/assets/a7bbff3a-d5a2-4ef6-b5e1-ea41a52bd934)
![image](https://github.com/user-attachments/assets/aac3eca7-2e14-4ab0-b428-2135912899fb)

**Comment by kangfenmao** [comment]
Github 不支持，不知道为什么

**Comment by lgf5090** [comment]
啊？ 我自己写的代码都可以啊？ 按照官网给的代码就可以， chatbox软件也是支持图片没有问题的

**Comment by kangfenmao** [comment]
> 啊？ 我自己写的代码都可以啊？ 按照官网给的代码就可以， chatbox软件也是支持图片没有问题的

可以贴一下请求示例代码吗，或者帮我看看哪里出了问题

**Comment by kevan** [comment]
同样使用grok-beta，不支持上传图片，请优化一下，谢谢

**Comment by kangfenmao** [comment]
https://github.com/lobehub/lobe-chat/issues/4013

**Comment by kangfenmao** [comment]
找到原因了，OpenAI SDK 请求头附加了设备信息，我把这个给注释掉了，这样 OpenAI 搜集不到设备信息了

**Comment by kangfenmao** [comment]
先关闭了，等下个版本更新就好了。Github Models 和 Groq 都可以了

**Comment by kevan** [comment]
大佬，为什么上周更新了2次版本，都没有开放grok的上传图片格式呢？

**Comment by kangfenmao** [comment]
> 大佬，为什么上周更新了2次版本，都没有开放grok的上传图片格式呢？

忘记了这个，我上次只改了上面两个服务商，忘记加上 Grok Beta 模型了

**Comment by kevan** [comment]
奥力给！！！
