### ISSUE TITLE
[Feature] - Add the ability to display the application in tray

### ISSUE THREAD

**Issue by injurka** [kangfenmao/cherry-studio#297]
It would be great if instead of closing the application it could be hidden in tray. This would make it easier to work on tiling systems, and sometimes you just want the application to always be at hand, but you dont want to open it as such every time)

> This is approximately what I mean
![image](https://github.com/user-attachments/assets/b91cd6ee-db17-48e5-a08b-d095f2a9575c)

**Comment by kangfenmao** [comment]
OK

**Comment by kangfenmao** [comment]
@1355873789 我们需要设计一个这样的图标，一种是白色，一种是黑色 

<img width="227" alt="image" src="https://github.com/user-attachments/assets/1247ed17-b38a-4ace-a3e2-5e9cb397c31b">

**Comment by kangfenmao** [comment]
Working in progress

**Comment by kangfenmao** [comment]
Update to the new version
