### ISSUE TITLE
【使用反馈】现在的“所有文件”功能似乎没有用？

### ISSUE THREAD

**Issue by forrany** [kangfenmao/cherry-studio#299]
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/5c9e7728-9f2f-46ee-9eed-0852aa47bf1a">

如图，每次上传的文件或图片似乎都被缓存，并在这里可以看到，但是除了 “打开” 之外，在聊天中也无法引用文件，如果需要使用某个还是要重新上传，然后生成一个新的 temp文件？

然后占据空间越来越大，但这个有没有任何作用看起来？

**Comment by kangfenmao** [comment]
后面这个模块会变成知识库，可以添加之前的文件到知识库里面

**Comment by kangfenmao** [comment]
这个问题先关闭了，后面页面还有改版，这个界面可能也会不存在了
