### ISSUE TITLE
增加 xAI 的 api 支持

### ISSUE THREAD

**Issue by hypooo** [kangfenmao/cherry-studio#301]
目前 xAI 在公测，有免费的额度可以用

文档地址：https://docs.x.ai/api

另外希望点击右上角 x 的时候，可以给个最小化到托盘或者直接退出的选项。

**Comment by kangfenmao** [comment]
加了，最近两个发布新版本就有了，周末更新一下就好了

**Comment by kangfenmao** [comment]
右上角 x 的时候，可以给个最小化到托盘或者直接退出的选项。这个在其他 issue 里记录了。

我先关闭这个了，等周末版本更新就好了

**Comment by hypooo** [comment]
👍👍👍
