### ISSUE TITLE
气泡默认界面显示异常

### ISSUE THREAD

**Issue by Jontyshaw** [kangfenmao/cherry-studio#308]
<img width="959" alt="1" src="https://github.com/user-attachments/assets/3e5b3975-4972-4e03-a6d0-42d60e487fcb">

如图所示，0.8.10版本的聊天界面在气泡模式下会出现这个问题，许多文字只有用鼠标选中高亮才能看到

**Comment by kangfenmao** [comment]
确实是有问题，建议先用简洁模式

**Comment by kangfenmao** [comment]
已修复
