### ISSUE TITLE
mermaid图渲染有问题

### ISSUE THREAD

**Issue by huminglong** [kangfenmao/cherry-studio#310]
mermaid显示有问题，生成的mermaid图代码，必须得手动切换一个话题再切换回来，mermaid图渲染才会成功，否则就只会显示代码，不显示渲染后的图

**Comment by kangfenmao** [comment]
Is it related to the mermaid? How to reproduce it

**Comment by kangfenmao** [comment]
The app seems to start slower after using shiki. I don't know if it's my illusion

**Comment by kangfenmao** [comment]
已修复
