### ISSUE TITLE
bug: 对话分叉后意外恢复至编辑前的原始内容状态

### ISSUE THREAD

**Issue by ufvice** [kangfenmao/cherry-studio#313]
软件版本：0.8.10-x86_64.AppImage
问题现象：
在话题分叉前对某个话题的对话进行内容编辑，后续执行分叉操作时，分叉后的两个话题会自动回退到编辑前的原始内容状态，导致用户的编辑内容丢失。
重现步骤：
1. 打开一个已经聊了几回合的话题
2. 编辑话题部分对话内容
3. 在该话题任一对话处执行话题分叉操作
4. 发现分叉后的两个话题内容均恢复到编辑前的状态（分叉对话之前和之后的对话内容都会回退到编辑前的状态）
预期行为：
分叉后，两个话题应保留最近编辑的内容状态。
实际行为：
分叉后，两个话题自动还原到编辑前的初始内容。

**Comment by kangfenmao** [comment]
这个问题是个 bug 我修了

**Comment by kangfenmao** [comment]
已上线
