### ISSUE TITLE
代理增加开关选项

### ISSUE THREAD

**Issue by kakapas** [kangfenmao/cherry-studio#314]
用了下还不错，提3个建议
1、最左边的那列图标，能否鼠标放上面有个提示，现在不点进去，都不知道做什么的
2、设置，代理能否加个开关。我填了代理，代理软件一关，国内的智谱等官网都上不去了
3、希望能再做个安卓手机客户端，不过我推论就算要做，是不是也先做水果的？（笑）

**Comment by kangfenmao** [comment]
1. 这个我已经加上了
2. 可以
3. 一起做

**Comment by kangfenmao** [comment]
下个版本加上代理设置选项

**Comment by kangfenmao** [comment]
已上线
