### ISSUE TITLE
请求智能体增加变量和同步功能

### ISSUE THREAD

**Issue by igeekbb** [kangfenmao/cherry-studio#32]
![CleanShot 2024-08-21 at 14 02 23@2x](https://github.com/user-attachments/assets/ec096935-f4a9-466b-9c9c-affb91ad9717)
同步功能也可以使用导出平替，方便多台电脑使用。

**Comment by kangfenmao** [comment]
计划中，导出功能应该会更早做出来。变量功能，我去研究一下

**Comment by kangfenmao** [comment]
备份和恢复功能开发好了，下个版本上线

<img width="1165" alt="image" src="https://github.com/user-attachments/assets/bcb31c1d-fac9-434c-b7e5-6a4922475c8e">

**Comment by kangfenmao** [comment]
https://github.com/kangfenmao/cherry-studio/releases

新增备份和恢复功能
