### ISSUE TITLE
最小化和关闭都会导致关闭到托盘

### ISSUE THREAD

**Issue by czz404** [kangfenmao/cherry-studio#321]
v0.8.11点击最小化和关闭都会导致关闭到托盘

**Comment by kangfenmao** [comment]
> v0.8.11点击最小化和关闭都会导致关闭到托盘
> 
> 
> 
> 

什么系统

**Comment by czz404** [comment]
> > v0.8.11 点击最小化和关闭都会导致关闭到托盘
> 
> 什么系统

win11 23H2 22631.4391
