### ISSUE TITLE
v0.8.11点击最小化和关闭都会关闭到托盘

### ISSUE THREAD

**Issue by hw-tutu** [kangfenmao/cherry-studio#323]
win11系统
v0.8.11点击最小化和关闭都会导致关闭到托盘
并且如果最小化到托盘后 在重新打开软件 会卡死 无法点击 切换页面 选中文字

**Comment by Sorades** [comment]
win11 23H2，遇到了同样的问题，最小化到托盘后必须通过托盘打开才能正常使用，通过exe打开界面会卡死

**Comment by WEIFENG2333** [comment]
同样遇到问题

**Comment by kangfenmao** [comment]
正在发新版

**Comment by kangfenmao** [comment]
去更新一下
