### ISSUE TITLE
全局快捷键唤醒

### ISSUE THREAD

**Issue by zhang258027** [kangfenmao/cherry-studio#324]
设备信息：
系统版本：Windows 11 24H2 (版本 10.0.26100)
软件版本：Cherry Studio v0.8.12

问题描述(修正)：
在我的 Win11 自定义主题下（默认 Windows 模式：深色；默认应用模式：浅色），会显示为黑色图标。
![image](https://github.com/user-attachments/assets/6c5507b2-30f7-4c68-b41d-5057bfbb5310)

建议：
1.考虑重新调整一下，或直接更换为彩色图标。
2.既然已经有托盘图标，是否可以增加一个全局快捷键来呼出窗口？

**Comment by 1355873789** [comment]
1. 下个版本会换彩色logo
2. 全局快捷键后续会做

**Comment by kangfenmao** [comment]
全局快捷键唤醒功能已经加上了，更新到新版本就可以了
