### ISSUE TITLE
添加 api 接口时检测的不正确

### ISSUE THREAD

**Issue by SystemDev01** [kangfenmao/cherry-studio#326]
![PixPin_2024-11-11_15-14-50](https://github.com/user-attachments/assets/59b44523-c027-443e-87d0-7d639fb12bb4)
如上 点击检测一直都是连接失败

![PixPin_2024-11-11_15-21-05](https://github.com/user-attachments/assets/de756f0b-72ad-4ec3-ade5-9051999f7e05)
实际上已经检测到了模型，并且对话也是没问题的

**Comment by kangfenmao** [comment]
这信息都遮挡完了，看不出来问题

**Comment by kangfenmao** [comment]
需要提供更多的信息：

1. API 地址
2. 第一个模型信息

@SystemDev01

**Comment by SystemDev01** [comment]
> 需要提供更多的信息：
> 
> 1. API 地址
> 2. 第一个模型信息
> 
> @SystemDev01

![PixPin_2024-11-12_13-39-47](https://github.com/user-attachments/assets/a4c909a7-bcef-4b47-bc97-e2137546a22b)

**Comment by kangfenmao** [comment]
我知道了，你要先添加模型然后再检测

**Comment by SystemDev01** [comment]
> 我知道了，你要先添加模型然后再检测

是否需要优化下，既然可以获取到模型列表，代表网络连接、密钥都是没问题的

**Comment by kangfenmao** [comment]
> > 我知道了，你要先添加模型然后再检测
> 
> 是否需要优化下，既然可以获取到模型列表，代表网络连接、密钥都是没问题的

已经优化了，没有添加模型的时候会给提示
