### ISSUE TITLE
助手<>话题 间的自动切换

### ISSUE THREAD

**Issue by LeoStruggle666** [kangfenmao/cherry-studio#337]
**问题描述：**
在我的使用场景中，需要频繁的切换使用不同的助手/agent + 新建话题。

当前 选中助手->Command+N新建助手后，左侧的菜单栏就会从“助手”自动切到“话题”，表示我新建了个话题。但下一次我要切换其他助手的时候，还需要 先在菜单栏点回“助手”->再选中要启用新话题的助手->再周而复始，交互上虽然只多了一步，但频率高了会还是觉得有些繁琐。

而我记得在早前的版本中，选中助手->Command+N新建助手后，左侧的菜单栏仍保持为“助手”

**期望：**
是否能加多一个配置项，让我们选择 Command+N新建助手 后的菜单栏是保持不变or切换为“话题”？

**Comment by kangfenmao** [comment]
是有这样的一个问题，我可以增加一个选项，或者去掉自动切换逻辑。

你可以暂时把话题放在右侧，这样更加高效一点

**Comment by LeoStruggle666** [comment]
好的，谢谢建议！

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/4905a7ab-af3a-462b-a536-1b5640cf6f98)
通过这个开关可以设置了
