### ISSUE TITLE
清除上下文功能

### ISSUE THREAD

**Issue by Plus-xu** [kangfenmao/cherry-studio#338]
经常使用清除上下文功能，希望可以恢复
比如我阅读某一篇文章，我可以将一个视频的不同评论的翻译通过清除上下文保存在一个话题内
或者我想询问多个模型同一个问题，我可以通过清除上下文将不同模型的回答保存在一个话题内
通过清除上下文，可以精简话题数量，便于查找和总结

**Comment by kangfenmao** [comment]
这个功能一直有呀

**Comment by kangfenmao** [comment]
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/85460aa1-04aa-46a3-910a-c9f9cadc4993">

**Comment by Plus-xu** [comment]
> <img alt="image" width="1037" src="https://private-user-images.githubusercontent.com/8253512/385237860-85460aa1-04aa-46a3-910a-c9f9cadc4993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDY0NzgsIm5iZiI6MTczMTQwNjE3OCwicGF0aCI6Ii84MjUzNTEyLzM4NTIzNzg2MC04NTQ2MGFhMS0wNGFhLTQ2YTMtOTEwYS1jOWY5Y2FkYzQ5OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMTAwOTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVkNDM0MGVhYjQ0ZGVjNmVmYmQxMTc3ZTBmNzg1NTliYzc1MWM3NGExOGUzYjliZDY3ODI0Y2Y3NDJhYmU1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.erjNoGKNBVAIYdBA00YeOPyyCL8dXd9fhSWCEHfdiMI">

哦...晕，我最近把显示token关闭了，然后我以为更新后这个功能被取消了

**Comment by kangfenmao** [comment]
> > <img alt="image" width="1037" src="https://private-user-images.githubusercontent.com/8253512/385237860-85460aa1-04aa-46a3-910a-c9f9cadc4993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDY0NzgsIm5iZiI6MTczMTQwNjE3OCwicGF0aCI6Ii84MjUzNTEyLzM4NTIzNzg2MC04NTQ2MGFhMS0wNGFhLTQ2YTMtOTEwYS1jOWY5Y2FkYzQ5OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMTAwOTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVkNDM0MGVhYjQ0ZGVjNmVmYmQxMTc3ZTBmNzg1NTliYzc1MWM3NGExOGUzYjliZDY3ODI0Y2Y3NDJhYmU1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.erjNoGKNBVAIYdBA00YeOPyyCL8dXd9fhSWCEHfdiMI">
> 
> 哦...晕，我最近把显示token关闭了，然后我以为更新后这个功能被取消了

我是不是应该把这两个按钮的显示分开

**Comment by Plus-xu** [comment]
> > > <img alt="image" width="1037" src="https://private-user-images.githubusercontent.com/8253512/385237860-85460aa1-04aa-46a3-910a-c9f9cadc4993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDY0NzgsIm5iZiI6MTczMTQwNjE3OCwicGF0aCI6Ii84MjUzNTEyLzM4NTIzNzg2MC04NTQ2MGFhMS0wNGFhLTQ2YTMtOTEwYS1jOWY5Y2FkYzQ5OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMTAwOTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVkNDM0MGVhYjQ0ZGVjNmVmYmQxMTc3ZTBmNzg1NTliYzc1MWM3NGExOGUzYjliZDY3ODI0Y2Y3NDJhYmU1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.erjNoGKNBVAIYdBA00YeOPyyCL8dXd9fhSWCEHfdiMI">
> > 
> > 
> > 哦...晕，我最近把显示token关闭了，然后我以为更新后这个功能被取消了
> 
> 我是不是应该把这两个按钮的显示分开

分开好一点
