### ISSUE TITLE
代码库可以不自动换行开关吗

### ISSUE THREAD

**Issue by CHEN1016** [kangfenmao/cherry-studio#34]
目前的代码块会自动换行，希望可以增加不自动换行的功能，可以自己左右滑动来查看

**Comment by kangfenmao** [comment]
这个暂时先不弄了，需要的话复制出来到 IDE 里面看吧，

**Comment by kangfenmao** [comment]
> 目前的代码块会自动换行，希望可以增加不自动换行的功能，可以自己左右滑动来查看

默认关闭了换行，下个版本更新，你的这个问题我记着呢
