### ISSUE TITLE
新版没有模型温度调节设置了

### ISSUE THREAD

**Issue by Plus-xu** [kangfenmao/cherry-studio#340]
模型温度超级常用，我针对每个智能体的模型温度都不同，比如翻译，日常对话，写作，数学计算等都设了不同的模型温度，并且每次调节模型温度都能生成不同的答案。现在没办法针对每个智能体设置不同模型温度了，非常不方便，希望能加回右侧的设置面板中。

**Comment by kangfenmao** [comment]
点击顶部助手名字，或者助手右键菜单进行设置

**Comment by kangfenmao** [comment]
> 模型温度超级常用，我针对每个智能体的模型温度都不同，比如翻译，日常对话，写作，数学计算等都设了不同的模型温度，并且每次调节模型温度都能生成不同的答案。现在没办法针对每个智能体设置不同模型温度了，非常不方便，希望能加回右侧的设置面板中。

找到设置的地方了吗

**Comment by hdestiny** [comment]
模型温度和上下文数是高频设置项，使用过程中经常要调节，希望能将这几个设置项调回边栏设置面板中。

**Comment by kangfenmao** [comment]
> 模型温度和上下文数是高频设置项，使用过程中经常要调节，希望能将这几个设置项调回边栏设置面板中。

好的，感谢给出反馈建议

**Comment by ZzzzRyan** [comment]
> 模型温度和上下文数是高频设置项，使用过程中经常要调节

为什么会需要高频调节呢？有什么使用场景吗？

个人还是比较认同目前把温度收归到助手的设置界面里的，原因如下：

1. 这样界面布局逻辑上看起来更加统一，界面也更简洁——全局设置和全局设置放在一起，助手设置和助手设置放在一起；
2. 而且一般温度和上下文调整好之后，基本上都可以固定为一个新的助手复用，无需在同一个助手下反复调节；
3. 上下文数量一般是一个助手对话的上限，反复在同一个助手下调整可以使用“清除上下文”、“清空消息”、“创建一个新的话题提问”等来替代操作，更符合交互体验。、

以上为个人想法，供参考。

**Comment by hdestiny** [comment]
一、
不同的模型，对于同一个场景，其温度设置偏好是不同的，值域也是不同的，比如有的模型是(0,1]，有的模型是(0,2]
拿翻译来说，有的模型推荐设置为1.3，有的模型则需要设置为0.7。对于同一个智能体，我是有需求经常切换不同的模型看不同的返回结果的。参考：
https://api-docs.deepseek.com/zh-cn/quick_start/parameter_settings
https://platform.lingyiwanwu.com/docs/api-reference
https://help.aliyun.com/zh/model-studio/user-guide/text-generation#ad7b336bec5fw
https://www.volcengine.com/docs/82379/1357049

二、
有的场景我需要多轮对话，但时不时我就需要模型不参考上下文，然而我还想要保持在同一个会话中，不希望清除会话和新建会话。

**Comment by Plus-xu** [comment]
> > 模型温度超级常用，我针对每个智能体的模型温度都不同，比如翻译，日常对话，写作，数学计算等都设了不同的模型温度，并且每次调节模型温度都能生成不同的答案。现在没办法针对每个智能体设置不同模型温度了，非常不方便，希望能加回右侧的设置面板中。
> 
> 找到设置的地方了吗

谢谢，找到设置的地方了，我和上面一样，经常用到模型温度和回复token限制，希望可以恢复回右侧面板
