### ISSUE TITLE
无法恢复备份文件

### ISSUE THREAD

**Issue by LeoStruggle666** [kangfenmao/cherry-studio#341]
**问题描述：**
我使用场景是公司和家里的mac都有安装使用Cherry Studio，所以偶尔会有设备间配置同步需求，即“数据备份与恢复”。备份数据通常都没问题，但恢复时经常非常容易触发“备份文件格式错误”的报错。
以今天我尝试回复的备份文件“cherry-studio.202411121540.zip”为例，从文件名和压缩包格式看，似乎都很正常。到目前我也还没发现报错的触发规律，个人一个推测，是因为恢复时会做版本号校验？因为Cherry Studio更新频率很是挺高的，确实可能公司/家里的版本不一致。

**Comment by kangfenmao** [comment]
和更新应该关系不大，这个备份和恢复兼容所有版本。你先测试一下手动下载，并恢复试试，排除一下下载错误

**Comment by LeoStruggle666** [comment]
我刚刚又试了下，还是能正常备份但无法恢复....可以参考下👇gif的操作，有点神奇😂
![CleanShot 2024-11-14 at 17 15 32](https://github.com/user-attachments/assets/5143a1b5-d58c-4aaa-950f-b57b8f1107c9)

**Comment by kangfenmao** [comment]
那说明还是有问题，我得修一下 @LeoStruggle666

**Comment by LeoStruggle666** [comment]
@kangfenmao 另外还想问一下，有做移动端的打算吗？以及优先级如何呢？非常期待！

**Comment by kangfenmao** [comment]
有计划明年初开始

**Comment by kangfenmao** [comment]
@LeoStruggle666 能否加下我的微信，我来帮你看看这个问题

我的微信：kangfenmao

**Comment by kangfenmao** [comment]
已完成修复
