### ISSUE TITLE
设置里面的默认助手设置，点击关闭会把窗口最大化

### ISSUE THREAD

**Issue by gao1239520176** [kangfenmao/cherry-studio#344]
如下图所示，点击助手设置窗口的关闭，会使窗口最大化
![image](https://github.com/user-attachments/assets/8851c154-b514-475d-bf4c-1d8160fb304d)

**Comment by kangfenmao** [comment]
窗口弄的太小了，点到顶部窗口了，顶部窗口双击是最大化

**Comment by gao1239520176** [comment]
，果然是，不好意思打扰了




花落也无尘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kangfenmao/cherry-studio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月13日(星期三) 下午2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kangfenmao/cherry-studio] 设置里面的默认助手设置，点击关闭会把窗口最大化 (Issue #344)



 窗口弄的太小了，点到顶部窗口了，顶部窗口双击是最大化
