### ISSUE TITLE
Proxy don't work

### ISSUE THREAD

**Issue by leporel** [kangfenmao/cherry-studio#347]
Platform: Windows 11
Ver: 0.8.13

1. Proxy don't work, when i start ssh tunnel `ssh -D 1337 -N myvps` and past `socks5://localhost:1337` into settings, mini-app like chatGPT still don't work (shows my real IP)
2. The trey icon always shows up even closed app, there is no pop-up window when i click it, after the trey icon is turned off in settings - it still remains in system tray.

**Comment by kangfenmao** [comment]
You need to provide information about the operating system being used and the steps to reproduce the issue

**Comment by leporel** [comment]
OS: Windows 11 Pro 10.0.22631 x64

Proxy:
1. Start ssh SOCKS tunnel on port 1337 `ssh -D 1337-N user@remote.host`

2. Put `socks5://localhost:1337` in the settings

<details>
<summary><b>screenshot</b></summary>

![image](https://github.com/user-attachments/assets/ade58838-e302-4807-9e96-d0191587f4c4)

</details>

3. Try open miniapp ChatGPT
<details>
<summary><b>screenshot, IP address is not my proxy </b></summary>

![image](https://github.com/user-attachments/assets/2f98613b-2c46-4b85-8142-6fe0cadd0375)

</details>

---

Tray Icon Bug:
<details>
<summary><b>screenshot</b></summary>

![image](https://github.com/user-attachments/assets/351ba5b0-9a67-4970-907d-cd80c12a648c)

</details>

**Comment by kangfenmao** [comment]
Updated
