### ISSUE TITLE
可以支持Embedding模型的调用么？

### ISSUE THREAD

**Issue by Roderick-Stinson** [kangfenmao/cherry-studio#352]
当前情况下，读取文件时，还是通过已选模型作为prompt输入。
希望可以添加Embedding模型支持，通过Embedding模型读取上传的文件，这样可以节省很大的花销，谢谢

**Comment by kangfenmao** [comment]
正在做

**Comment by kangfenmao** [comment]
请求合并：https://github.com/kangfenmao/cherry-studio/issues/156
