### ISSUE TITLE
重启之后无法保存界面的缩放&缩放快捷键不支持小键盘

### ISSUE THREAD

**Issue by Calvaire** [kangfenmao/cherry-studio#354]
1、放大/缩小之后，重启App无法保存缩放，有时当再次使用缩放快捷键后才会重新变为之前的缩放。
2、缩放快捷键的+、-、0不支持小键盘的按键，希望能增加支持，或者增加相应提示。

**Comment by kangfenmao** [comment]
快捷键不是使用的加号减号，而是使用的 - 和 =

**Comment by Calvaire** [comment]
> 快捷键不是使用的加号减号，而是使用的 - 和 =

原来如此，因为我看设置里提示的是加号减号
![image](https://github.com/user-attachments/assets/6098c294-3c5c-43ff-a866-3ced9dc44ccb)

**Comment by kangfenmao** [comment]
更新一下软件

**Comment by Calvaire** [comment]
> 更新一下软件

软件版本：v0.8.17，系统WIN10，重启后还是不能保存缩放，并且有时候过了一会才能变成之前设置的缩放（目前没能找到复现的规律）
