### ISSUE TITLE
黑屏了！

### ISSUE THREAD

**Issue by itmanmax** [kangfenmao/cherry-studio#357]
![image](https://github.com/user-attachments/assets/33c9ba11-be30-4666-9d39-63942ed1ddf6)
打开之后黑屏

**Comment by kangfenmao** [comment]
这个是由于把模型回复的代码解析成为了 html 导致的错误，我今天会发版修复这个问题

**Comment by kangfenmao** [comment]
手动更新一下软件试试 @itmanmax
