### ISSUE TITLE
设置 api 后显示连接失败怎么办呢？

### ISSUE THREAD

**Issue by EdmundsYan** [kangfenmao/cherry-studio#358]
<img width="1081" alt="image" src="https://github.com/user-attachments/assets/b7c51e55-1b73-450c-b4ab-0b7983bc6e58">
添加 api 是 grok，但一直无法连接。网络是畅通的，添加到 chatbox 时都能正常使用。求大佬帮助一下！

**Comment by Chenastron** [comment]
请问是怎么解决的？

**Comment by kangfenmao** [comment]
> 请问是怎么解决的？

他的地址填错了，你看后面还有一个重置按钮
