### ISSUE TITLE
支持行内公式

### ISSUE THREAD

**Issue by aqquser** [kangfenmao/cherry-studio#36]
行内公式 显示不出来，例如：

![image](https://github.com/user-attachments/assets/03602d86-5dd7-42ab-8830-e6094474fa43)

**Comment by aqquser** [comment]
@kangfenmao 
原文是   “- 从 \(\frac{\partial \mathcal{L}}{\partial y} = 0\) 得到：”
软件渲染出来是：
![image](https://github.com/user-attachments/assets/bf1d6ba6-c307-4666-a387-1a90d85cb3c6)

**Comment by kangfenmao** [comment]
的确是有这个问题，等我空下来我得再看一下，这个链接作为参考

https://github.com/kangfenmao/cherry-studio/issues/15#issuecomment-2268220342

**Comment by aqquser** [comment]
> 的确是有这个问题，等我空下来我得再看一下，这个链接作为参考
> 
> [#15 (comment)](https://github.com/kangfenmao/cherry-studio/issues/15#issuecomment-2268220342)

我在chatbox中，发现以下问题：
![image](https://github.com/user-attachments/assets/22352172-e2e4-43fd-b682-f84e811ede62)
我的理解是把  \(...\) 转化成 $...$，把 \[...\]转化成 $$...$$，然后再渲染。
当然他这个错误 应该是 转换不彻底导致的，没有  \]转化成$$ 
@kangfenmao

**Comment by kangfenmao** [comment]
<img width="810" alt="image" src="https://github.com/user-attachments/assets/641ce97c-9f49-48f7-9233-e7ad40c2d584">
