### ISSUE TITLE
BUG: gemini 渠道无法连接，最新 gemini-exp 模型无法使用

### ISSUE THREAD

**Issue by fangyuan99** [kangfenmao/cherry-studio#360]
软件有没有日志输出？如有可以提供报错信息

**Comment by kangfenmao** [comment]
估计是和代理设置有关系

需要到翻墙软件配置下面地址，使用非中国节点，并且翻墙软件要打开 TUN 模式或者增强模式

https://generativelanguage.googleapis.com

**Comment by fangyuan99** [comment]
已解决
