### ISSUE TITLE
Github model和Mistral的最拳大模型自动识别不全，且无法识别视觉模型

### ISSUE THREAD

**Issue by vimbackground** [kangfenmao/cherry-studio#363]
1. Github model模型自动识别不全，如“Cohere-command-r-plus-08-2024”、“Llama-3.2-11B-Vision-Instruct”等，经测试，可以手动添加，建议更新一下
2. Mistral的模型无法识别其中的视觉模型pixtral

强迫症建议：相关大模型分组能否优化一下，同一平台下，同一公司推出的大模型(或者同一类的大模型)，能否放在同一分组下--这个不重要，有空时可以考虑优化一下：）

**Comment by kangfenmao** [comment]
第一个问题是数据源问题，Cherry Studio 也不清楚
第二个问题实际上也做不了，数据结构不支持，也就是缺少数据无法识别他们归属

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/f516d935-126f-4b79-a81e-585f23f7ca3b)

我做了一个改进，下个版本发

**Comment by vimbackground** [comment]
这样看起来相当的舒服，好评!!!
