### ISSUE TITLE
温度设置恢复和添加常用模型按钮

### ISSUE THREAD

**Issue by Plus-xu** [kangfenmao/cherry-studio#365]
1. 建议将温度设置功能恢复至右侧设置面板的中上部位置。当前的调整方式降低了经常需要调节温度参数的用户的操作效率。
2. 建议增设常用模型快捷切换功能（如下图所示）。对于使用多个模型的用户，希望能提供个性化的模型固定选项，允许用户将常用模型固定在界面顶部或底部，实现一键切换，从而提升操作便利性。
![image](https://github.com/user-attachments/assets/0917e2af-4c3b-42ab-896b-e889cd60439f)

谢谢！

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/b7488d47-145e-4185-ba96-7fb3550a5c7f)
