### ISSUE TITLE
模型回答时可以新建对话

### ISSUE THREAD

**Issue by yangtb2024** [kangfenmao/cherry-studio#369]
模型回答时原本点击其他地方会提示`模型回答完成后才能切换`。
但是新建对话可以点击，随后会进入一个新对话，并且点击其他地方仍然提示`模型回答完成后才能切换`，需要等待刚才那个回复完才行。

![image](https://github.com/user-attachments/assets/593f32eb-97b1-47d5-9d60-1c6319012c87)

**Comment by kangfenmao** [comment]
我修一下
