### ISSUE TITLE
打开小程序，左侧边栏的导航会被遮盖住无法点击

### ISSUE THREAD

**Issue by whshang** [kangfenmao/cherry-studio#37]
Sonoma 14.6.1
Arc Version 1.58.1 (53264)
Chromium Engine Version 128.0.6613.85
v0.6.2

任意小程序开启后，左侧边栏按钮可以看到但点不了，必须关闭小程序才可以点击

另外，如果使用微信扫码登录小程序内的页面，登录窗口会开启新窗口而不是刷新应用内页面，也就登不进去

**Comment by kangfenmao** [comment]
设计上小程序打开的时候是不允许点击左侧区域的，可以加一个提示。微信扫描登录问题，我会看一下

**Comment by kangfenmao** [comment]
更新到新版本 https://github.com/kangfenmao/cherry-studio/releases/tag/v0.6.8

看看扫码登录的问题是否解决

**Comment by kangfenmao** [comment]
ref: https://github.com/kangfenmao/cherry-studio/issues/50
