### ISSUE TITLE
gpt-4o 无法插入图片

### ISSUE THREAD

**Issue by xgugeng** [kangfenmao/cherry-studio#370]
Model Provider：Azure OpenAI
Model: gpt-4o
Version: 0.8.17

点击对话框的上传按钮没有翻译，右键会出现图二的报错
![image](https://github.com/user-attachments/assets/c2b5ca58-8876-4aa5-9cd5-c609099614b8)

![image](https://github.com/user-attachments/assets/c29de501-b092-4cad-bc0b-c779a518fa2b)

**Comment by kangfenmao** [comment]
先用复制粘贴试试

**Comment by xgugeng** [comment]
试了也没有反应 😢

**Comment by kangfenmao** [comment]
> 试了，也没有反应 😢

还有一个问题，和模型有关系吗。是不是只要点这里就会报错

**Comment by xgugeng** [comment]
和模型无关，右键点击下面任何输入框下面任何一个模型都会报错。平台是 Windows 11
![image](https://github.com/user-attachments/assets/ba41b011-43ff-4a7e-9030-92c7a7ad9281)

**Comment by kangfenmao** [comment]
我明白你的问题原因了，这是由于社区有人 PR 的时候导致的一个错误。你需要手动切换一下语言，这里估计就正常了。

@xgugeng

**Comment by xgugeng** [comment]
软件的语言设置吗，还是不行。我的系统语言是 English (Australia)
![image](https://github.com/user-attachments/assets/473fbb19-23da-4985-96c6-97f0e7efb442)

**Comment by kangfenmao** [comment]
> 软件的语言设置吗，还是不行。我的系统语言是 English (Australia) ![image](https://private-user-images.githubusercontent.com/5053603/388390291-473fbb19-23da-4985-96c6-97f0e7efb442.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzI1OTksIm5iZiI6MTczMjE3MjI5OSwicGF0aCI6Ii81MDUzNjAzLzM4ODM5MDI5MS00NzNmYmIxOS0yM2RhLTQ5ODUtOTZjNi05N2YwZTdlZmI0NDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMDY1ODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVjMjBlM2NiNjVmMzE5MjAxZTA0OGI3NzJiZjNjNjBlNDYxZTExMzI0YzI1NzAzMTkzYzFjOTc1ZDliNTdjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0MFB2l0QgM1xOkC11fvEbGuLtDTmeqy9YEIGadxJlBA)

嗯我下个版本修复一下这个问题

**Comment by kangfenmao** [comment]
切换完语言重启一下再试试，这里的问题在于没有判断不支持的语言的情况

**Comment by xgugeng** [comment]
如果你指的重启软件的话，每次切换之后我都有重启。现在发现这个报错不限于输入框，只要在软件内右键都会这样。不太确定修复之后，是不是就可以插入图片了。

**Comment by xgugeng** [comment]
另外的问题
1. 切换语言后，会立即生效。关掉软件之后，system tray 还在，左键和右键均无反应
2. 只能从 task manager 里杀死，但再打开还是英语

**Comment by kangfenmao** [comment]
> 另外的问题
> 
> 1. 切换语言后，会立即生效。关掉软件之后，system tray 还在（设置里已关闭），左键和右键均无反应
> 2. 只能从 task manager 里杀死，但再打开还是英语

语言导致的问题，等我修复吧

**Comment by xgugeng** [comment]
谢谢响应，暂时回退到 [v0.8.7](https://github.com/kangfenmao/cherry-studio/releases/tag/v0.8.7)，一切正常

**Comment by kangfenmao** [comment]
使用这个版本试试，我修改了菜单语言的设置 @xgugeng https://github.com/kangfenmao/cherry-studio/releases/tag/v0.8.18

**Comment by xgugeng** [comment]
> 使用这个版本试试，我修改了菜单语言的设置 @xgugeng https://github.com/kangfenmao/cherry-studio/releases/tag/v0.8.18

确认 thread 里提到的问题都已修复，感谢 💖
