### ISSUE TITLE
希望可以支持讯飞星火APIkey

### ISSUE THREAD

**Issue by qinchunice** [kangfenmao/cherry-studio#374]

**Comment by qinchunice** [comment]
希望能支持讯飞星火

**Comment by kangfenmao** [comment]
可以手动添加进去

**Comment by qinchunice** [comment]
> 可以手动添加进去

可不可以教教，完全不懂代码，手动添加里面只有密码和地址两个选项，但是星火的有四个，APPID、APISecret、APIKey、ws(s)，完全不知道该怎么设置😭

**Comment by kangfenmao** [comment]
我明天再回复你这个设置

**Comment by qinchunice** [comment]
好滴

**Comment by kangfenmao** [comment]
## API KEY

https://console.xfyun.cn/services/cbm

![image](https://github.com/user-attachments/assets/2f0ba2d2-c4f2-4de1-b7e0-d88f84a14d98)

## 配置

![image](https://github.com/user-attachments/assets/e76a1983-323c-4001-9bb8-b75b7ee599b0)

模型需要手动添加，支持 lite,generalv3,pro-128k,generalv3.5,max-32k,4.0Ultra

**Comment by qinchunice** [comment]
ok
