### ISSUE TITLE
webdav设置报错

### ISSUE THREAD

**Issue by Long-louis** [kangfenmao/cherry-studio#375]
![image](https://github.com/user-attachments/assets/f6c8986c-2dc8-4b78-bfef-758bc615b6e5)
不知道是不是因为webdav路径含有中文？

**Comment by kangfenmao** [comment]
你的 webdav 服务商可能不支持中文或者特殊字符，换一个服务商或者修改备份路径试试

**Comment by kangfenmao** [comment]
后来有备份成功过吗 @Long-louis

**Comment by DrayChou** [comment]
看报错提示就是不支持的字符类型，不要用中文名称或者空格作为目录名

**Comment by mpbizn** [comment]
后续可以支持中文路径吗
