### ISSUE TITLE
Ollama 获取 API KEY

### ISSUE THREAD

**Issue by haitaoge** [kangfenmao/cherry-studio#377]
本地Ollama 如何获取API Key？

**Comment by kangfenmao** [comment]
留空

**Comment by haitaoge** [comment]
> 留空

留空好像不可以 
![image](https://github.com/user-attachments/assets/963f0acd-7753-413b-987c-59676f846e98)

**Comment by kangfenmao** [comment]
你的 ollama 如果不是本地安装的，需要询问服务商密码是多少

**Comment by yoreeee** [comment]
> 你的 ollama 如果不是本地安装的，需要询问服务商密码是多少 [@haitaoge](https://github.com/haitaoge)

是本地安装，key留空显示连接失败

**Comment by bestgopher** [comment]
> > 你的 ollama 如果不是本地安装的，需要询问服务商密码是多少 [@haitaoge](https://github.com/haitaoge)
> 
> 是本地安装，key留空显示连接失败，并且key一旦输入就无法删除为空了。v0.9.17版本。

+1

**Comment by euzenlee** [comment]
有解决方案了没有？本地部署的服务，apikey填或不填都不行。

**Comment by hainingning** [comment]
> 有解决方案了没有？本地部署的服务，apikey填或不填都不行。

Service文件里配置这两行环境变量重启ollama就行了，在nextchat的使用文档看见的。
![Image](https://github.com/user-attachments/assets/fed26771-5c2b-4c79-928a-1afb07460e29)
![Image](https://github.com/user-attachments/assets/771a82f3-cbc3-4616-b68d-c3413da41712)

**Comment by wuxinliuyun** [comment]
最新版还是会触发这个bug

**Comment by wuxinliuyun** [comment]
检查一下ollama有没有在后台运行！后台没有的话就会这样
