### ISSUE TITLE
目前对于模型是否支持图片理解是如何判定的？

### ISSUE THREAD

**Issue by Masque423** [kangfenmao/cherry-studio#378]
目前对于多模态模型是如何判定的？
最近 Gemini 新增的模型 gemini-exp-1114, gemini-exp-1121 都支持图片输入，但是添加模型后却显示不支持图片，图片能发，但是模型貌似收不到。
![image](https://github.com/user-attachments/assets/5b1d167b-f85b-4352-84f0-6d3ad9a8716c)

带眼睛的模型 gemini-1.5-pro-002 能够正常读图，可不可以让用户手动设置模型是否支持视觉呢？
![image](https://github.com/user-attachments/assets/4898d543-c985-41d6-a2ae-87ff5b4b545c)

**Comment by ZzzzRyan** [comment]
我这边测试没问题

<img src=https://github.com/user-attachments/assets/df70ab3d-da64-4fed-a2cd-007d71db356d width=550>

是从官网接的API吗？可以检查看看是不是服务商的问题。

**Comment by kangfenmao** [comment]
现在使用内置规则判定的，后面给单个模型增加一个设置就好了

**Comment by kangfenmao** [comment]
const visionAllowedModels = [
  'llava',
  'moondream',
  'minicpm',
  'gemini-1\\.5',
  'gemini-exp',
  'claude-3',
  'vision',
  'glm-4v',
  'qwen-vl',
  'qwen2-vl',
  'internvl2',
  'grok',
  'pixtral',
  'gpt-4(?:-[\\w-]+)',
  'gpt-4o(?:-[\\w-]+)?',
  'chatgpt-4o(?:-[\\w-]+)?'
]

**Comment by Masque423** [comment]
> 现在使用内置规则判定的，后面给单个模型增加一个设置就好了

是的，还是增加设置比较好，内置规则有个弊端就是如果是自定义了模型名，很有可能匹配不到规则

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/6814eb27-fef7-46d3-8a5d-c3e7008129ef)
