### ISSUE TITLE
Markdown格式图片显示不正确，多个代理下的相同模型会显示错误

### ISSUE THREAD

**Issue by Komorebi-yaodong** [kangfenmao/cherry-studio#38]
Markdown格式图片显示不正确
![image](https://github.com/user-attachments/assets/44e42cb7-ab25-424e-b74f-6d7e16326f8e)

多个代理下的相同类型的模型（如gpt-4o-mini）会出现显示问题：模型列表只显示一种模型

**Comment by kangfenmao** [comment]
需要你复制一下你发送的内容，粘贴到下面评论框 @Komorebi-yaodong

**Comment by Komorebi-yaodong** [comment]
就像这样：
```
![image](https://github.com/user-attachments/assets/44e42cb7-ab25-424e-b74f-6d7e16326f8e)
```

**Comment by kangfenmao** [comment]
感谢提供反馈，这个问题我已经修复了，下个版本发布 @Komorebi-yaodong

**Comment by kangfenmao** [comment]
已经发布新版本解决了这个问题

**Comment by Komorebi-yaodong** [comment]
当我使用官方与中转代理，并开启同一种模型时，默认模型页面的所有模型会显示错误，如果一开始没显示错误，选择时也会显示错误，如下图所示
![image](https://github.com/user-attachments/assets/66e16bae-9f35-4907-84aa-9f35bdcd1c7b)

**Comment by kangfenmao** [comment]
> 当我使用官方与中转代理，并开启同一种模型时，默认模型页面的所有模型会显示错误，如果一开始没显示错误，选择时也会显示错误，如下图所示 ![image](https://private-user-images.githubusercontent.com/84176918/365073605-66e16bae-9f35-4907-84aa-9f35bdcd1c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDgyOTEsIm5iZiI6MTcyNTYwNzk5MSwicGF0aCI6Ii84NDE3NjkxOC8zNjUwNzM2MDUtNjZlMTZiYWUtOWYzNS00OTA3LTg0YWEtOWYzNWJkY2QxYzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA3MzMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MmYwYjliMTIwZTMzZTVlNjc4OTVjZTQ0MmMwM2VkNGU0Zjc3MmVkMDQ3OGFjYWQ1OWUyMWZiMWZlZTU3MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.whTMqmY1nuMiSnYU3DjJIJzEGyVBZv-68R8zSY31QOc)

是用的同一个服务商吗，能否截图看一下服务商下面添加的模型

**Comment by Komorebi-yaodong** [comment]
不是同一个服务商，只是模型名称相同
![image](https://github.com/user-attachments/assets/2439e4ba-cac1-4f6e-8cb9-bcb2e69172cc)

**Comment by kangfenmao** [comment]
https://github.com/kangfenmao/cherry-studio/releases/tag/v0.6.10

@Komorebi-yaodong 这个模型 ID 重复显示异常的问题已经修复过了，使用新版本测试一下看看

**Comment by Komorebi-yaodong** [comment]
新版本没有错误，感谢！
