### ISSUE TITLE
一个小BUG，链接失败警告不消失。

### ISSUE THREAD

**Issue by Sucorde** [kangfenmao/cherry-studio#382]
![image](https://github.com/user-attachments/assets/a38f0e38-24c6-4fdd-93bc-dbdde0c3941e)

**Comment by kangfenmao** [comment]
8秒消失

**Comment by Sucorde** [comment]
> 8秒消失

我的一天都没消失。

**Comment by kangfenmao** [comment]
有没有复现路径

**Comment by Sucorde** [comment]
我是点击验证很多次。然后就卡在那里了。

**Comment by kangfenmao** [comment]
> 我是点击验证很多次。然后就卡在那里了。

修掉了，检测过程中禁止点击了
