### ISSUE TITLE
Gemini 连接问题

### ISSUE THREAD

**Issue by WindWash** [kangfenmao/cherry-studio#383]
使用 cloudflare 反代了 generativelanguage.googleapis.com，跟换 API 地址后无法连接。

但是使用 #316 上面提到的客户端可以正常使用，并且在翻译插件里面也可以正常调用。

是我哪设置的不对吗？还是什么原因？

<img width="1192" alt="截屏2024-11-25 21 17 19" src="https://github.com/user-attachments/assets/6beb2153-8535-4705-b6e0-78b60d9aa190">

**Comment by kangfenmao** [comment]
微信私聊我帮你看看：kangfenmao

**Comment by kangfenmao** [comment]
已修复，下个版本上
