### ISSUE TITLE
可否增加markdown的图绘制能力解析，例如流程图等

### ISSUE THREAD

**Issue by HaishengLiang** [kangfenmao/cherry-studio#386]
如题： 支持markdown的diagrams的渲染
类似下文

```mermaid
graph TD;
    A[节点 A] --> B[节点 B]
    A --> C[节点 C]
    B --> D[节点 D]
    C --> D
    C --> E[节点 E]
    D --> E
    D --> F[节点 F]

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/6f0fe86a-cc55-4760-b99b-b987f70f8795)

目前支持 Mermaid

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/6f46c90d-343f-4d8f-8ea1-52dbe3924356)
