### ISSUE TITLE
Cherry Studio考虑出安卓版本吗？

### ISSUE THREAD

**Issue by xixia123** [kangfenmao/cherry-studio#389]
这个软件是目前我体验下来对API管理最好的软件，内置的各种助手也很有用，想请问下会考虑增加移动设备的支持吗？比方说安卓或者ios版本的app。

**Comment by kangfenmao** [comment]
需求合并，参考一下这个：https://github.com/kangfenmao/cherry-studio/issues/152

计划是明年开始弄
