### ISSUE TITLE
Claude 3.5 Sonnet

### ISSUE THREAD

**Issue by scaactk** [kangfenmao/cherry-studio#39]
When I use the API from Anthropic, this bug often comes up.  But when I change to another assistant talk or open a new talk, it works.
Default Assistant, API check is fine.

"Something went wrong. Please check if you have set your API key in the Settings > Providers
Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: first message must use the "user" role"}}"

**Comment by kangfenmao** [comment]
Ok, I will fix this in a later version

**Comment by scaactk** [comment]
Thanks, I already updated it to v0.6.6, however, the same problem still exists, could you help me check that again?

**Comment by scaactk** [comment]
Thanks, I already updated it to v0.6.6, however, the same problem still exists, could you help me check that again?

**Comment by kangfenmao** [comment]
V0.6.6 was developed before. This problem I will take a look at today

**Comment by kangfenmao** [comment]
I've fixed this problem. The next version will be released
