### ISSUE TITLE
webdav 支持加密

### ISSUE THREAD

**Issue by m2uyo** [kangfenmao/cherry-studio#393]
希望可以根据密钥加密上传到webdav上的备份文件
解密的时候也是用该密钥解密

**Comment by m2uyo** [comment]
![图片](https://github.com/user-attachments/assets/b60ab703-c13a-41fa-8e88-167f653a91cd)
这里 setPassword 一下应该也可以?
上传云端还是希望云端数据安全

**Comment by kangfenmao** [comment]
需求合并：https://github.com/kangfenmao/cherry-studio/issues/220
