### ISSUE TITLE
add a function 

### ISSUE THREAD

**Issue by Yalyenea** [kangfenmao/cherry-studio#396]
1. can you add a function that can make the output message without  markdown or latex. I want copy the original content.
2. the translation can be auto?

**Comment by kangfenmao** [comment]
1. Just copy the content
2. Can you provide a detailed explanation to help me understand?

**Comment by Yalyenea** [comment]
1. 当遇到LaTeX公式时，复制体验并不好，如果可以切换输出的源格式，方便$$等符号来显示公式
2. 翻译功能，当输入文字的时候，右侧的翻译能够在较短时间内自动更新，而不用点击翻译按钮
