### ISSUE TITLE
[feature] 希望添加一个关闭总结标题的按钮

### ISSUE THREAD

**Issue by delph1s** [kangfenmao/cherry-studio#399]
我经常自己为重要的对话进行标题编辑，并且删除一些不重要的话题。因此，我希望能够有一个禁止总结标题的开关，省一些API的额度。再次感谢大佬的工具！

**Comment by kangfenmao** [comment]
可以

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/ca587b87-6777-4199-9d89-dcdc30023d48)

**Comment by kangfenmao** [comment]
已经上线
