### ISSUE TITLE
不能使用GitHub model的模型的api，好像是因为路径不一样，没有V1

### ISSUE THREAD

**Issue by corwin1949** [kangfenmao/cherry-studio#40]
它的请求路径是：https://models.inference.ai.azure.com/chat/completions。
openai格式

**Comment by kangfenmao** [comment]
这个问题我今天会看一下，你可以先尝试用这样的 API 地址

https://models.inference.ai.azure.com/chat/completions/

**Comment by kangfenmao** [comment]
@corwin1949 按照我的方法能否解决问题？

**Comment by corwin1949** [comment]
> @corwin1949 按照我的方法能否解决问题？

还是不行，404

**Comment by corwin1949** [comment]
> 出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥
> Error: 404 Resource not found

试了下其他客户端，可以用，可能是是 cherry-studio 自动增加了/v1……这样的请求路径，结果GitHub model路径不一样，就找不到路径了

**Comment by corwin1949** [comment]
GitHub model 的项目地址是，申请还挺好过的

https://github.com/marketplace/models

**Comment by corwin1949** [comment]
已经解决，地址设置如下即可
```https://models.inference.ai.azure.com/chat/completions#```

使用 # 号屏蔽掉客户端增加的路径后缀。

**Comment by kangfenmao** [comment]
> GitHub model 的项目地址应该是是，申请还挺好过的
> 
> 
> 
> https://github.com/marketplace/models

那我去申请一个，调试调试看看

**Comment by Komorebi-yaodong** [comment]
> 已经解决，地址设置如下即可 `https://models.inference.ai.azure.com/chat/completions#`
> 
> 使用 # 号屏蔽掉客户端增加的路径后缀。

但是这样的话无法自动抓取模型了

**Comment by kangfenmao** [comment]
我的 Github Models 已经申请成功了，我等会看一下

**Comment by kangfenmao** [comment]
<img width="912" alt="Electron 2024-09-11 19 09 15" src="https://github.com/user-attachments/assets/d69fc074-2874-4569-94f0-078e371d8bec">

晚上发新版本 @corwin1949 @Komorebi-yaodong

**Comment by Komorebi-yaodong** [comment]
> <img alt="Electron 2024-09-11 19 09 15" width="912" src="https://private-user-images.githubusercontent.com/8253512/366429798-d69fc074-2874-4569-94f0-078e371d8bec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTY3NjYsIm5iZiI6MTcyNjA1NjQ2NiwicGF0aCI6Ii84MjUzNTEyLzM2NjQyOTc5OC1kNjlmYzA3NC0yODc0LTQ1NjktOTRmMC0wNzhlMzcxZDhiZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMTIwNzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY1YTZjZThjNDBiZTcwNzg4NGU1MWVkMDY2MDFiZDQzYTEzMjcyMzVjZmZiOTNmZGZjYzY4YzlmOWE0YjAzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YgH1XlmLPbcX5tve5GLTejzotq6qKXTHUDJAtqDptQk">
> 晚上发新版本 @corwin1949 @Komorebi-yaodong

感谢！

**Comment by corwin1949** [comment]
> <img alt="Electron 2024-09-11 19 09 15" width="912" src="https://private-user-images.githubusercontent.com/8253512/366429798-d69fc074-2874-4569-94f0-078e371d8bec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzE0NDksIm5iZiI6MTcyNjA3MTE0OSwicGF0aCI6Ii84MjUzNTEyLzM2NjQyOTc5OC1kNjlmYzA3NC0yODc0LTQ1NjktOTRmMC0wNzhlMzcxZDhiZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMTYxMjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjRmZjVhMzQ5ODgwM2Q5ZDBiOTE3NGE0NzZmNzg5YTdmODEyN2RlNGZmYzYxZmU4YmNhYTQ0YjM4OTM0YjMxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AA19qMT6MfaU99B2H38Ph5zj3Gf-hMTjHlO6Fh7Ba-E">
> 晚上发新版本 @corwin1949 @Komorebi-yaodong

好哎，用上了
