### ISSUE TITLE
[bug] 启动白屏，重装还是白屏

### ISSUE THREAD

**Issue by jipiyan** [kangfenmao/cherry-studio#400]
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/3ce992ba-9a6a-4b27-8706-afbfd58442af">

这是控制台的截图

**Comment by kangfenmao** [comment]
加一下我的微信吧，我帮你看下数据：kangfenmao

**Comment by jipiyan** [comment]
> 加一下我的微信吧，我帮你看下数据：kangfenmao
> 
> @jipiyan

谢谢大佬，刚把 ~/Application Support/CherryStudio 删除后重装恢复了。QAQ 数据没了，不能帮大佬复现了

**Comment by kangfenmao** [comment]
大概是公式引擎出的问题，我得想个办法让他不要崩溃

**Comment by kangfenmao** [comment]
大概是公式引擎出的问题，我得想个办法让他不要崩溃

**Comment by jipiyan** [comment]
> 大概是公式引擎出的问题，我得想个办法让他不要崩溃

应该是的，刚是在翻译文献时出现问题，然后崩溃白屏

**Comment by kangfenmao** [comment]
新版本增加了错误处理，如果内容出错不影响 APP 使用
