### ISSUE TITLE
错误弹出 “更新出错” 提示

### ISSUE THREAD

**Issue by ZzzzRyan** [kangfenmao/cherry-studio#401]
当前有新版本的时候，在软件里点击“检查更新”按钮会弹出“**更新出错**”的提示，但实际上已经开始下载更新了，后续也能正常更新。

![image](https://github.com/user-attachments/assets/fa266e94-2f4e-4bd0-a465-5f1b71627e1c)

**Comment by kangfenmao** [comment]
这个我修了，最新版本再检查才能没问题
