### ISSUE TITLE
[功能]: 希望能在话题栏的最上方添加一个新建话题按钮

### ISSUE THREAD

**Issue by redapple0204** [kangfenmao/cherry-studio#404]
### 您的功能建议是否与某个问题相关?

有时候在多个历史话题中浏览，然后想要新建一个新的话题进行对话，这个时候点击右下角的新建话题按钮感觉距离太远，按钮太小，不是很方便操作

### 请描述您希望实现的解决方案

因此希望能在话题栏的最顶端添加一个“新建话题”的按钮，大概效果如图
![image](https://github.com/user-attachments/assets/35a0fd3b-f1e1-4e6f-805d-fd6fa503bb2b)
然后当用户开始对话之后，则立刻在右侧新建一个新的话题，这个新建话题的按钮仍然不变，就像这样
![image](https://github.com/user-attachments/assets/613e596e-6e43-4ccb-bd02-3ba4e2aef026)

**Comment by kangfenmao** [comment]
这个问题，我需要再考虑。建议优先使用快捷键来创建新话题。
