### ISSUE TITLE
[功能]: 开启消息长度限制希望能用键盘输入值

### ISSUE THREAD

**Issue by Guanrenfu** [kangfenmao/cherry-studio#405]
### 您的功能建议是否与某个问题相关?

 消息长度限制

### 请描述您希望实现的解决方案

![image](https://github.com/user-attachments/assets/30c23049-d8ec-448e-8bc5-d90b2e04e4a2)
现在只能滑条滑动整百的数值，但有些情况需要输入4096,8192这样的数，希望可以添加一个键盘输入的输入框来输入具体的数值

**Comment by kangfenmao** [comment]
已经看到，会考虑

**Comment by kangfenmao** [comment]
助手名字 -> 右键 -> 编辑助手 -> 模型设置

里面可以输入数字
