### ISSUE TITLE
[Bug]: 严重bug，设置快捷键导致应用无法打开

### ISSUE THREAD

**Issue by elfcute** [kangfenmao/cherry-studio#407]
### Platform

Windows

### Version

v0.8.22

### Bug Description

设置快捷键‘ctrl+向上箭头’，显示面板，然后应用就废掉了，如图所示
并且还进不去应用面板界面，无法重置快捷键，一直是弹出错误提示词

![image](https://github.com/user-attachments/assets/a0f7d667-c273-4bad-8624-0a951ea736b8)
![image](https://github.com/user-attachments/assets/4b00c91b-8892-4e72-a7f0-e606f4a620e8)

### Steps To Reproduce

1、快捷键设置
2、显示面板快捷键设置为‘ctrl+向上箭头’
3、缩小cherry-studio应用程序
4、在电脑上，按下快捷键ctrl+向上箭头‘

### Expected Behavior

已经卡死了，是不是需要重新安装应用？
那这个里面的数据是不是全部清除了？？？

**Comment by elfcute** [comment]
> C:\Users\wangqian\AppData\Roaming\CherryStudio\config.json
> 
> 看看能否先编辑一下这个文件，把开关给去掉 @elfcute

早上问了Claude也是这么解决的，问题在于后面我又试了其他快捷键ctrl+ alt +space显示应用也是会弹出错误提示
所以，是不是有bug，显示快捷键现在设置快捷键会导致程序崩溃

**Comment by kangfenmao** [comment]
> > C:\Users\wangqian\AppData\Roaming\CherryStudio\config.json
> > 看看能否先编辑一下这个文件，把开关给去掉 @elfcute
> 
> 早上问了Claude也是这么解决的，问题在于后面我又试了其他快捷键ctrl+ alt +space显示应用也是会弹出错误提示 所以，是不是有bug，显示快捷键现在设置快捷键会导致程序崩溃

感谢发现重大 bug, 我已经干了一个小时，做了各种错误处理
