### ISSUE TITLE
[功能]: 有考虑添加源到homebrew和scoop吗？

### ISSUE THREAD

**Issue by ypxun** [kangfenmao/cherry-studio#408]
### 您的功能建议是否与某个问题相关?

mac端想要用Homebrew来安装和管理，win端用的是scoop。我查了下，cherry-studio还没接入这俩。

### 请描述您希望实现的解决方案

如果无版权纠纷的话，希望能添加到这俩库里。

**Comment by kangfenmao** [comment]
暂时还没接入，还没有调研如何接入

**Comment by EFLKumo** [comment]
已提交 scoop PR 等待合并
https://github.com/ScoopInstaller/Extras/pull/14614

**Comment by ypxun** [comment]
> 已提交 scoop PR 等待合并
> https://github.com/ScoopInstaller/Extras/pull/14614

谢咯，现在用的是其他人整理的源，能添加到官方源里肯定更好。

**Comment by Mrered** [comment]
~~这是我和我的小伙伴维护的 Homebrew 第三方组织的仓库。~~

~~如果 @kangfenmao 您希望在 Homebrew 官方库中维护，可以参考我们的实现：~~

我发现已经在官方库里了，话题结束。

**Comment by toddyoe** [comment]
@EFLKumo @kangfenmao 是否可以将pre-release版加入到 [Version](https://github.com/ScoopInstaller/Versions) 仓库，方便通过Scoop随时更新最新Build的版本

**Comment by EFLKumo** [comment]
> @EFLKumo @kangfenmao 是否可以将pre-release版加入到 [Version](https://github.com/ScoopInstaller/Versions) 仓库，方便通过Scoop随时更新最新Build的版本

好巧不巧 刚刚在 github.com/EFLKumo/cherry-studio-nightly-win 写了自动构建。有时间看看加到 version 里面

**Comment by kangfenmao** [comment]
我需要怎么操作

**Comment by toddyoe** [comment]
> > [@EFLKumo](https://github.com/EFLKumo) [@kangfenmao](https://github.com/kangfenmao) 是否可以将pre-release版加入到 [Version](https://github.com/ScoopInstaller/Versions) 仓库，方便通过Scoop随时更新最新Build的版本
> 
> 好巧不巧 刚刚在 github.com/EFLKumo/cherry-studio-nightly-win 写了自动构建。有时间看看加到 version 里面

那可真是太巧了，坐等大佬的PR被喝道Scoop的Version库，那样更新方便多了

**Comment by EFLKumo** [comment]
> 我需要怎么操作

您好，可能 GitHub actions 那个 nightly 构建需要修一下，现在是不可用的 感谢 🤗

**Comment by EFLKumo** [comment]
https://github.com/ScoopInstaller/Versions/pull/2199
