### ISSUE TITLE
保存为markdown或者复制时公式显示有问题

### ISSUE THREAD

**Issue by Long-louis** [kangfenmao/cherry-studio#409]
![image](https://github.com/user-attachments/assets/6510197c-6b08-4c3f-916e-02a686d7d6c1)
这是复制之后粘贴在typora中显示的内容，这种latex公式格式不能正确渲染，需要修改为$$包裹才行

**Comment by ZzzzRyan** [comment]
这个需要调整的是大模型输出的内容，你可以在 prompt 中对大模型进行引导，让它把数学公式包裹在 `$$` 中即可。

> 顺便说一句：事实上，`$$` 是 $\TeX$ 的原始语法；在 $\LaTeX$ 中，并不正式支持 `$$` 的公式环境，使用 `\[ \]` 才是更推荐的用法。
> 关于 Typora 无法渲染这事，从 2016 年开始，就有人给 Typora 提过 issue，但截止目前并没有什么进展 :/

**Comment by kangfenmao** [comment]
这个应该提交给 Typora 来解决了
