### ISSUE TITLE
[Bug]: ~~热更新bug~~ 已解决 删除了吧

### ISSUE THREAD

**Issue by elfcute** [kangfenmao/cherry-studio#411]
### Platform

Windows

### Version

0.8.22

### Bug Description

~~如图所示，热更新无法安装。

提示要手动关闭程序，但是如图所示，应用里面压根就没有了cherry-studio，~~

![image](https://github.com/user-attachments/assets/2dd81368-356a-4c52-bb7a-c51b66e2a7cf)

~~任务管理器进程，就只有这个，关了，整个都关了包括更新弹窗~~

![Uploading image.png…]()

### Steps To Reproduce

更新即可触发

### Expected Behavior

更新即可触发

**Comment by kangfenmao** [comment]
能解决问题了吗

**Comment by elfcute** [comment]
> 能解决问题了吗

佬 解决了 删除这个issue吧，我没有权限删除

**Comment by elfcute** [comment]
> 能解决问题了吗

不过有另外一个问题就是文本dav备份逻辑的问题，有时候如果你输出webdav或者是无效的，就会一直卡着，所以能不能增加超时限制，或者是手动停止备份
![image](https://github.com/user-attachments/assets/5ff834e6-aef4-40a7-94cc-87fb758646ce)

**Comment by walk1ng** [comment]
> > 能解决问题了吗
> 
> 佬 解决了 删除这个issue吧，我没有权限删除

请问是如何解决更新问题的？

**Comment by kangfenmao** [comment]
任务管理器搜索 Cherry 右键结束进程
