### ISSUE TITLE
[错误]: 微信输入法“符号自动配对”功能会新建话题

### ISSUE THREAD

**Issue by czz404** [kangfenmao/cherry-studio#412]
### 平台

Windows

### 版本

v0.8.23

### 错误描述

微信输入法-设置-输入-符号自动配对打开，输入左括号，此时自动补全左右括号并新建了一个话题
关闭符号自动配对则正常
在Cherrystudio里把快捷方式里面所有快捷键都关闭也没有用

### 重现步骤

微信输入法-设置-输入-符号自动配对打开
打开Cherrystudio-切换输入法为中文-shift+9输入左括号
此时自动补全左右括号并新建了一个话题

### 预期行为

不触发新建话题

**Comment by kangfenmao** [comment]
更新新版本，然后把新建话题快捷键重置成默认的，看看能否解决问题

**Comment by czz404** [comment]
> 更新新版本，然后把新建话题快捷键重置成默认的，看看能否解决问题

hhh很神奇，点一下重置快捷键就解决了，可我之前好像也没改过快捷键，只是把开关都关掉了
