### ISSUE TITLE
[功能]: 希望能添加的字体大小修改功能

### ISSUE THREAD

**Issue by huantingdream** [kangfenmao/cherry-studio#414]
### 您的功能建议是否与某个问题相关?

天天盯着电脑屏幕上班，笔记本屏幕比较小，加上字体一小有点难受🥲

### 请描述您希望实现的解决方案

能在设置里添加个字体调节功能

**Comment by kangfenmao** [comment]
有两个办法可以实现

1. 设置面板可以修改字体大小
2. 使用快捷键全局缩放界面，具体参考设置 - 快捷键

如果还有其他疑问可以在下方留言
