### ISSUE TITLE
[功能]jsp代码直接就给我显示效果，有时候想看源代码却只能复制查看，很麻烦

### ISSUE THREAD

**Issue by reflect3** [kangfenmao/cherry-studio#419]
### 您的功能建议是否与某个问题相关?

- 不仅jsp,还有svg，都是直接显示效果，有时候查看源码挺不方便的
- 输出svg的时候不显示效果，直接就白了，重新让他输出几遍了都是这样

### 请描述您希望实现的解决方案

![image](https://github.com/user-attachments/assets/e2da8c39-1e66-4338-bcc2-b45c34215ecb)

![image](https://github.com/user-attachments/assets/867c8ac8-641f-479c-a2aa-ee5c8ad04f61)

### 请描述您考虑过的其他方案

能否出一个跟HTML一样的，可以点击预览的，或者点击查看源码按钮

**Comment by kangfenmao** [comment]
> ### 您的功能建议是否与某个问题相关?
> 
> - 不仅jsp,还有svg，都是直接显示效果，有时候查看源码挺不方便的
> 
> - 输出svg的时候不显示效果，直接就白了，重新让他输出几遍了都是这样
> 
> 
> 
> ### 请描述您希望实现的解决方案
> 
> ![image](https://github.com/user-attachments/assets/e2da8c39-1e66-4338-bcc2-b45c34215ecb)
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/867c8ac8-641f-479c-a2aa-ee5c8ad04f61)
> 
> 
> 
> ### 请描述您考虑过的其他方案
> 
> 能否出一个跟HTML一样的，可以点击预览的，或者点击查看源码按钮
> 
> ### 其他补充信息
> 
> _No response_

粘贴一下回复内容吧

**Comment by reflect3** [comment]
回复内容：

好的,让我们详细讲解一下 <jsp:useBean> 标签的使用。

<jsp:useBean> 是 JSP 的一个动作标签,用于在 JSP 页面中声明和初始化 JavaBean。它的主要作用是简化 JavaBean 的使用,使得在 JSP 中操作 JavaBean 变得更加方便。

### 基本语法

```jsp
<jsp:useBean id="beanName" class="package.class" scope="page|request|session|application" />
```

参数说明:
- id: Bean 的唯一标识符,用于在 JSP 页面中引用该 Bean。
- class: Bean 的完整类名。
- scope: Bean 的作用域,可以是 page、request、session 或 application。

### 使用示例

1. 基本使用:

```jsp
<jsp:useBean id="user" class="com.example.User" scope="request" />
```

这行代码会创建一个 com.example.User 类的实例,并将其存储在 request 作用域中,以 "user" 为名。

2. 带有属性设置的使用:

```jsp
<jsp:useBean id="user" class="com.example.User" scope="request">
    <jsp:setProperty name="user" property="name" value="Alice" />
    <jsp:setProperty name="user" property="age" value="25" />
</jsp:useBean>
```

这个例子不仅创建了 User 对象,还设置了它的 name 和 age 属性。

3. 使用 type 属性:

```jsp
<jsp:useBean id="users" scope="request" type="java.util.List<com.example.User>" />
```

这里使用 type 属性指定了 Bean 的类型,而不是 class。这通常用于已经在 Servlet 中创建并设置到 request 属性中的对象。

### 注意事项

1. 如果指定的 Bean 已经存在于给定的作用域中,<jsp:useBean> 会直接使用现有的 Bean,而不是创建新的。

2. 使用 type 属性时,如果指定的对象不存在,会抛出异常。所以使用 type 时,通常需要确保对象已经在 Servlet 中创建并设置。

3. 在使用 <jsp:useBean> 后,可以直接在 JSP 中使用 EL 表达式或 scriptlet 来访问 Bean 的属性。

4. 作用域的选择很重要:
   - page: 只在当前页面有效
   - request: 在当前请求中有效
   - session: 在用户会话期间有效
   - application: 在整个应用程序生命周期内有效

### 最佳实践

1. 尽量使用 EL 表达式来访问 Bean 的属性,而不是 scriptlet。
2. 合理选择 Bean 的作用域,避免不必要的资源消耗。
3. 在复杂的业务逻辑中,最好在 Servlet 中创建和初始化 Bean,然后在 JSP 中使用 type 属性来引用。

通过正确使用 <jsp:useBean>,可以有效地分离业务逻辑和表现层,提高代码的可维护性和可读性。

更多详细信息,可以参考 JavaEE 官方文档:
https://docs.oracle.com/javaee/5/tutorial/doc/bnajb.html

答案已验证

**Comment by reflect3** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<svg width="400" height="600" xmlns="http://www.w3.org/2000/svg">
    
    <defs>
        <pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse">
            <path d="M 20 0 L 0 0 0 20" fill="none" stroke="#f0f0f0" stroke-width="0.5"/>
        </pattern>
    </defs>
    <rect width="400" height="600" fill="#fff"/>
    <rect width="400" height="600" fill="url(#grid)" opacity="0.3"/>

    
    <rect x="20" y="20" width="360" height="560" fill="#fff" stroke="#eee" stroke-width="1"/>

    
    <line x1="40" y1="90" x2="360" y2="90" stroke="#333" stroke-width="0.5" stroke-dasharray="1,3"/>
  
    
    <text x="200" y="60" font-family="楷体" font-size="28" fill="#333" text-anchor="middle">汉语新解</text>
  
    
    <text x="200" y="120" font-family="sans-serif" font-size="18" fill="#555" text-anchor="middle">程序员</text>
    <text x="200" y="145" font-family="sans-serif" font-size="14" fill="#888" text-anchor="middle">[Programmer] [プログラマー]</text>

    
    <text x="50" y="200" font-family="宋体" font-size="16" fill="#444">
        <tspan x="50" dy="0">一群被困在二进制牢笼里的现代僧侣,</tspan>
        <tspan x="50" dy="25">日夜吟诵着看不见的咒语,</tspan>
        <tspan x="50" dy="25">用逻辑编织梦想,</tspan>
        <tspan x="50" dy="25">却常常难以对话现实。</tspan>
        <tspan x="50" dy="35"></tspan>
        <tspan x="50" dy="25">他们把生命编译成代码,</tspan>
        <tspan x="50" dy="25">却解析不出自己的未来,</tspan>
        <tspan x="50" dy="25">用算法优化世界,</tspan>
        <tspan x="50" dy="25">却无法计算加班的终点。</tspan>
        <tspan x="50" dy="35"></tspan>
        <tspan x="50" dy="25">像一群永远处于 DEBUG 模式的生物,</tspan>
        <tspan x="50" dy="25">在光怪陆离的赛博世界里,</tspan>
        <tspan x="50" dy="25">寻找着那个完美的分号。</tspan>
    </text>

    
    <line x1="40" y1="500" x2="360" y2="500" stroke="#333" stroke-width="0.5" stroke-dasharray="1,3"/>

    
    <text x="200" y="540" font-family="黑体" font-size="16" fill="#666" text-anchor="middle">
        现代社会的二进制苦行僧
    </text>

    
    <circle cx="40" cy="40" r="8" fill="none" stroke="#888" stroke-width="0.5"/>
    <circle cx="360" cy="40" r="8" fill="none" stroke="#888" stroke-width="0.5"/>
    <circle cx="40" cy="560" r="8" fill="none" stroke="#888" stroke-width="0.5"/>
    <circle cx="360" cy="560" r="8" fill="none" stroke="#888" stroke-width="0.5"/>
</svg>

**Comment by kangfenmao** [comment]
已修复，等版本更新
