### ISSUE TITLE
调试提示词不方便，需要点击很多下，能否修改用户界面或交互逻辑。

### ISSUE THREAD

**Issue by corwin1949** [kangfenmao/cherry-studio#42]
比如，1. 我点击对话中最上面的提示词就能直接编辑提示词。

或者 2. 右边设置菜单加一个修改提示词的文本框，点击就能修改。
要是设置页面放不下，也可以单独开个和设置同级的页面，专门写提示词。

我感觉现在右边设置的内容，其实一般都不太会修改，最多改一两次。
但是提示词是会经常迭代修改的，更频繁。

**Comment by kangfenmao** [comment]
感谢提出反馈意见

最直接的编辑方式就是点击标题进行编辑，我在下个版本增加这个功能，可以快速点击标题进行编辑。如果有什么想法，可以在下面留言告诉我。

<img width="934" alt="image" src="https://github.com/user-attachments/assets/b93fdb73-d7e4-43b3-9c00-2e3882b8f544">

**Comment by kangfenmao** [comment]
已经开发完成，等待下个版本发布

**Comment by corwin1949** [comment]
> 已经开发完成，等待下个版本发布

感谢，你的反馈总是这么快！
