### ISSUE TITLE
[错误]: 连接Gemini中转api总是失败 

### ISSUE THREAD

**Issue by Jayden-Pr** [kangfenmao/cherry-studio#420]
### 平台

Windows

### 版本

0.8.23

### 错误描述

连接中转api失败 api地址为https://yunwu.ai 在网页端使用正常，在软件内就提示“出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥”，但是我配置了

### 重现步骤

{
  "status": 404,
  "statusText": ""
}

### 预期行为

期望正常输入输出内容

### 相关日志输出

```shell
{
  "status": 404,
  "statusText": ""
}
```

**Comment by ZzzzRyan** [comment]
建议提供服务配置截图、操作步骤以供分析问题。

**Comment by Diomchen** [comment]
我也遇到了同样的问题，gemini 代理地址和API key 都在我自己搭建的平台上通过了，但是 cherry-studio 则会出现连接失败
![image](https://github.com/user-attachments/assets/934d0595-ce60-472b-9b7c-15a172f273eb)

**Comment by ZzzzRyan** [comment]
> 我也遇到了同样的问题，gemini 代理地址和API key 都在我自己搭建的平台上通过了，但是 cherry-studio 则会出现连接失败

你的 Gemini 代理支持使用 Gemini 请求格式请求吗？大部分第三方代理一般只支持使用 OpenAI 格式请求，据我目前了解，还没有看到支持 Gemini 格式的转接站。

**Comment by Diomchen** [comment]
> > 我也遇到了同样的问题，gemini 代理地址和API key 都在我自己搭建的平台上通过了，但是 cherry-studio 则会出现连接失败
> 
> 你的 Gemini 代理支持使用 Gemini 请求格式请求吗？大部分第三方代理一般只支持使用 OpenAI 格式请求，据我目前了解，还没有看到支持 Gemini 格式的转接站。

支持的，我这个是自己弄的，原理是通过 cloudflare 代理了 gemini api。所以请求格式应该是和原生的 gemini 是一样的。

**Comment by ZzzzRyan** [comment]
> 支持的，我这个是自己弄的，原理是通过 cloudflare 代理了 gemini api。所以请求格式应该是和原生的 gemini 是一样的。

我这边接的是 Gemini 官方的 API，目前可以正常使用。

![image](https://github.com/user-attachments/assets/d6be87f8-ef7e-433e-88c9-a1bdd7b6e64c)

我能想到的原因还有两个：

1. 因为检查连接是否成功的原理是使用下面模型列表的第一个模型进行一次请求，所以得确保支持那一个模型；
2. 代理设置

如果还是无法解决的话等作者来看看👀。

**Comment by Diomchen** [comment]
> > 支持的，我这个是自己弄的，原理是通过 cloudflare 代理了 gemini api。所以请求格式应该是和原生的 gemini 是一样的。
> 
> 我这边接的是 Gemini 官方的 API，目前可以正常使用。
> 
> ![image](https://private-user-images.githubusercontent.com/107601663/393720888-d6be87f8-ef7e-433e-88c9-a1bdd7b6e64c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MjUyNjYsIm5iZiI6MTczMzcyNDk2NiwicGF0aCI6Ii8xMDc2MDE2NjMvMzkzNzIwODg4LWQ2YmU4N2Y4LWVmN2UtNDMzZS04OGM5LWExYmRkN2I2ZTY0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQwNjE2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWIwYWY3ZjZhZDcwNGNjNGYxOGYzZGI1M2U2YjNlMzBjODE0Yjk4Y2MyYTZmNDEzMzA0NGUyOTRjNzJhYzVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oChJnkBh-5cyWnx2vkd51lZ54zbFfJXilfKXMKZAvHE)
> 
> 我能想到的原因还有两个：
> 
> 1. 因为检查连接是否成功的原理是使用下面模型列表的第一个模型进行一次请求，所以得确保支持那一个模型；
> 2. 代理设置
> 
> 如果还是无法解决的话等作者来看看👀。

我刚刚试了手动添加模型，还是不大行，不过还是谢谢你的回复！♥️

**Comment by kangfenmao** [comment]
不要填在 Gemini 那里，这样的做法是错误的！

手动新建一个服务商，输入 云雾，格式选择 OpenAI

![image](https://github.com/user-attachments/assets/848bb68b-0cf2-4ff1-96d3-220a4fededbe)

@Jayden-Pr

**Comment by kangfenmao** [comment]
@Jayden-Pr 是否解决问题？

**Comment by SteveShufan** [comment]
> [@Jayden-Pr](https://github.com/Jayden-Pr) 是否解决问题？
按照这个方式还是不行，出现如下错误(未挂梯)
