### ISSUE TITLE
[错误]: Groq 请求失败

### ISSUE THREAD

**Issue by hadis898** [kangfenmao/cherry-studio#425]
### 平台

Windows

### 版本

v1.0

### 错误描述

1：获取 API
访问https://console.groq.com
完成注册并申请 API

2：兼容OpenAI接口方式
API地址：https://api.groq.com/openai/
模型名称：llama-3.3-70b-versatile

3：主要优势
响应速度：200 Token/秒
性能表现：接近 GPT-4.0 水平
完全免费使用

4：使用限制
每分钟限额：6000 Token
每日 API 调用：14000 次
足够普通用户日常使用

我用这个申请到api后，链接检测都成功的，使用时候却显示"status": 400, 不行

### 重现步骤

如上

### 预期行为

如上

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/1e4d9ff2-f86f-4744-8a05-d572affa545d)
![image](https://github.com/user-attachments/assets/4eeac050-1098-4076-9926-b220e902fa4e)


如同所示，按照我这个配置，看看结果

**Comment by kangfenmao** [comment]
我注意到有些模型我也不能访问，所以我只配置了 Llama3 70b，另外我在代理规则中绕过了墙

![image](https://github.com/user-attachments/assets/fa3ce0e3-ff68-452f-8edb-8b2ef1e84a9a)

**Comment by kangfenmao** [comment]
@hadis898 是否解决了问题？

**Comment by Huaweidev** [comment]
> [@hadis898](https://github.com/hadis898) 是否解决了问题？

遇到了完全相同的问题，常规设置后检测报错如下：
`message": "404 Not Found", "status": 404,"requestID":null, "error":f"message": "Not Found"}}`

系统环境：
---
操作系统版本：Windows 11 24H2
Cherry Studio版本：v1.5.5 Windows
代理信息：“非被Groq屏蔽地区的代理”

Clash Verge Rev设置：
---
设置 - 端口设置 - 开启“HTTP(S)代理端口 7899”

Cherry Studio设置：
---
常规设置 - 代理地址：“http://127.0.0.1:7899”
模型服务 - Groq - API地址：“https://api.groq.com/openai”

参考资料：
Groq官方屏蔽IP地址说明：https://community.groq.com/discussion-forum-7/groq-api-always-returns-404-219
Cherry Studio调用Groq API报错404：https://linux.do/t/topic/806041/11
claude-code-router + groq 请求一直失败：看https://linux.do/t/topic/834739/5

<img width="587" height="599" alt="Image" src="https://github.com/user-attachments/assets/acd5a8a6-8822-4145-8484-8f7506bb0ce5" />
