### ISSUE TITLE
[功能]: 清除上下文按钮容易误点

### ISSUE THREAD

**Issue by uvmd** [kangfenmao/cherry-studio#426]
### 您的功能建议是否与某个问题相关?

清除上下文按钮容易误点，建议不要。本来就可以另开话题。

### 请描述您希望实现的解决方案

清除上下文按钮容易误点，建议不要。本来就可以另开话题。

**Comment by uvmd** [comment]
或者增加一个选项让用户决定是否有这个按钮

**Comment by kangfenmao** [comment]
隐藏掉吧

**Comment by ZzzzRyan** [comment]
但它不是还会弹出一个确认的对话框吗？误点了按钮然后又连续误点了确认？🤔

**Comment by kindmesdilabso** [comment]
> 隐藏掉吧

本来想上来也提这个issues的
想问能否增加一个撤销刚清除的上下文的
其实也没必要隐藏
我发现再点一次清除上下文就撤销了
或者考虑把没有输入内容的输入框高度配置成可以自己调节高度的形式
并记忆高度
感觉现在没有输入内容的输入框高度有点小,容易点到下面的一些按钮

**Comment by kindmesdilabso** [comment]
> ~但它不是还会弹出一个确认的对话框吗？连续误点了确认？🤔~
> 
> 非常抱歉，my fault，我误以为是 “清空消息” 按钮了，原来是清除上下文🥲。
> 
> 我觉得或许可以改成可撤销的形式？像 NextChat 那样，点击一下清除的分界线就撤销清除。

那个清除上下文的按钮还能再点一次来撤销

**Comment by ZzzzRyan** [comment]
> 那个清除上下文的按钮还能再点一次来撤销

感谢🙏，才知道还有这个功能！

**Comment by kindmesdilabso** [comment]
> > 那个清除上下文的按钮还能再点一次来撤销
> 
> 感谢🙏，才知道还有这个功能！

我也是刚准备发issues才发现有这个

**Comment by kangfenmao** [comment]
自定义输入框高度，和自适应高度冲突，只能选一种

**Comment by kindmesdilabso** [comment]
> 自定义输入框高度，和自适应高度冲突，只能选一种

那默认的初始高度可以适当的再调高一点吗?使用上偶尔是会感觉有点不太容易点中还未输入内容的发送框

**Comment by kangfenmao** [comment]
> > 自定义输入框高度，和自适应高度冲突，只能选一种
> 
> 那默认的初始高度可以适当的再调高一点吗?使用上偶尔是会感觉有点不太容易点中还未输入内容的发送框

可以

**Comment by kindmesdilabso** [comment]
> > > 自定义输入框高度，和自适应高度冲突，只能选一种
> > 
> > 
> > 那默认的初始高度可以适当的再调高一点吗?使用上偶尔是会感觉有点不太容易点中还未输入内容的发送框
> 
> 可以

非常感谢

**Comment by kangfenmao** [comment]
1. 增加了大屏幕输入框默认高度
2. 清除上下文的消息点击可以撤回

下个版本发布
