### ISSUE TITLE
[功能]: 增加滚动条的大小

### ISSUE THREAD

**Issue by jiushime** [kangfenmao/cherry-studio#427]
### 您的功能建议是否与某个问题相关?

我是win10系统

滚动条太细拖动的时候不太容易选中
![PixPin_2024-12-09_20-33-36](https://github.com/user-attachments/assets/d75318d4-b9b7-41ac-928c-e8fff949fa00)
![PixPin_2024-12-09_20-53-53](https://github.com/user-attachments/assets/cd92df0f-cdf6-4891-b212-bee32f8f7804)

### 请描述您希望实现的解决方案

把滚动条加大加宽一些

**Comment by kangfenmao** [comment]
可以加宽一些
