### ISSUE TITLE
[功能]: 界面字体大小设置支持全局设置，而不仅仅是编辑对话的区域，还包括其他界面部分，或者单独拆分出来一个设置 IDE 界面字体的输入框

### ISSUE THREAD

**Issue by HahaCodeLife** [kangfenmao/cherry-studio#429]
### 您的功能建议是否与某个问题相关?

如题

### 请描述您希望实现的解决方案

如题

**Comment by ZzzzRyan** [comment]
UI 整体字体大小比较建议直接调整电脑 DPI，因为看起来 Cherry-Studio 的 UI 字体大小和 Explorer 的字体大小是相差无几的，如果感觉 Cherry 界面字体小，那么其他软件的应该也差不太多。

**Comment by HahaCodeLife** [comment]
我知道想说的或者想表达的是什么，类似于 Windows 和 Mac 

但是这里面有一个问题：
01）系统层面的设置是整体的全局的
02）应用层面的设置是应用层级的
03）应用层面的部分区域的设置是应用层面的部分与部分之间的关系

类似于当我使用 jetbrains 系列 IDE 软件默认给 资源管理器 大小一致的字体的时候我是通过设置 IDEA 中的编辑器编辑区域的字号来更改还是通过修改系统设置中的文本缩放来更改

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/34b18f79-d208-4e6d-a3b9-7b8e1faa77a9)

**Comment by HahaCodeLife** [comment]
这就是我要的效果
