### ISSUE TITLE
能否增加一个清除 Context 的功能，不希望清除上面的聊天记录

### ISSUE THREAD

**Issue by yangg** [kangfenmao/cherry-studio#43]
1. 有时候不想带context干扰问题，清除掉后想看之前的又看不到了
2. 不需要带context时也可以节省 token
3. 如果觉得没位置，也可以放在现在的清除上加个长按

**Comment by kangfenmao** [comment]
你的意思是临时增加一个选项，这个选项打开的时候不带任何 context，这个选项关闭的时候就带上 context。我的理解对吗？ @yangg

**Comment by yangg** [comment]
不完全对：
我的意思是
清空Context按钮：会将前面的消息标记为已清除，有了这个标记的消息就不会被context计算及包含在请求中，但是界面上不删除。
后续还是会带context,不想带就再点一下，当然也可以多做一个选项变成你这种一直不带context的。

**Comment by kangfenmao** [comment]
<img width="1398" alt="image" src="https://github.com/user-attachments/assets/04df7034-a271-49f1-b763-b80c3f2c955d">

@yangg 来看一下是不是这样的

**Comment by yangg** [comment]
是的，速度啊

**Comment by yangg** [comment]
你这咋调试的，不得搞个 langchain smith 配置的地方

**Comment by kangfenmao** [comment]
下午发版本带上这个功能，这样我们就可以精确控制发送的上下文内容了，从 token 数量统计上也能看到要发送的 token 没有了

**Comment by kangfenmao** [comment]
更新到新版本 https://github.com/kangfenmao/cherry-studio/releases/tag/v0.6.8
