### ISSUE TITLE
[错误]: 公式渲染有问题

### ISSUE THREAD

**Issue by CatechumenLee** [kangfenmao/cherry-studio#434]
### 平台

Windows

### 版本

v0.8.23

### 错误描述

公式渲染重叠的问题

### 重现步骤

问gpt这个问题“1个t的数据 20MB/S多长时间传完”，会出现公式渲染重叠的问题。
![wechat_2024-12-10_133014_901](https://github.com/user-attachments/assets/43830385-caa7-4fec-b275-c966631c5023)

### 预期行为

正常输出公式。

**Comment by kangfenmao** [comment]
设置里面切换公式引擎

![image](https://github.com/user-attachments/assets/4a6bbba0-4110-4458-a8e4-27269f03b4c7)
