### ISSUE TITLE
[功能]: O1模型支持流式输出

### ISSUE THREAD

**Issue by ZzzzRyan** [kangfenmao/cherry-studio#439]
### 您的功能建议是否与某个问题相关?

当前，OpenAI 的 O1 模型已经支持流式输出，但软件里还是会强制将其设置为非流式，较为影响使用体验。

### 请描述您希望实现的解决方案

希望取消 O1 模型的强制非流式输出，回归用户控制。

### 请描述您考虑过的其他方案

无

### 其他补充信息

无

**Comment by kangfenmao** [comment]
OK

**Comment by kangfenmao** [comment]
已修复，下个版本上线

**Comment by blacksev** [comment]
现在o1 又不支持 stream 了，看了最新的代码是被限制了，还能改回来吗？

@kangfenmao
