### ISSUE TITLE
中文输入法回车会导致发送

### ISSUE THREAD

**Issue by yangg** [kangfenmao/cherry-studio#44]
本来输入法回车是英文上屏的

这里有个解决方案
https://www.zhangxinxu.com/wordpress/2023/02/js-enter-submit-compositionupdate/

**Comment by kangfenmao** [comment]
哈哈哈，自带解决方案啊，我测试他给的第一个方法有效，下个版本上

**Comment by yangg** [comment]
其实表单最适合的还是应该 form。
如果要用 js 事件的话，最下面的 `event.isComposing` 比较符合语义

**Comment by kangfenmao** [comment]
更新到新版本 https://github.com/kangfenmao/cherry-studio/releases/tag/v0.6.8
