### ISSUE TITLE
[功能]: 要是能出安卓端就好了，或者说目前的项目能部署到安卓吗？

### ISSUE THREAD

**Issue by lioensky** [kangfenmao/cherry-studio#441]
### 您的功能建议是否与某个问题相关?

希望有安卓端

### 请描述您希望实现的解决方案

希望有安卓端

**Comment by scu-lixiao** [comment]
能支持iPhone,iPad 更好。

**Comment by kangfenmao** [comment]
还没有开发，移动端都会在明年支持

**Comment by wenbochang888** [comment]
> 还没有开发，移动端都会在明年支持

@kangfenmao 具体有什么计划么，比如几月几号？其他的客户端感觉不怎么好用

**Comment by kangfenmao** [comment]
> > 还没有开发，移动端都会在明年支持
> 
> @kangfenmao 具体有什么计划么，比如几月几号？其他的客户端感觉不怎么好用

几月几号，我现在也不好说

**Comment by freezefire** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

It's 2026, has it been put on the schedule?

---
<details>
<summary>Original Content</summary>

2026年了，提上日程了吗？
</details>
