### ISSUE TITLE
[功能]: 请问能否支持gemini grounding功能？

### ISSUE THREAD

**Issue by lokiter** [kangfenmao/cherry-studio#442]
### 您的功能建议是否与某个问题相关?

您好，google studio中gemini1.5 pro/flash、gemini 2.0 exp模型可以开启grounding选项实时搜索，希望可以支持这一选项。
文档介绍链接：
https://ai.google.dev/gemini-api/docs/grounding?hl=zh-cn&lang=python

效果：
![图片](https://github.com/user-attachments/assets/738fd63b-9781-476c-b317-b9f8497f0663)

### 请描述您希望实现的解决方案

希望增加一个实时搜索按钮，当用户使用支持的模型且仅使用文本对话时可以打开。

**Comment by kangfenmao** [comment]
我看了这个，我还在考虑接入这个，还是未来用 Cherry 内置的联网来做。

目前这个开启需要绑定支付方式，大概一次搜索的价格在 ¥0.25，差不多1块钱可以做4次搜索

**Comment by kangfenmao** [comment]
已经集成好了，下午发

**Comment by kangfenmao** [comment]
https://github.com/kangfenmao/cherry-studio/releases/tag/v0.8.25
