### ISSUE TITLE
[错误]: 更新之后，之前设置的模型服务无法正常回复

### ISSUE THREAD

**Issue by WanderInTree** [kangfenmao/cherry-studio#445]
### 平台

Windows

### 版本

v0.8.24

### 错误描述

更新之后，之前设置的模型服务无法正常回复，但是在设置界面，检查均为正常链接。我在其他ai框架中使用相应apikey，可以正常回复。

### 重现步骤

![image](https://github.com/user-attachments/assets/9f1c07e0-8d70-4bb3-add8-b883b6678d42)
![image](https://github.com/user-attachments/assets/0fcd5e9c-05fb-4bee-97bb-f46b484502d9)
![image](https://github.com/user-attachments/assets/995a4f27-fd96-4d3b-881a-b1c07be732c5)
![image](https://github.com/user-attachments/assets/d1163bfc-8bf5-4fcd-84e0-66be5d7928a1)
![image](https://github.com/user-attachments/assets/746398a4-30fd-46af-a08c-9bd1c0e64a17)

### 预期行为

我设置好apikey之后，在对话框应能正常回复，但是均未正常回复

**Comment by Femoon** [comment]
一样的问题

<img width="813" alt="image" src="https://github.com/user-attachments/assets/8e753a53-a510-4fa2-8230-7812a64d79e4" />

**Comment by kangfenmao** [comment]
这个问题看起来很奇怪，添加我的微信详细看看吧 

微信：kangfenamo

**Comment by kangfenmao** [comment]
> 更新后丢失了所有配置，填入 Key 测试通过，openRouter 一样请求报错
> 
> <img alt="image" width="813" src="https://private-user-images.githubusercontent.com/23479787/395074844-8e753a53-a510-4fa2-8230-7812a64d79e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTY0NTUsIm5iZiI6MTczMzk5NjE1NSwicGF0aCI6Ii8yMzQ3OTc4Ny8zOTUwNzQ4NDQtOGU3NTNhNTMtYTUxMC00ZmEyLTgyMzAtNzgxMmE2NGQ3OWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA5MzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ODY0MTM0NWE4OTVlYTkzM2MwZDUyNjgwNDAxZDUwZDk1NGI3MjUwNmZjNjJiNjVlNjcyNzkxMjVlZmRiZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wae5gjoxo-5tvbiaoovx-lsjyGCUdqkKd0hUAOnwe6c">

你这个更严重，也加我微信帮你看一下吧

**Comment by Femoon** [comment]
> > 更新后丢失了所有配置，填入 Key 测试通过，openRouter 一样请求报错
> 
> > 
> 
> > <img alt="image" width="813" src="https://private-user-images.githubusercontent.com/23479787/395074844-8e753a53-a510-4fa2-8230-7812a64d79e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTY0NTUsIm5iZiI6MTczMzk5NjE1NSwicGF0aCI6Ii8yMzQ3OTc4Ny8zOTUwNzQ4NDQtOGU3NTNhNTMtYTUxMC00ZmEyLTgyMzAtNzgxMmE2NGQ3OWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDA5MzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ODY0MTM0NWE4OTVlYTkzM2MwZDUyNjgwNDAxZDUwZDk1NGI3MjUwNmZjNjJiNjVlNjcyNzkxMjVlZmRiZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wae5gjoxo-5tvbiaoovx-lsjyGCUdqkKd0hUAOnwe6c">
> 
> 
> 
> 你这个更严重，也加我微信帮你看一下吧

配置是找不回了，重新配置后覆盖了版本没法复现。报错的问题找到了解决方法是新建一个会话窗，新建的会话窗功能正常，然后再将有问题的会话窗删除

**Comment by kangfenmao** [comment]
升级问题我已经修复了，后续我会自行测试一下升级

**Comment by okayshare** [comment]
最新0.96版本，openrouter api 连接检查正常， chat 中 Phi-3 Medium 128K Instruct  正常回复。其他的 Google: Gemini Flash 2.0 Experimental (free) 等，Meta: Llama 3.1 405B Instruct (free) 等 都是下面的代码错误  

 {
  "error": {
    "message": "Provider returned error",
    "code": 429,
    "metadata": {
      "raw": {
        "__kind": "OK",
        "data": "{\"error\":{\"code\":null,\"message\":\"Rate limit exceeded\",\"param\":null,\"type\":\"rate_limit_exceeded\"}}\n"
      },
      "provider_name": "SambaNova"
    }
  },
  "code": 429
}
请修正下，谢谢
