### ISSUE TITLE
[错误]: 输出不显示 markdown 的小圆点

### ISSUE THREAD

**Issue by huangzhenhao90** [kangfenmao/cherry-studio#446]
### 平台

macOS

### 版本

0.8.25

### 错误描述

![image](https://github.com/user-attachments/assets/d88f0740-3f0b-4380-99ab-52d9228d89dd)
如图所示，不显示 markdown 的小圆点，不知道是不是哪里设置的不对呢

### 重现步骤

就是常规的每个输出

### 预期行为

预期以 markdown 小圆点展示

**Comment by kangfenmao** [comment]
已修复，下个版本发布

**Comment by huangzhenhao90** [comment]
> 已修复，下个版本发布

nb，真快，感谢！！
