### ISSUE TITLE
[功能]: 苹果系列的开发者账户和证书

### ISSUE THREAD

**Issue by leipengic** [kangfenmao/cherry-studio#449]
### 您的功能建议是否与某个问题相关?

尊敬的开发者，请问您有苹果系列开发者账户开发吗？还是说安装之后需要进行自签证书信任啊？

### 请描述您希望实现的解决方案

开发者账户

**Comment by kangfenmao** [comment]
不能正常安装吗，软件是有证书和公证的

**Comment by kangfenmao** [comment]
遇到什么问题了吗
