### ISSUE TITLE
自己发送的文本没有解析markdown吗？

### ISSUE THREAD

**Issue by yangg** [kangfenmao/cherry-studio#45]
经常需要发送一些代码段，会用markdown ``` 括起来，这样更明确，或者一些  \`combined word\`，但是现在发送的文本貌似没有代码块的样式

比如：

优化这段代码
\```
getProjectInfo(company_code).then((projectRes) => {
      const urls = getAppConfig()
      userData.loginUrl = urls.loginApiUrl
      dispatch(handleLogin(userData))
      setLoading(false)
    })
\```

**Comment by kangfenmao** [comment]
看来是有这个问题，需要加语言名字才能解析 ```language，下个版本优化一下

**Comment by kangfenmao** [comment]
更新到新版本 https://github.com/kangfenmao/cherry-studio/releases/tag/v0.6.8
