### ISSUE TITLE
[问题]: Gemini 2.0 联网功能使用报错。

### ISSUE THREAD

**Issue by wjl697** [kangfenmao/cherry-studio#452]
### 您的问题

![PixPin_2024-12-13_01-11-54](https://github.com/user-attachments/assets/f0a2ac94-0f00-43ca-b522-abc3bb1e607e)
![PixPin_2024-12-13_01-12-23](https://github.com/user-attachments/assets/32fcb706-78a7-4437-9745-96c68def7d7e)

### 相关背景

平台：win
版本：0.8.25

### 优先级

低 (有空再看)

**Comment by lioensky** [comment]
flash每天联网次数是有限的，你的额度用完了。

**Comment by huameiwei-vc** [comment]
我也是，但是我第一次使用，不可能额度用完啊

**Comment by kangfenmao** [comment]
https://aistudio.google.com/apikey

![image](https://github.com/user-attachments/assets/dd839fff-dbe2-4742-9c5a-b9d98855cded)

**Comment by kangfenmao** [comment]
需要绑定付费账号后使用
