### ISSUE TITLE
[错误]: v0.8.25 新建助手，软件白屏

### ISSUE THREAD

**Issue by magickzl** [kangfenmao/cherry-studio#453]
### 平台

Windows

### 版本

v0.8.25

### 错误描述

最新版本 新建助手，软件立刻白屏。
完全退出软件后，重新打开才恢复，应该是重启后软件自动定位到第一个助手才恢复的。
这时只要点击那个新建的助手，马上会再次白屏。

### 重现步骤

1. 新建助手
2. 软件白屏
3. 重启恢复
4. 再次点击
5. 立刻白屏

### 预期行为

新建助手，软件立刻白屏。

**Comment by kangfenmao** [comment]
用快捷键 Ctrl + Shift + I 调出控制台看看有没有什么错误

**Comment by magickzl** [comment]
![Uploading PixPin_2024-12-13_10-11-51.png…]()

**Comment by magickzl** [comment]
![Alt text](https://file.uhsea.com/2412/b172bdbfd01e5e407de35bee655f7a57S2.png)

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/75c6f197-7d9f-423a-ab49-3a35e4b92737)

选一下这个试试

**Comment by magickzl** [comment]
这里任意选一个模型后确实正常了。

**Comment by kangfenmao** [comment]
> 这里任意选一个模型后确实正常了。

感谢发现这个问题，我已经修了
