### ISSUE TITLE
[问题]: 未设置默认对话模型之后导致无法启动

### ISSUE THREAD

**Issue by DFobain** [kangfenmao/cherry-studio#455]
### 您的问题

版本：V0.8.25
对设置默认对话模型之后删除了对应模型 导致无法启动
在目前无法启动的情况下 我应该如何恢复默认模型的配置
![图片](https://github.com/user-attachments/assets/e89a7c10-04bf-491d-b910-89083c8c8839)

### 优先级

高 (阻碍工作进行)

**Comment by DFobain** [comment]
已解决，安装旧版本完成设置，设置完成后升级。

**Comment by kangfenmao** [comment]
这是个 bug, 我马上就修掉
