### ISSUE TITLE
[功能]: 4-mini-支持的Function Calling什么时候可以支持

### ISSUE THREAD

**Issue by smith-chow** [kangfenmao/cherry-studio#456]
### 您的功能建议是否与某个问题相关?

之前在别的软件中有插件，可以让4o-mini 联网  duckduckgo插件还有其他插件 

### 请描述您希望实现的解决方案

现在没有找到插件和联网按钮，请问如何实现，插件和联网功能，或者自定义自己添加

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the AppsPage component to include a new section for plugins and add an internet connectivity toggle. Update the minapps configuration to include plugin support.

You can review changes in this commit: https://github.com/kkpo4553/kangfenmao-cherry-studio-456/commit/2c4cd7eb03acafd816834c997db57756b2bf00b0.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
