### ISSUE TITLE
[功能]: 附件可删改

### ISSUE THREAD

**Issue by Masque423** [kangfenmao/cherry-studio#458]
### 您的功能建议是否与某个问题相关?

附件无法删改，想删改就要重新开对话，但是这样前面的交流就没了

### 请描述您希望实现的解决方案

能够对前文中上传的文档等附件可以删除，替换，增加等

**Comment by kangfenmao** [comment]
文件功能后续版本可能会取消，这里不允许修改。删除和修改都会导致聊天数据丢失而出现错误
