### ISSUE TITLE
[功能]: mermaid图表代码一键复制功能。

### ISSUE THREAD

**Issue by wjl697** [kangfenmao/cherry-studio#460]
### 您的功能建议是否与某个问题相关?

我在使用 Mermaid 图表时发现复制代码比较麻烦，缺乏直接复制 Mermaid 代码到剪贴板的功能，需要手动选择和复制。

### 请描述您希望实现的解决方案

在Mermaid 图表旁边添加一个 '复制代码' 按钮或链接。

**Comment by kangfenmao** [comment]
已增加复制按钮，下个版本发布
