### ISSUE TITLE
[错误]: 附件只能选择某个文件夹下的文件

### ISSUE THREAD

**Issue by Masque423** [kangfenmao/cherry-studio#461]
### 平台

Windows

### 版本

0.8.25

### 错误描述

添加附件时，只能打开一次文件浏览器，这样的话貌似只能选择某个文件夹下的文件了，没法选择其他文件夹的文件

### 重现步骤

附件

### 预期行为

添加完附件时，，还可以继续打开文件浏览器添加附件。

**Comment by czz404** [comment]
添加完一个之后，其他文件再添加只需要把文件拖入消息框里就行了

**Comment by kangfenmao** [comment]
已经开发完成了：https://github.com/kangfenmao/cherry-studio/pull/472
已经上线
