### ISSUE TITLE
[功能]: 为何最大上下文只有20轮，没有无限？

### ISSUE THREAD

**Issue by lioensky** [kangfenmao/cherry-studio#467]
### 您的功能建议是否与某个问题相关?

进行微调工作根本不够用啊。

### 请描述您希望实现的解决方案

希望增加可以设置无限上下文轮次的选项。

**Comment by ZzzzRyan** [comment]
那个 20 就是无限轮次，只不过标的 20

**Comment by lioensky** [comment]
> 那个 20 就是无限轮次，只不过标的 20

谢谢！
