### ISSUE TITLE
[错误]: 创建API渠道后，点击聊天，出现界面黑屏卡住崩溃，重启后卡在启动图标界面

### ISSUE THREAD

**Issue by chxcodepro** [kangfenmao/cherry-studio#468]
### 平台

Windows

### 版本

0.8.25

### 错误描述

我创建了三个API渠道，前两个是正常的，创建好第三个后，点击聊天，出现界面黑屏卡住崩溃，重启后卡在启动的图标界面，多次重试也无效
![image](https://github.com/user-attachments/assets/cc0feb12-be02-4e8b-a722-14d77d378a95)

### 重现步骤

1.创建api点击测试后
2.点击聊天

### 预期行为

尽快修复

**Comment by kangfenmao** [comment]
按一下快捷键 Ctrl Shift I 看看控制台报错信息

**Comment by chxcodepro** [comment]
![image](https://github.com/user-attachments/assets/ac7e4118-dc15-43d5-a456-466db334d27c)

**Comment by kangfenmao** [comment]
我已经修复了，还没有发版本，先下载旧版本使用吧

**Comment by kangfenmao** [comment]
升级到新本版本就没有这个问题了
