### ISSUE TITLE
[功能]: 希望加入知识库功能！

### ISSUE THREAD

**Issue by lioensky** [kangfenmao/cherry-studio#469]
### 您的功能建议是否与某个问题相关?

希望能有一个知识库文档的整理和挂载功能。

### 请描述您希望实现的解决方案

希望可以在对应的角色卡里直接挂载知识库txt文档，勾选后自动加载到系统提示词的开头里。方便一些对应的生产工作。

**Comment by kangfenmao** [comment]
这个月上线
