### ISSUE TITLE
bug 设置页面进入 默认模型 页面，会导致白屏 

### ISSUE THREAD

**Issue by corwin1949** [kangfenmao/cherry-studio#47]
win11 系统，软件更新到最新版本

我修改了模型的名称，改成了 openAI/gpt-4o-2024-09-04

不知道这一修改是否和白屏 bug 有关，是名称长度太长，或者改了自定义名称，或者用了 / 符号。

**Comment by kangfenmao** [comment]
明天我试试

**Comment by corwin1949** [comment]
> 应该是和上次修复显示问题有关系，你闲的时候看看白屏的页面，按 Ctrl + Shift + T，然后看看 console 控制台有没有报错，如果有的话，截图贴一下，我明天修一修这个问题 @corwin1949

按不出控制台……

**Comment by kangfenmao** [comment]
搞错了 控制台应该是 Ctrl + Shift +I

**Comment by corwin1949** [comment]
![image](https://github.com/user-attachments/assets/a511f515-ca83-4597-86cf-037c448dc63d)

**Comment by kangfenmao** [comment]
安装一下新版本，再试试

**Comment by corwin1949** [comment]
> 安装一下新版本，再试试

已修复，感谢
