### ISSUE TITLE
[问题]: 在读取上传的pdf文档时，是能够获取文档中的所有文字吗

### ISSUE THREAD

**Issue by lipc20052006** [kangfenmao/cherry-studio#474]
### 您的问题

在读取上传的pdf文档时，是能够获取文档中的所有文字吗？
基于文档问答的时候，是用了文档中的所有信息，还是只截取部分信息

### 优先级

中 (希望尽快得到答复)

**Comment by kangfenmao** [comment]
全部文字

**Comment by lipc20052006** [comment]
> 全部文字

谢谢回复，上传的文件用完后如何删除呢，里面买找到删除选项

**Comment by kangfenmao** [comment]
每次使用的时候会提取文字，用完就丢掉了

**Comment by lipc20052006** [comment]
我意思是传上来的pdf，用完之后，pdf文件还在客户端的文件菜单里，我怎么才能把他从文件菜单中把这个文件删除？数据目录在本地也存了一份，只能打开本地目录删除吗
