### ISSUE TITLE
[错误]: 

### ISSUE THREAD

**Issue by OWRIG** [kangfenmao/cherry-studio#476]
### 平台

macOS

### 版本

v0.8.26

### 错误描述

使用 claude 模型报错 “出错了，如果没有配置 API 密钥，请前往设置 > 模型提供商中配置密钥”。自检相同代理地址及密钥，测试连接通过，chat-next-web 可正常使用。
目前测试了claude-3-5-haiku-20241022、claude-3-5-sonnet-20241022 等相关 claude 模型均报错。

### 重现步骤

![image](https://github.com/user-attachments/assets/3f17106b-7fec-421c-8cc5-df1d873b2f09)
![image](https://github.com/user-attachments/assets/208af484-ba19-40ef-96f2-42922df99970)

### 预期行为

希望能正常使用 claude 相关模型

**Comment by kangfenmao** [comment]
不要使用非官方的 API 填写到官方的服务商中，自己新建一个服务商，类型选 OpenAI

**Comment by OWRIG** [comment]
仍报错
![image](https://github.com/user-attachments/assets/5ced1a5f-e5ba-48ee-a6b5-0de6c3b25c92)
![image](https://github.com/user-attachments/assets/44ebd1e2-29df-4831-8fd3-b6e0e2fab74e)

**Comment by kangfenmao** [comment]
建议咨询一下服务商
