### ISSUE TITLE
[错误]: 官方网站查看，意见反馈点击无反应

### ISSUE THREAD

**Issue by czz404** [kangfenmao/cherry-studio#477]
### 平台

Windows

### 版本

v0.8.26

### 错误描述

关于我们界面官方网站查看，意见反馈点击无反应，之前版本可以正常在浏览器打开界面

### 重现步骤

1.关于我们
2.官方网站-查看
3.意见反馈-反馈

### 预期行为

正常在系统默认浏览器打开界面

**Comment by kangfenmao** [comment]
这个可能是你浏览器的问题，我们几个测试都是正常的

**Comment by czz404** [comment]
我这里现在也无法复现了，不知道早上是什么问题
