### ISSUE TITLE
能不能快速删除话题，在话题最后加一个X，点击就删掉了

### ISSUE THREAD

**Issue by corwin1949** [kangfenmao/cherry-studio#48]
现在删话题太麻烦了，还要右键，还要选择菜单。

---
直接点X号删除就好了，不需要再次确定，也许可以做个撤销动作，但也没什么必要。

因为话题没太大的价值，大不了再问一次嘛

**Comment by kangfenmao** [comment]
可以加上，晚上发

**Comment by corwin1949** [comment]
> 可以加上，晚上发

感谢~
