### ISSUE TITLE
[功能]: 能不能实现窗口自定义大小

### ISSUE THREAD

**Issue by MFLS2023** [kangfenmao/cherry-studio#480]
### 您的功能建议是否与某个问题相关?

能不能像其他应用的客户端一样能够实现自定义大小，随意拉扯，每次固定大小，我只有一个屏幕，太难受了

### 请描述您希望实现的解决方案

我不知道咋解决，得你们解决，实现可以四个角随意拉动客户端大小

**Comment by kangfenmao** [comment]
可以拖动大小呀，你用的什么系统

**Comment by MFLS2023** [comment]
windows11专业版 
![image](https://github.com/user-attachments/assets/01ee6c2f-d735-4ef5-97d8-23d9d7661c7a)

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/8f18b6ec-c831-4508-8a87-e0827c5f15ba)

**Comment by MFLS2023** [comment]
真没用，哥们，难道就我一个人有问题吗？有点离谱
![image](https://github.com/user-attachments/assets/a4f64eb6-07b6-44d8-95c3-dda233ab1baa)

**Comment by ZzzzRyan** [comment]
![PixPin_2024-12-16_16-34-13](https://github.com/user-attachments/assets/0d3ef6b3-2a2b-4143-b5c0-7b34cee09d95)

**Comment by kangfenmao** [comment]
明天帮你看看 @MFLS2023

**Comment by MFLS2023** [comment]
也许可能我没表达清楚，我想它尽可能的小，但是最小还是太大了，还有你是怎么做到上传动图的

**Comment by ZzzzRyan** [comment]
> 也许可能我没表达清楚，我想它尽可能的小，但是最小还是太大了

确实表述不太到位，你说的这个问题已经有提过 issue 了，参考 #99 

但优先级还不是很高，等待作者后面处理。

> 还有你是怎么做到上传动图的

直接复制图片，在这个编辑框 Ctrl+V 粘贴即可。
