### ISSUE TITLE
[问题]: gemini的输出不够流畅

### ISSUE THREAD

**Issue by MFLS2023** [kangfenmao/cherry-studio#481]
### 您的问题

每次都是一段段的卡着出来的感觉，没办法像其他一样（也许是流式输出？），看着太生硬了
![image](https://github.com/user-attachments/assets/be10679d-b536-409c-b452-cf6d7e6b2a1f)
![image](https://github.com/user-attachments/assets/7ea022b0-bc06-47b1-8b4a-4b7132e978ef)

### 优先级

低 (有空再看)

**Comment by kangfenmao** [comment]
服务和模型问题，Cherry Studio 无法解决
