### ISSUE TITLE
[错误]: 回答出现问题

### ISSUE THREAD

**Issue by MFLS2023** [kangfenmao/cherry-studio#485]
### 平台

Windows

### 版本

v0.25

### 错误描述

貌似回答有问题
![image](https://github.com/user-attachments/assets/64744f70-f9db-4a06-bffe-87327cb17a2a)

### 重现步骤

1. 注册serv00
2. 发送serv00的注册邮件给claude
3. 让它和之前自己保号的账号信息合并

### 预期行为

按理来说应该正常回复才对

**Comment by kangfenmao** [comment]
看不懂

**Comment by MFLS2023** [comment]
就是你看到红色那一串了吗？为什么会出现那个东西，按道理不应该啊！

**Comment by kangfenmao** [comment]
> 就是你看到红色那一串了吗？为什么会出现那个东西，按道理不应该啊！

把输入内容渲染成 markdown 开关关闭就好了

**Comment by kangfenmao** [comment]
> 就是你看到红色那一串了吗？为什么会出现那个东西，按道理不应该啊！

设置面板里把输入内容渲染为 Markdown 关闭
