### ISSUE TITLE
[错误]: 智谱AI 连接失败

### ISSUE THREAD

**Issue by JIANMOP** [kangfenmao/cherry-studio#498]
### 平台

Windows

### 版本

v0.8.27

### 错误描述

填写完api之后测试连接失败，无法使用。

### 重现步骤

![image](https://github.com/user-attachments/assets/2667048f-6904-4ff3-b5a1-e9c11a82a931)

### 预期行为

正确使用glm

**Comment by kangfenmao** [comment]
把模型全部删除了之后重新添加

**Comment by JIANMOP** [comment]
已解决
