### ISSUE TITLE
[错误]: windows系统使用过程中，按键[右shift]被触发时，自动复制AI的最后一条回复

### ISSUE THREAD

**Issue by Komorebi-yaodong** [kangfenmao/cherry-studio#499]
### 平台

Windows

### 版本

v0.8.27

### 错误描述

 windows系统使用过程中，按键[右shift]被触发时，自动复制AI的最后一条回复
![image](https://github.com/user-attachments/assets/1f2dc981-1369-44b5-a2ea-0b81717ac8e3)

### 重现步骤

1. 进入聊天界面
2. 触发键盘的[右shift]
3. 观察到产生bug

### 预期行为

不应该复制内容

**Comment by kangfenmao** [comment]
截图看看快捷键设置页面

**Comment by Komorebi-yaodong** [comment]
![{481D73C1-D3A1-4E53-A890-CD4C55BBD17A}](https://github.com/user-attachments/assets/188752f9-4a99-43ef-8395-d1b6e5baf5c8)
![{7434AFEF-34AE-4E70-B61A-E79F376F0AD4}](https://github.com/user-attachments/assets/24702cc3-175d-4e21-be1a-7ff16b072103)

**Comment by ywxhqwq** [comment]
碰到同样的问题了，按右shift会触发复制上一条AI消息，确认过快捷键设置中没有启用相关的

**Comment by kangfenmao** [comment]
暂时解决办法：把这个快捷键启用，或者启用后修改一下

**Comment by ywxhqwq** [comment]
> 暂时解决办法：把这个快捷键启用，或者启用后修改一下

![image](https://github.com/user-attachments/assets/bb7da97f-ccd5-457a-b1c0-169e0413d54d)
我把键位改成其他了，但是出现了无法输入，按任何键都会触发复制上一条消息

**Comment by kindmesdilabso** [comment]
> 碰到同样的问题了，按右shift会触发复制上一条AI消息，确认过快捷键设置中没有启用相关的

问题+1 输入右边的问号的时候按shift加/?键的时候也提示复制成功

**Comment by kangfenmao** [comment]
备份一下数据，更新到这个版本测试一下：https://github.com/kangfenmao/cherry-studio/releases/tag/v0.9.0

**Comment by Komorebi-yaodong** [comment]
> 备份一下数据，更新到这个版本测试一下：https://github.com/kangfenmao/cherry-studio/releases/tag/v0.9.0

这个版本没有问题
