### ISSUE TITLE
打开小程序，左侧边栏的导航会被遮盖住无法点击

### ISSUE THREAD

**Issue by exqmjmz** [kangfenmao/cherry-studio#50]
MAC OS版本切换到第三方网站时菜单栏不能点击
需要关闭或者重新刷新应用才可以进行点击
0.6.11版本

https://github.com/user-attachments/assets/28664313-bf28-4e90-a1f6-6110c0fbab5c

**Comment by J-StrawHat** [comment]
我也复现了

**Comment by kangfenmao** [comment]
是啊，我也知道这个，还没有想到好的交互方式。这样做防止用户点击左侧会导致当前小程序对话被意外关闭

**Comment by exqmjmz** [comment]
> 是啊，我也知道这个，还没有想到好的交互方式。这样做防止用户点击左侧会导致当前小程序对话被意外关闭

能否在打开小程序后，在遮罩层这边，显示成退出按钮，其他图标隐藏。可以隐藏在上方头像图标或者下方齿轮图标
![image](https://github.com/user-attachments/assets/f805ad4f-4c79-4223-bdca-c9526bacc7bd)

**Comment by kangfenmao** [comment]
右上角有关闭按钮，你们知道吧
