### ISSUE TITLE
[错误]: 渲染问题

### ISSUE THREAD

**Issue by Long-louis** [kangfenmao/cherry-studio#500]
### 平台

Windows

### 版本

0.8.27

### 错误描述

![image](https://github.com/user-attachments/assets/7593cce1-0516-4447-a68d-d23664c65f0f)

### 重现步骤

公式渲染有错误

### 预期行为

![image](https://github.com/user-attachments/assets/1111bf40-4b80-47b0-a699-f3115b4d6773)
返回的文本是这些

**Comment by kangfenmao** [comment]
切换公式引擎
