### ISSUE TITLE
[错误]: 似乎与鼠标手势类软件的功能有冲突

### ISSUE THREAD

**Issue by homeworkkun** [kangfenmao/cherry-studio#508]
### 平台

Windows

### 版本

0.8.27

### 错误描述

我比较习惯用鼠标手势
![image](https://github.com/user-attachments/assets/8a70f3fc-8c9b-4871-9be2-b50d22cfb2e7)
比如经常想这么删除对话框内的文字
但是我在Cherry Studio中使用鼠标手势后，经常会变成让人摸不着头脑的情况。。
比如Delete的鼠标手势，最后会弹出复制成功的提示
关掉快捷按键之后，Delete的鼠标手势会直接新建话题

### 重现步骤

打开cherrystudio后使用鼠标手势就会这样
我使用的鼠标手势软件：mouseinc

### 预期行为

支持鼠标手势

**Comment by kangfenmao** [comment]
备份一下数据，更新到这个版本测试一下：https://github.com/kangfenmao/cherry-studio/releases/tag/v0.9.0

**Comment by homeworkkun** [comment]
> 备份一下数据，更新到这个版本测试一下：https://github.com/kangfenmao/cherry-studio/releases/tag/v0.9.0

0.9.0更新之后我第一时间下载试用了，此问题已解决，但是有个新的问题就是文档无法被添加到知识库中。
