### ISSUE TITLE
代理是否可以设置在模型服务（Model Provider）上

### ISSUE THREAD

**Issue by xvweirong** [kangfenmao/cherry-studio#51]
您好，由于大多数模型不需要用到Proxy，代理是否可以设置在模型服务（Model Provider）上？谢谢。

**Comment by kangfenmao** [comment]
这个是代理软件可以设置的，不在本软件的功能范围内。可以考虑使用合适的代理软件来处理这个问题。比如为不同的网站设置不同的规则。由于未来本软件也不考虑处理这个问题，所以就先关闭这个 issue。如果有关于代理相关问题，可以在下面留言
