### ISSUE TITLE
[错误]: 提一个界面不一致的地方

### ISSUE THREAD

**Issue by smilingpoplar** [kangfenmao/cherry-studio#511]
### 平台

Windows

### 版本

0.8.27

### 错误描述

发出消息的下方工具栏在右，消息回复的下方工具栏在左

![2024-12-21 12 28 54](https://github.com/user-attachments/assets/c898017c-e08c-4163-bb7a-344f94d0e46b)

### 重现步骤

对话栏显示

### 预期行为

在相同的位置找到工具

**Comment by Komorebi-yaodong** [comment]
我以为是故意这么设计的，好让我们快速查找信息的来着，哈哈

**Comment by kangfenmao** [comment]
是故意这样设计的
