### ISSUE TITLE
[功能]: 希望增加解析网页链接功能

### ISSUE THREAD

**Issue by ForstJean** [kangfenmao/cherry-studio#514]
### 您的功能建议是否与某个问题相关?

目前cherry可以识别出网页链接，但是模型并不能读取链接包含的内容
![屏幕截图 2024-12-21 233037](https://github.com/user-attachments/assets/1ab5a1a8-128c-4e30-bea7-5d2a7c21110d)

### 请描述您希望实现的解决方案

可以尝试在输入框工具栏加入解析链接功能。
可以参考一下另一款工具gomoon的“解析链接”
https://www.bilibili.com/video/BV1kH4y177Tu?vd_source=9f4f5fa0ddf7994dab77edc934f59978&spm_id_from=333.788.videopod.sections
![屏幕截图 2024-12-21 233419](https://github.com/user-attachments/assets/0aa85d04-f0d7-4d93-8dca-9ebd89c979aa)

**Comment by ForstJean** [comment]
似乎可以通过提取链接中的文本信息，然后发送给模型，来实现访问链接内容的功能

**Comment by ForstJean** [comment]
群里看到开发者准备拓展的知识库了，应该包含了抓取网站链接能力了，此贴问题终结

**Comment by kangfenmao** [comment]
这个后面要做的
