### ISSUE TITLE
菜单需要限制最大高度不能超过窗口

### ISSUE THREAD

**Issue by yangg** [kangfenmao/cherry-studio#52]
现在模型多时不管显示上还是下都无法显示完整，滚动也出不来
<img width="604" alt="image" src="https://github.com/user-attachments/assets/626c8e8a-a0e4-451b-ae2b-7fa27aac0d38">

**Comment by kangfenmao** [comment]
这个要重新做了，现在不支持搜索。我要做一个更加精致的选择模型的界面

**Comment by kangfenmao** [comment]
我可以先临时限制一下高度。先把重要的文件功能开发出来，再搞这个

**Comment by kangfenmao** [comment]
修复完成，下个版本上线

**Comment by kangfenmao** [comment]
已经上线了 https://github.com/kangfenmao/cherry-studio/releases/tag/v0.6.12
