### ISSUE TITLE
[错误]:  和软件Stranslate快捷键冲突

### ISSUE THREAD

**Issue by proton9091** [kangfenmao/cherry-studio#523]
### 平台

Windows

### 版本

0.8.27

### 错误描述

软件Stranslate有划词翻译功能，我在cherry studio里使用软件Stranslate的快捷键，cherry studio会自动新建一个话题，并且话题栏目会自动缩回去（有时候将其他软件的文本复制到cherry studio的输入框内，也会重现这个问题，在谷歌ai studio复制输入框的文本比较容易复现），如下图所示，之前的版本0.8.24并没有这问题。

![image](https://github.com/user-attachments/assets/d257f5c1-47c3-475f-be25-36d20ac85818)

### 重现步骤

在cherry studio里使用软件Stranslate的快捷键划词翻译

### 预期行为

正常运行功能

**Comment by kangfenmao** [comment]
备份一下数据，更新到这个版本测试一下：https://github.com/kangfenmao/cherry-studio/releases/tag/v0.9.0
