### ISSUE TITLE
[错误]: Gemini 除了Gemini 2.0 Flash Experimental能用，其他的模型都不能用,找到原因了是开启了搜索

### ISSUE THREAD

**Issue by Kooazzr** [kangfenmao/cherry-studio#524]
### 平台

Windows

### 版本

0.8.27

### 错误描述

除了Gemini 2.0 Flash Experimental能用，其他的模型都不能用. 同一个api密钥在openwebui里正常使用。
![PixPin_2024-12-24_17-47-49](https://github.com/user-attachments/assets/16f2ece6-4f7d-45f1-ad66-0d7a9ceb61cf)

### 重现步骤

1.进入聊天页面
2.选择除Gemini 2.0 Flash Experimental 以外的gemini模型
3.开始聊天
4.返回错误代码

### 预期行为

正常运行功能

**Comment by kangfenmao** [comment]
这是个问题，切换一下联网模型，把联网开关关闭掉

**Comment by Kooazzr** [comment]
> 这是个问题，切换一下联网模型，把联网开关关闭掉

还是不行啊

**Comment by MoozLee** [comment]
> > 这是个问题，切换一下联网模型，把联网开关关闭掉
> 
> 还是不行啊

请问如何关闭啊？今天也是突然报这个错

**Comment by kangfenmao** [comment]
切换到 Gemini 2.0 Flash Experimental 模型，然后把输入框里面的搜索关闭。

下个版本这个问题就没有了

**Comment by smilingpoplar** [comment]
可以把`dns.google`加入分流规则

https://github.com/CherryHQ/cherry-studio/issues/505#issuecomment-2566829741
