### ISSUE TITLE
[问题]: 请问一下，在模型服务页面，点击管理后有时候能看到相同的模型，它们之间有什么区别吗

### ISSUE THREAD

**Issue by Komorebi-yaodong** [kangfenmao/cherry-studio#529]
### 您的问题

如下图所示，点击管理后，有很多模型是一样的，它们有什么区别吗，能否标记出他们之间的区别？
![{A9802077-544A-4224-9116-943760741440}](https://github.com/user-attachments/assets/89870f97-9154-4005-b24e-e1fd6741fce0)

### 优先级

低 (有空再看)

**Comment by kangfenmao** [comment]
模型 ID 不一样，界面上没有显示出来，后面我加上模型 ID 的显示
