### ISSUE TITLE
❗️❗️❗️ 通知 📢 文件和知识库功能正在开发中

### ISSUE THREAD

**Issue by kangfenmao** [kangfenmao/cherry-studio#53]
如果有什么好的想法可以在下面留言

https://github.com/kangfenmao/cherry-studio/issues/27
https://github.com/kangfenmao/cherry-studio/issues/29

**Comment by corwin1949** [comment]
意思是支持RAG文档吗，这好哎

**Comment by kangfenmao** [comment]
> 意思是支持RAG文档吗，这好哎

是的，GraphRAG 支持

**Comment by exqmjmz** [comment]
可以参考coze.cn的bot中”知识“这个参数
1、文本
单纯的就是文本内容
2、表格
可以有多个结构化表格，每个表格可以设置列参数、内容
3、图片
照片上传到知识库后自动/手动添加语义描述

如果加入本地文件和知识库，可以加入向量化功能
将文件的数据存储到sqlite中以blob的方式存储，向量数据也是存储到了sqlite中，这个在最近的vscode比较热门的continuedev插件有体现
BAAI/bge-m3模型在siliconflow现在是限时免费，我在continuedev插件向量化本地项目代码文件就是用这个
https://docs.siliconflow.cn/reference/createembedding-1
