### ISSUE TITLE
[错误]:为什么会消耗这么多的tokens？

### ISSUE THREAD

**Issue by EdenYyh** [kangfenmao/cherry-studio#535]
### 平台

Windows

### 版本

v0.8.27

### 错误描述

过多的消耗token，新对话，发送你好，qwen-turbo回复，花费了81tokens；为什么会消耗这么多的token？正常来说一个中文汉字最多消耗一个token

### 重现步骤

![image](https://github.com/user-attachments/assets/844c774f-0210-447a-b6ba-5cf1088753f2)
![image](https://github.com/user-attachments/assets/1f46e0ab-7677-4952-a4ce-3513b5d7a1c6)
![image](https://github.com/user-attachments/assets/126378ad-2e17-49c9-9d1d-1b562b57f640)
![image](https://github.com/user-attachments/assets/300d022d-b7c4-4606-8ae1-f9c0776db158)

这是使用前后的tokens对比

### 预期行为

为什么会消耗这么多的tokens？

**Comment by kangfenmao** [comment]
提示词是什么

**Comment by EdenYyh** [comment]
@kangfenmao 我没加提示词。我又试了另外一个模型，我发现问题了，原来是qwen本身的问题！！！

**Comment by aigc4o** [comment]
一个问题开一个issue就行，你重复发帖了
