### ISSUE TITLE
[功能]: 需要只发送图片功能

### ISSUE THREAD

**Issue by lunemoe** [kangfenmao/cherry-studio#538]
### 您的功能建议是否与某个问题相关?

当尝试发送图片时，发现其只能在添加文字的情况下才能被发送出去，此情况有待优化。

### 请描述您希望实现的解决方案

使用 Gemini 处理图片时，必须添加文字才能发送，这很麻烦，希望优化。

**Comment by kangfenmao** [comment]
好的

**Comment by kangfenmao** [comment]
已经开发完成，下个版本上线
