### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by czz404** [kangfenmao/cherry-studio#54]
感谢作者制作这么好的软件！使用中遇到了两个小问题，麻烦作者看一下

1、自定义服务添加 openai 第三方服务（ https://burn.hair/ ），检查密钥显示连接失败。
      api 文档：https://github.com/BurnHair/docs

2、安装程序能否可以自定义安装位置，想安装到 D 盘

**Comment by corwin1949** [comment]
> 感谢作者制作这么好的软件！使用中遇到了两个小问题，麻烦作者看一下
> 
> 1、自定义服务添加 openai 第三方服务（ https://burn.hair/ ），检查密钥显示连接失败。 api 文档：https://github.com/BurnHair/docs
> 
> 2、安装程序能否可以自定义安装位置，想安装到 D 盘

burn.hair，我也有用，我这边可以啊。你要不试试国内的链接。

**Comment by czz404** [comment]
> burn.hair，我也有用，我这边可以啊。你要不试试国内的链接。
请问你是如何设置的，是点加号新添加模型然后 api 地址填 https://burn.hair/ 吗，我这里检查密钥一直显示连接失败

**Comment by corwin1949** [comment]
> > burn.hair，我也有用，我这边可以啊。你要不试试国内的链接。
> 
> 请问你是如何设置的，是点加号新添加模型然后 api 地址填 https://burn.hair/ 吗，我这里检查密钥一直显示连接失败
> 
> 我接口地址试了 https://burn.hair/ ； [https://burn.hair/v1；](https://burn.hair/v1%EF%BC%9B) https://cn-test.burn.hair/ 都不行

你试试从管理添加模型

**Comment by kangfenmao** [comment]
应该这样：https://burn.hair

**Comment by kangfenmao** [comment]
第二个问题，如果自定义安装路径会导致升级的时候每次都要手动，为大多数用户考虑还是暂时先不要修改安装路径了。如果自己需要，可以把程序复制到需要的目录。

**Comment by czz404** [comment]
解决了，感谢解答！
