### ISSUE TITLE
[错误]: 对话界面右键的复制功能未生效

### ISSUE THREAD

**Issue by ousugo** [kangfenmao/cherry-studio#543]
### 平台

Windows

### 版本

v0.9.1

### 错误描述

在对话界面，右键的复制功能未生效，点击复制后实际上并未复制任何内容
![gif](https://github.com/user-attachments/assets/27eab293-ea45-41cf-9daa-931d46dcf724)

### 重现步骤

1. 在对话界面点击右键->复制
2. 尝试粘贴，发现未复制任何内容

### 预期行为

点击复制后，复制内容

**Comment by kangfenmao** [comment]
先选中文字然后右键复制
