### ISSUE TITLE
[错误]: 某些输出包含<sub></sub>无法正常显示

### ISSUE THREAD

**Issue by ZhouXiaolin** [kangfenmao/cherry-studio#545]
### 平台

Windows

### 版本

v0.9.1

### 错误描述

使用gemini的thinking模型时，输出的内容包含数学公式

```md
**3. 推导共变导数的表达式**

考虑一个向量场 **V**，其在某坐标系下的分量为 V<sup>ν</sup>，基向量为 **e**<sub>ν</sub>。  向量 **V** 可以表示为 **V** = V<sup>ν</sup> **e**<sub>ν</sub> （使用爱因斯坦求和约定）。

我们尝试对 **V** 进行求导。  由于基向量 **e**<sub>ν</sub> 也可能随坐标变化，我们需要对乘积进行求导：

∂<sub>μ</sub>**V** = ∂<sub>μ</sub>(V<sup>ν</sup> **e**<sub>ν</sub>) = (∂<sub>μ</sub>V<sup>ν</sup>) **e**<sub>ν</sub> + V<sup>ν</sup> (∂<sub>μ</sub>**e**<sub>ν</sub>)

第一项 (∂<sub>μ</sub>V<sup>ν</sup>) **e**<sub>ν</sub>  类似于普通偏导数，但它不是一个张量，因为基向量 **e**<sub>ν</sub> 本身会随坐标变换。  关键在于第二项 V<sup>ν</sup> (∂<sub>μ</sub>**e**<sub>ν</sub>)。
```

<sub></sub>部分无法正常显示

### 重现步骤

gemini-thinking模型

### 预期行为

它应该正常地显示如下，而不是直接输出<sup></sup>

**3. 推导共变导数的表达式**

考虑一个向量场 **V**，其在某坐标系下的分量为 V<sup>ν</sup>，基向量为 **e**<sub>ν</sub>。  向量 **V** 可以表示为 **V** = V<sup>ν</sup> **e**<sub>ν</sub> （使用爱因斯坦求和约定）。

我们尝试对 **V** 进行求导。  由于基向量 **e**<sub>ν</sub> 也可能随坐标变化，我们需要对乘积进行求导：

∂<sub>μ</sub>**V** = ∂<sub>μ</sub>(V<sup>ν</sup> **e**<sub>ν</sub>) = (∂<sub>μ</sub>V<sup>ν</sup>) **e**<sub>ν</sub> + V<sup>ν</sup> (∂<sub>μ</sub>**e**<sub>ν</sub>)

第一项 (∂<sub>μ</sub>V<sup>ν</sup>) **e**<sub>ν</sub>  类似于普通偏导数，但它不是一个张量，因为基向量 **e**<sub>ν</sub> 本身会随坐标变换。  关键在于第二项 V<sup>ν</sup> (∂<sub>μ</sub>**e**<sub>ν</sub>)。

**Comment by ZhouXiaolin** [comment]
`<sub></sub>`无法正常显示，它直接输出了

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/632c3203-3b16-4948-9ebc-7f33b8f41e05)

已修复，等下个版本更新
