### ISSUE TITLE
[功能]: 希望小程序中增加 github copilot

### ISSUE THREAD

**Issue by zerolincku** [kangfenmao/cherry-studio#547]
### 您的功能建议是否与某个问题相关?

无

### 请描述您希望实现的解决方案

github copilot 网页版能够进行对话，以及切换模型，希望能够支持，能够更方便的使用 copilot 提供功能

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/8a5cca7f-ce31-4aa0-9432-205e8848d581)

已增加，等下个版本发布
