### ISSUE TITLE
支持小窗模式

### ISSUE THREAD

**Issue by corwin1949** [kangfenmao/cherry-studio#55]
最小宽度太宽了。和其他软件协作时，不能并排显示在同一屏幕；屏幕宽度不够，需要来回切换窗口，不太方便

能不能设计一个最窄的宽度模式，左边右边什么都没有，只有中间的对话界面。

这样我开浏览器或者开笔记软件，可以把[cherry-studio](https://github.com/kangfenmao/cherry-studio)固定屏幕右边，方便随时和LLM对话。

比如这样：
![image](https://github.com/user-attachments/assets/bcb39a24-3185-48e0-95a4-9e61f63cffb7)

**Comment by kangfenmao** [comment]
这个可以做，只不过影响的页面比较多，都需要做适配。目前主要工作集中在文件处理上，所以先放在这里记录，等我大模块做完了再做这个 feature

**Comment by corwin1949** [comment]
> 这个可以做，只不过影响的页面比较多，都需要做适配。目前主要工作集中在文件处理上，所以先放在这里记录，等我大模块做完了再做这个 feature

确实要做好多适配。感谢作者。

**Comment by kangfenmao** [comment]
https://github.com/kangfenmao/cherry-studio/issues/136

**Comment by kangfenmao** [comment]
话题合并：https://github.com/kangfenmao/cherry-studio/issues/122
