### ISSUE TITLE
[Bug]: 会跳转到https://viablehornsborn.com

### ISSUE THREAD

**Issue by wmc1125** [kangfenmao/cherry-studio#552]
### Platform

macOS

### Version

0.9.1

### Bug Description

用着用着就跳转到这个链接了  https://viablehornsborn.com/a7rq77dq0?bpblzy=86&refer=http%3A%2F%2Flocalhost%3A3000%2Fgeneral&kw=%5B%22random%22%2C%22gamertags%22%2C%22list%22%2C%22gamertaggenerator%22%2C%22top%22%5D&key=0b3967e3a4821fac5539cb5589bd8eb8&scrWidth=1440&scrHeight=900&tz=8&v=24.10.2259&ship=&psid=localhost:3000,localhost:3000&sub3=invoke_layer&res=14.31&dev=r&uuid=7ca92434-6184-47c0-b0b0-8ad2402505a1%3A2%3A1

https://github.com/user-attachments/assets/fc605459-c82c-4701-b79f-981a600ed7db

### Steps To Reproduce

反复点击下助手,话题就会出现这个问题

### Expected Behavior

反复点击下助手,话题就会出现这个问题

**Comment by kangfenmao** [comment]
需要提供一下这个会话的关键聊天记录内容，用复制按钮复制到下面，我来参考一下

**Comment by wmc1125** [comment]
我给你个todesk&nbsp; 我演示给你看下可以吗





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月27日(星期五) 下午2:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kangfenmao/cherry-studio] [Bug]: 会跳转到https://viablehornsborn.com (Issue #552)














 
需要提供一下这个会话的关键聊天记录内容，用复制按钮复制到下面，我来参考一下

**Comment by kangfenmao** [comment]
加我一下微信说：kangfenmao

**Comment by kangfenmao** [comment]
输入内容如下：

---

这个是广告代码  有什么作用  <div id="j653f6a" style="position: fixed; inset: 0px; z-index: 2147483647; background: black; opacity: 0.01; height: 340px; width: 1440px;"><a id="lko7" href="http://viablehornsborn.com/a7rq77dq0?bpblzy=86&amp;refer=http%3A%2F%2Flocalhost%3A3000%2Fgeneral&amp;kw=%5B%22random%22%2C%22gamertags%22%2C%22list%22%2C%22gamertaggenerator%22%2C%22top%22%5D&amp;key=0b3967e3a4821fac5539cb5589bd8eb8&amp;scrWidth=1440&amp;scrHeight=900&amp;tz=8&amp;v=24.10.2259&amp;ship=&amp;psid=localhost:3000,localhost:3000&amp;sub3=invoke_layer&amp;res=14.31&amp;dev=r&amp;uuid=7ca92434-6184-47c0-b0b0-8ad2402505a1%3A2%3A1" target="_blank" style="display: block; height: inherit;"></a></div>

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/4bde06ae-78cd-45b7-854c-565fd60ca1eb)

看到这段代码生成了一个透明的 div 覆盖了用户界面

---

解决办法：

1. 避免输入恶意代码
2. 关闭用户消息使用 markdown 渲染开关

**Comment by kangfenmao** [comment]
这段代码存在多个潜在的风险和问题，尤其是在安全性、用户体验和代码质量方面。以下是详细的分析：

---

### 1. **安全风险**
   - **恶意链接**：`<a>`标签中的`href`指向一个外部链接（`viablehornsborn.com`），该链接包含大量查询参数，可能用于跟踪或恶意目的。如果该链接指向不安全的网站，可能会导致用户被重定向到钓鱼网站、恶意软件下载页面或其他有害内容。
   - **数据泄露**：查询参数中包含敏感信息，例如`uuid`、`refer`（当前页面的URL）、`scrWidth`、`scrHeight`等。这些信息可能被用于跟踪用户行为或进行攻击。
   - **跨站脚本攻击（XSS）**：如果外部链接或查询参数被恶意利用，可能会导致XSS攻击，从而窃取用户数据或执行恶意代码。

---

### 2. **用户体验问题**
   - **透明覆盖层**：`<div>`元素覆盖了整个屏幕（`inset: 0px`），并且设置了极低的透明度（`opacity: 0.01`）。虽然用户几乎看不到它，但它会拦截所有点击事件，导致用户无法与页面其他部分交互。
   - **误导性点击**：`<a>`标签的`display: block`和`height: inherit`属性使其覆盖整个`<div>`区域，用户可能会在不知情的情况下点击链接，导致意外跳转。
   - **性能问题**：固定定位的覆盖层可能会影响页面性能，尤其是在低性能设备上。

---

### 3. **代码质量问题**
   - **硬编码尺寸**：`width`和`height`被硬编码为`1440px`和`340px`，这可能导致在不同屏幕尺寸或设备上显示异常。
   - **不必要的复杂性**：`z-index`被设置为`2147483647`，这是最大值，通常用于确保元素位于最顶层。然而，这种做法可能会导致与其他元素的层级冲突。
   - **缺乏语义化**：代码没有使用语义化的HTML标签，而是直接使用`<div>`和`<a>`，这可能会影响可维护性和可读性。

---

### 4. **潜在的法律和合规问题**
   - **隐私问题**：如果未经用户同意收集或传输数据（如`uuid`、`refer`等），可能违反隐私法规（如GDPR或CCPA）。
   - **广告欺诈**：如果该代码用于生成虚假点击或流量，可能涉及广告欺诈行为。

---

### 改进建议
1. **移除或替换外部链接**：确保链接指向可信的、安全的网站，并避免传输敏感数据。
2. **优化覆盖层设计**：如果必须使用覆盖层，应明确告知用户其用途，并提供关闭或跳过的选项。
3. **简化代码**：移除不必要的硬编码值，使用响应式设计以适应不同设备。
4. **增强安全性**：避免在URL中传输敏感信息，并对用户输入进行验证和过滤。
5. **遵守隐私法规**：确保数据收集和处理符合相关法律法规，并获取用户同意。

---

### 总结
这段代码存在较高的安全风险和用户体验问题，建议彻底审查其用途并进行优化。如果该代码用于广告或跟踪目的，应确保其透明性和合法性，同时保护用户隐私和数据安全。
