### ISSUE TITLE
[功能]: 选择对话模型时，建议模型名后面标注一下服务商

### ISSUE THREAD

**Issue by vimbackground** [kangfenmao/cherry-studio#557]
### 您的功能建议是否与某个问题相关?

有一些开源大模型，不同服务商都有提供，常见的如：qwen2.5、llama3.1、command-r等。

如果在后台启用的多家AI服务商中都启用了这些模型，在对话框选择时，如果再有置顶，有时候会弄混服务商。

### 请描述您希望实现的解决方案

希望在对话模型选择窗口中，相关模型后面，标注一下服务商。能让用户方便进行针对性的选择。

### 请描述您考虑过的其他方案

当然，不要在不同平台选重复的模型，就不会碰到这个问题了。但各家额度不同，都打开，额度更足。

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/f1a0bef7-f003-4f63-a381-1485a784ef53)

已经增加，下个版本发布
