### ISSUE TITLE
设置里的 Default Assistant 设置了 context 为 3，不生效

### ISSUE THREAD

**Issue by yangg** [kangfenmao/cherry-studio#56]
返回聊天，新建一个 Default Assistant context 还是 6，这个设置没用吗？

**Comment by kangfenmao** [comment]
你需要在这个设置里面调整

<img width="1201" alt="image" src="https://github.com/user-attachments/assets/301f295f-4c13-4d0c-bf9c-b79e4e91ff11">

**Comment by yangg** [comment]
是在这里设置，但是新建不生效

**Comment by kangfenmao** [comment]
> 是在这里设置，但是新建不生效

这是个 bug 我要修一下，哈哈哈

**Comment by kangfenmao** [comment]
这个已经修复了，更新版本再试试
