### ISSUE TITLE
[功能]: 用户自定义话题总结Prompt

### ISSUE THREAD

**Issue by aigc4o** [kangfenmao/cherry-studio#562]
### 您的功能建议是否与某个问题相关?

我经常与AI进行英文对话，生成话题却是中文，应用语言改为英文也是如此。看了下，应该是Cherry内置的中文话题总结prompt导致的。

### 请描述您希望实现的解决方案

- 希望能自定义话题总结的prompt。
- 如果cherry打算面向多语言用户的话，可以把话题生成的prompt也翻译一下。

### 请描述您考虑过的其他方案

- 有考虑过让模型识别用户语言，比如

    > 你是一名擅长会话的助理，你需要将用户的会话总结为 10 个字以内的标题，标题语言与用户的首要语言一致，不要使用标点符号和其他特殊符号。

    但是在中英文都有的情况下，模型可能无法识别用户语言，返回无关内容。

- 建议还是加一个自定义。

**Comment by kangfenmao** [comment]
可以

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/db921979-cdb0-49ce-8077-573acf7a75a3)

已经增加配置，下个版本发布
