### ISSUE TITLE
[功能]: 期望添加讯飞星火的模型接口服务

### ISSUE THREAD

**Issue by 1731563584** [kangfenmao/cherry-studio#565]
### 您的功能建议是否与某个问题相关?

当前缺少讯飞星火大模型接口服务

### 请描述您希望实现的解决方案

加入接口，见文档：https://www.xfyun.cn/doc/spark/Web.html（websocket调用） 或 https://www.xfyun.cn/doc/spark/HTTP%E8%B0%83%E7%94%A8%E6%96%87%E6%A1%A3.html （http调用）

**Comment by kangfenmao** [comment]
自己添加就可以了

**Comment by g1021895463** [comment]
兼容OPENAI接口都可以自己添加

**Comment by 1731563584** [comment]
> 自己添加就可以了

ok，突然忘记有openai接口兼容的了，谢谢！

**Comment by 1731563584** [comment]
> ok，突然忘记有openai接口兼容的了，谢谢！

ok，突然忘记有openai接口兼容的了，谢谢！
