### ISSUE TITLE
[错误]: 豆包无法连接

### ISSUE THREAD

**Issue by kdurant** [kangfenmao/cherry-studio#573]
### 平台

Linux

### 版本

0.9.2

### 错误描述

豆包配置好KEY后，怎是提示连接失败

### 重现步骤

![image](https://github.com/user-attachments/assets/2ece93fb-3e7e-48c6-86f8-ebef54ff73a5)

### 预期行为

可以正确配置

**Comment by homeworkkun** [comment]
豆包那个平台挺离谱的，你输入模型名没有用，得添加接入点

**Comment by kangfenmao** [comment]
模型名字错了

**Comment by liujianfeng** [comment]
> 模型名字错了

名字应该怎么写呀？

**Comment by kangfenmao** [comment]
好像是 ep-xxxxxxxx 这样的
