### ISSUE TITLE
[功能]: 希望能够增加genspark小程序

### ISSUE THREAD

**Issue by doubleheiker** [kangfenmao/cherry-studio#578]
### 您的功能建议是否与某个问题相关?

genspark最近较火，也是搭上了genspark的车，希望开发者大大能够增加genspark的小程序，感激不尽！

### 请描述您希望实现的解决方案

genspark最近较火，也是搭上了genspark的车，希望开发者大大能够增加genspark的小程序，感激不尽！

**Comment by kangfenmao** [comment]
可以

**Comment by kangfenmao** [comment]
![image](https://github.com/user-attachments/assets/5fddb367-d45c-4627-bf20-fa6f81db1c08)
等下个版本发布
