### ISSUE TITLE
UI 暗黑模式下面板分界不明显

### ISSUE THREAD

**Issue by ZzzzRyan** [kangfenmao/cherry-studio#58]
## 1 前言

非常感谢作者带来这么好的软件！个人原先是 NextChat 和 LobeChat 的用户，但一直烦恼他们的交互奇怪+界面卡顿。遇到 cherry-studio解决了我一直以来的几个痛点，同时还能保持轻量，确实非常好用！在此有一点小的建议。

## 2 建议

在 UI 暗黑模式下，左中右几个面板的区分度比较低，面板之间的分界线、对话中的分界线可以再明显一点，或者使用不同的颜色深浅度。目前几个版面未分隔开看着会有点凌乱。

以及滑块控件上的绿色主题色偏暗了，在暗黑模式下较弱化。又或许是背景黑色可以再浅一点，比如 `#1E1E1E` ？

---

如果方便的话，作者可以放出赞赏入口，我希望能表达一点支持！也希望软件越来越优秀。

**Comment by kangfenmao** [comment]
1. 感谢喜欢这个项目，我会在未来数年内持续更新这个
2. 可能由于显示器都有色差，我会调亮一些适应更多屏幕显示
3. 赞赏入口暂时还没有，如果喜欢可以推荐给身边的朋友来用
