### ISSUE TITLE
[错误]: 数学公式中如果有中文，中文字符重叠

### ISSUE THREAD

**Issue by Solareni** [kangfenmao/cherry-studio#581]
### 平台

macOS

### 版本

0.9.2

### 错误描述

\[
\frac{1}{2\pi i} \oint_C -\frac{\zeta'(s)}{\zeta(s)} \frac{x^s}{s} ds = \sum_{\text{极点 } s_0 \text{ 在 } C \text{ 内}} \text{Res}\left(-\frac{\zeta'(s)}{\zeta(s)} \frac{x^s}{s}, s_0\right)
\]

\[
\frac{1}{2\pi i} \int_{c-i\infty}^{c+i\infty} n^{-s} \frac{x^s}{s} ds =
\begin{cases}
1, & \text{如果 } n < x \\
0, & \text{如果 } n > x
\end{cases}
\]
<img width="471" alt="截屏2024-12-30 14 21 52" src="https://github.com/user-attachments/assets/aedeaa73-3919-44cd-9fd6-65ec58693961" />

<img width="347" alt="截屏2024-12-30 14 22 18" src="https://github.com/user-attachments/assets/9172287b-620c-4604-bbff-a687bbb6f9a9" />

### 重现步骤

数学公式

### 预期行为

![截屏2024-12-30 14 23 14](https://github.com/user-attachments/assets/2fd74328-da36-493d-b091-846e495cc976)
![截屏2024-12-30 14 23 26](https://github.com/user-attachments/assets/34bbfd1f-b8e1-4180-83e1-8ff97e150269)

**Comment by kangfenmao** [comment]
设置面板里面切换公式引擎
