### ISSUE TITLE
智能体改进：名称、上下文支持、模型参数支持

### ISSUE THREAD

**Issue by Yizhouuu** [kangfenmao/cherry-studio#59]
首先非常感谢作者所做的工作，对于智能体功能有以下一些想法

- 智能体这个名称我个人感觉有些怪怪的？不过当然，这个主要看作者喜好😂
- 如果能像 NextChat 那样支持包含上下文（包括 assistant, user, system 讯息）会比较好，方便 few-shot 训练
- 如果能设定模型参数（温度、流式传输、上下文长度等等）、选用的模型也会方便很多

**Comment by kangfenmao** [comment]
智能体这个名字不知道如何命名比较好，业界是这么叫的

<img width="1304" alt="image" src="https://github.com/user-attachments/assets/a92b380f-8139-470e-ae31-da89f83b9ec3">

<img width="1320" alt="image" src="https://github.com/user-attachments/assets/d550e6d5-5bcd-47e4-a2fa-c6f6d55507ba">

**Comment by Yizhouuu** [comment]
搜了一下，原来是 Agents 的中文翻译🤔不过翻译问题不大

我知道能在对话页中更改对话的参数，但是没法在智能体中预先定义智能体的参数，以及包含指定上下文

**Comment by kangfenmao** [comment]
> 搜了一下，原来是 Agents 的中文翻译🤔不过翻译问题不大
> 
> 我知道能在对话页中更改对话的参数，但是没法在智能体中预先定义智能体的参数，以及包含指定上下文

我明白你的意思了，你需要一个更加高级的智能体设置，支持更多的参数。这个问题先放在这里，让我考虑一下

**Comment by Yizhouuu** [comment]
> > 搜了一下，原来是 Agents 的中文翻译🤔不过翻译问题不大
> > 我知道能在对话页中更改对话的参数，但是没法在智能体中预先定义智能体的参数，以及包含指定上下文
> 
> 我明白你的意思了，你需要一个更加高级的智能体设置，支持更多的参数。这个问题先放在这里，让我考虑一下

麻烦了。以前从 NextChat 转到 LobeChat 时，最大的阻力就是没法像 NextChat 的面具一样定义上下文，个人认为这个功能还是蛮重要的，可以很大的扩展功能

**Comment by yangg** [comment]
我的建议是语言选英文

同样觉得这里面能设置 模型参数比较好。

**Comment by kangfenmao** [comment]
> 我的建议是语言选英文
> 
> 同样觉得这里面能设置 模型参数比较好。

语言是根据用户操作系统语言来的。智能体可以改进，将来甚至可以附带知识库

**Comment by Yizhouuu** [comment]
> 我的建议是语言选英文
> 
> 同样觉得这里面能设置 模型参数比较好。

没，如果已经是通用的翻译了，那自然就没什么更改的必要了😂

> 将来甚至可以附带知识库

期待期待

**Comment by yangg** [comment]
@Yizhouuu 系统语言选英文，再也不会遇到翻译不喜欢，觉得别扭的问题。

**Comment by Yizhouuu** [comment]
> @Yizhouuu 系统语言选英文，再也不会遇到翻译不喜欢，觉得别扭的问题。

没，我个人喜好到不在讨论范围内，交 issue 是为了项目本身考虑嘛😂只是讨论下这个翻译本身合适不合适

**Comment by kangfenmao** [comment]
看来我要弄一个专业的智能体编辑工具了 @Yizhouuu

**Comment by Yizhouuu** [comment]
辛苦🙏

**Comment by kangfenmao** [comment]
这个功能准备提上日程

**Comment by Yizhouuu** [comment]
太好了，这是目前我全面转到 cherry studio 的最大阻力😂尤其是预定上下文

**Comment by kangfenmao** [comment]
这个功能我记着呢，主要是最近关于文件和网页预览的功能需求量太大了，所以先改道把文件优先级提高了。

**Comment by Yizhouuu** [comment]
> 这个功能我记着呢，主要是最近关于文件和网页预览的功能需求量太大了，所以先改道把文件优先级提高了。
> 
> 智能体：预定义上下文 智能体：附带参数
> 
> 助手：分组（这个往后排一排）

了解了解，按照你的计划来即可

话说除了这个，快捷键功能计划何时开发？清除上下文这些功能使用频率很频繁，如果有快捷键会很方便，就不用总是动鼠标了

**Comment by kangfenmao** [comment]
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/4175c227-4eed-41d8-8ef3-0bb8805d0de7">

加了单独的编辑入口，点击编辑会进入智能体编辑页面，编辑页面空间比较大，支持自定义更多参数。还在做

**Comment by kangfenmao** [comment]
<img width="1332" alt="image" src="https://github.com/user-attachments/assets/ca831e4c-94d5-4f61-aef7-d4f26e16a0f2">

还差模型参数调节

**Comment by Yizhouuu** [comment]
跟我预想的差不多，辛苦了🙏
