### ISSUE TITLE
总是出现连接错误，网络一切顺通

### ISSUE THREAD

**Issue by Sun9220** [kangfenmao/cherry-studio#6]
总是提示连接错误，
`Error: 400 invalid preamble: Request with a GET or HEAD method cannot have a body.`
网络一切顺通的，api地址也能访问的

**Comment by kangfenmao** [comment]
> 总是提示连接错误，
> 
> `Error: 400 invalid preamble: Request with a GET or HEAD method cannot have a body.`
> 
> 网络一切顺通的，api地址也能访问的

需要你提供下面信息：

1. 模型服务商 API 地址
2. 模型 ID
3. 客户端平台和版本号

我看看具体原因

**Comment by Sun9220** [comment]
Openrouter的api
全部模型都不可用，同样的Chatbox可以正常使用
Windows11 V0.3.6

**Comment by kangfenmao** [comment]
尝试复现了一下，没有测试出来这个错误，能否再提供一张 OpenRouter 设置界面的截图，和一张聊天出错的截图 @Sun9220

**Comment by kangfenmao** [comment]
可能是提示词问题，你在左侧智能体上面点击右键，把提示词改成空的试试 @Sun9220

**Comment by Sun9220** [comment]
<img width="610" alt="3" src="https://github.com/user-attachments/assets/5bc94bc5-e077-4521-8a6a-69185b5df916">
<img width="610" alt="1" src="https://github.com/user-attachments/assets/df1a7aaa-99a0-43e7-a4a2-cb167c253a6c">
<img width="778" alt="2" src="https://github.com/user-attachments/assets/095af351-b19e-4fa4-91e8-54f6589491c7">
同样的网络情况下，Chatbox可以正常运行，网络也是可以触达OpenRouter官网的

**Comment by kangfenmao** [comment]
看到了这个情况，看来是客户端在发起请求的时候遇到了网络相关问题。

如果有配置代理软件，还需要检查是否是网络代理问题。

如果这些问题都没有的话，我明天发一个新版本，和你一起再看看开发者工具中出现的错误，应该就能解决这个问题了。

**Comment by Sun9220** [comment]
问题描述:
1. 软件初始安装后可以正常使用，API检测显示连通。
2. 使用一段时间后，突然出现"连接错误"的错误。
3. 卸载重装后，仍然只能在安装后的短时间内正常使用，之后再次出现相同错误。

已尝试的解决方法:
1. 家中网络使用全局代理，理论上不应该是网络问题。
2. 在本地开启额外的代理软件，但错误依然存在。

**Comment by kangfenmao** [comment]
需要更新到最新版 v0.3.7，更新完成后使用快捷键 Ctrl + Shift + I 打开控制台，然后看看网络请求情况。看看能否提供一些更有用的信息 @Sun9220 

<img width="1421" alt="image" src="https://github.com/user-attachments/assets/b31b6079-0279-400e-91ec-6539b58f6ee9">

**Comment by Sun9220** [comment]
![image](https://github.com/user-attachments/assets/dfabffc7-918c-4f27-a0d9-70c2288ac7a9)

**Comment by kangfenmao** [comment]
可以加我一下微信吗，我可以快速跟你沟通一下 @Sun9220 

<img width="196" alt="image" src="https://github.com/user-attachments/assets/ef40fb8c-db85-4c72-80b5-d51698c8cac2">

**Comment by kangfenmao** [comment]
代理设置问题

<img width="1121" alt="image" src="https://github.com/user-attachments/assets/9ae8032b-18c8-464d-9179-5fe953937caa">
