### ISSUE TITLE
改进参数的调整范围

### ISSUE THREAD

**Issue by wsyzxjn** [kangfenmao/cherry-studio#60]
目前在应用中模型温度的上限值为1.2
而在某些场景下该值需要更高的设定，如下图
![image](https://github.com/user-attachments/assets/e130c3ac-6caf-4c23-a3c5-55b0f404c308)
希望能够修改该值的上限。
以及上下文参数或许可以更加灵活配置，例如添加一个自定义上下文数的输入框？

**Comment by wsyzxjn** [comment]
发现了在设置页面可以修改，但只限于默认助手

**Comment by kangfenmao** [comment]
这里也能设置吧 @wsyzxjn 

<img width="1385" alt="image" src="https://github.com/user-attachments/assets/be1fce38-6dd1-44e9-983a-a21a83107494">
