### ISSUE TITLE
为啥不像next一样用tauri打包呢，electron不想用啊

### ISSUE THREAD

**Issue by kero990** [kangfenmao/cherry-studio#64]
既然是TypeScript，应该天生亲和tauri吧，能不能不用electron啊，对electron真是一点好感都没有

**Comment by kangfenmao** [comment]
因为有更复杂的功能还没有开发出来，tauri 打包只能做一些简单的应用。一旦复杂起来，开发量会很大，并没有很多 rust 库可以集成

**Comment by kangfenmao** [comment]
复杂的功能包括知识库的集成，和操作系统的紧密联系，用户数据安全，本地AI引擎集成，隐私保护等。用 Tauri 开发可调用的系统 API 能力有限，同时写 Rust 的速度很慢，不是很合适 Studio 要做的事情。
