### ISSUE TITLE
优化模型选择 Dropdown 组件

### ISSUE THREAD

**Issue by wsyzxjn** [kangfenmao/cherry-studio#65]
目前点击重新生成后都会固定弹出选择列表，如下图
![image](https://github.com/user-attachments/assets/16ab8708-75e7-44b5-b98d-55afae483f07)
默认会高亮生成该回答的模型，但是要执行重新生成还是需要点击对应的选项。
而在很多时候都是需要当前模型进行重新生成，在配置了很多模型的情况下还需要滑动列表才能找到当前的模型。希望可以在点开这个列表时能自动定位到当前模型。

**Comment by kangfenmao** [comment]
很好的建议(òωó)👍
