### ISSUE TITLE
停止生成内容后，消息无法清空

### ISSUE THREAD

**Issue by ZzzzRyan** [kangfenmao/cherry-studio#66]
我在大模型回复内容前暂停了生成，此时这一条消息就无法清空了。即使切换到其他对话，该消息仍然存在。
详情见录屏：

[](https://github.com/user-attachments/assets/94d0dda2-fa5e-4fa7-bc49-a08e25921113)

**Comment by kangfenmao** [comment]
是个大 bug。我得修一下
