### ISSUE TITLE
已发送的文本复制后，每行结尾会多出两个空格

### ISSUE THREAD

**Issue by ZzzzRyan** [kangfenmao/cherry-studio#67]
## 问题

点击发送后消息右上角的复制按钮，复制出来的文本会比原文本每行的结尾多出两个空格。

虽然一两个无伤大雅，但我有时一个提示词会反复复制、修改、重新发送，这时候空格就会不断累积，造成影响了。

https://github.com/user-attachments/assets/bddba17d-2548-4cf4-8e1d-c444c5339e8a

## 顺带一提

点击编辑按钮后，文本放进输入框，但输入框高度无法自适应。

![PixPin_2024-09-14_10-32-58](https://github.com/user-attachments/assets/2d3a1f27-a265-4d44-bfa3-512cc6b82528)

并且我注意到一些竞品这里的编辑是在原消息处修改，然后消息上方会带有一个 “重新生成” 按钮。

当前 cherry-studio 的重新发送一条新消息的方式，会携带上文中的原消息，可能会造成一定的干扰和Token消耗。

---

最后，想咨询一下开发者的意见，像我这样一次遇到了两个问题，同时相关性不强的情况，我是否应该开多个 issue 呢？还是像这样放在一个 issue 里提出？

**Comment by kangfenmao** [comment]
非常感谢提出反馈信息，你的反馈非常清晰明确

无所谓开几个 issue，只要能够反馈问题，开发者就能够了解使用者需求，这样的话软件就会慢慢变好

**Comment by ZzzzRyan** [comment]
> 非常感谢提出反馈信息，你的反馈非常清晰明确
> 
> 无所谓开几个 issue，只要能够反馈问题，开发者就能够了解使用者需求，这样的话软件就会慢慢变好

好的，感谢开发者！

**Comment by kangfenmao** [comment]
修复了一个复制文字末尾有空格的问题

**Comment by kangfenmao** [comment]
修复了点击编辑消息后输入框不能自适应内容高度问题

**Comment by kangfenmao** [comment]
编辑消息的功能这里使用了另外一种方式来实现，创建新分支来从历史中的某个消息重新开始。这样不会导致后面消息意外丢失。

<img width="623" alt="image" src="https://github.com/user-attachments/assets/6d4ed6a4-4e6e-4af8-a742-26a7d8300ccc">

**Comment by ZzzzRyan** [comment]
> 编辑消息的功能这里使用了另外一种方式来实现，创建新分支来从历史中的某个消息重新开始。这样不会导致后面消息意外丢失。
> 
> <img alt="image" width="623" src="https://private-user-images.githubusercontent.com/8253512/367653375-6d4ed6a4-4e6e-4af8-a742-26a7d8300ccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NjM1NTMsIm5iZiI6MTcyNjQ2MzI1MywicGF0aCI6Ii84MjUzNTEyLzM2NzY1MzM3NS02ZDRlZDZhNC00ZTZlLTRhZjgtYTc0Mi0yNmE3ZDgzMDBjY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMDUwNzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZlMTdiMmQzNjE2Y2ZhMzg1ZWIxNzcwYTg3ZWFjMDIxNDBjY2NkNDUyMTgwZDMyMjlmODVhZmMzZTU3YWY4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P1MfS-RDbPK71A9dBPR3_qCvZzFuvfRHQ-95VtIyB6s">

赞！这样确实更直观和保险！

**Comment by kangfenmao** [comment]
新版本已经发布
