### ISSUE TITLE
Webdav 数据备份与数据同步

### ISSUE THREAD

**Issue by youtiaoguagua** [kangfenmao/cherry-studio#69]
webdav加密同步配置，

**Comment by kangfenmao** [comment]
这个已经在做了

**Comment by dlzmoe** [comment]
支持，很需要这个功能 😎

**Comment by kangfenmao** [comment]
这个功能已经开发完成，by @DrayChou

另外，我给 webdav 增加了一个配置界面，增加了备份文件的功能

![CleanShot 2024-09-29 at 16 37 24@2x](https://github.com/user-attachments/assets/3ccc7e72-281e-4c8e-9b4c-94a6607f6e36)
