### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by randbitxx** [kangfenmao/cherry-studio#7]
希望可以自定义“职业”，也就是提示词。设计的方便使用，类似于GTPs。
如果能接入类似于chatGpt的语音聊天，那么在众多chatbox中可以脱颖而出了，即使是可以预留接口接入云服务商的语音合成和识别

**Comment by kangfenmao** [comment]
<img width="239" alt="image" src="https://github.com/user-attachments/assets/c86b768a-ec71-48a0-836b-1f154253cf09">

@randbitxx 这里点击右键有菜单

<img width="512" alt="image" src="https://github.com/user-attachments/assets/95ab7e07-1d89-4900-8271-99b0c51656fd">

**Comment by kangfenmao** [comment]
接入语言聊天其实并不复杂，等基础功能开发完成后，马上就考虑做这个

**Comment by randbitxx** [comment]
> <img alt="image" width="239" src="https://private-user-images.githubusercontent.com/8253512/351971223-c86b768a-ec71-48a0-836b-1f154253cf09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODYwNTYsIm5iZiI6MTcyMTg4NTc1NiwicGF0aCI6Ii84MjUzNTEyLzM1MTk3MTIyMy1jODZiNzY4YS1lYzcxLTQ4YTAtODM2Yi0xZjE1NDI1M2NmMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMDUzNTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRkMWRjNWVlMjBmM2UzMDUwOWQyZjU4ZTYzZjExYmI4ZTc0NmM5M2Y0MjIzMThjMzAwMDdlMjFmYWNlZDVkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hhlk7HeLUhZB5Jqal80vyrsmhHvtBzCSZ9uH_hWgh8k">
> @randbitxx 这里点击右键有菜单
> 
> <img alt="image" width="512" src="https://private-user-images.githubusercontent.com/8253512/351971308-95ab7e07-1d89-4900-8271-99b0c51656fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODYwNTYsIm5iZiI6MTcyMTg4NTc1NiwicGF0aCI6Ii84MjUzNTEyLzM1MTk3MTMwOC05NWFiN2UwNy0xZDg5LTQ5MDAtODI3MS05OWIwYzUxNjU2ZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMDUzNTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQ0M2FiMWQwYTdjZTc1OTA2NjI4MWUwYjkzNWU2NjI0ZDRlNGE1OTVkN2Y4MjE0ZTk0ODBlYjM0ZDlhOTNkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OhTT1yafoSrkkgGsURY8kURw-WLArrr4AgEvc9n_JAk">

这个是聊天窗口吗？单次聊天窗口是可以修改提示词，但是每次新会话都需要修改好像有点不方便，或者清空一个现有的聊天窗口？

**Comment by kangfenmao** [comment]
你说的是这个吗 @randbitxx 

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/091352c8-dc5a-4eb9-a159-02ab9ec2909a">

**Comment by randbitxx** [comment]
<img width="1079" alt="截屏2024-07-25 13 44 12" src="https://github.com/user-attachments/assets/1d403029-a90c-4f98-bad2-38f64ba892a1">
左侧边栏是会话记录，修改提示词的话，我是在这里修改的，但是每次创建新会话都必须这么做，除非是清空一个历史会话的聊天记录，感觉不太方便

**Comment by kangfenmao** [comment]
@randbitxx 加我微信，我们聊一下吧

wx: kangfenmao

**Comment by randbitxx** [comment]
> 你说的是这个吗 @randbitxx
> 
> <img alt="image" width="1075" src="https://private-user-images.githubusercontent.com/8253512/351977207-091352c8-dc5a-4eb9-a159-02ab9ec2909a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODY4MTUsIm5iZiI6MTcyMTg4NjUxNSwicGF0aCI6Ii84MjUzNTEyLzM1MTk3NzIwNy0wOTEzNTJjOC1kYzVhLTRlYjktYTE1OS0wMmFiOWVjMjkwOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMDU0ODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjdhZmY0ODljOTlmZjdlYWZkOGI4ZGZmN2Y2YTMzOWMzNjNkZTNhMGMxNWJjODJiZWIyMzVkNzIwNDE4Zjk5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5Cu8w4vs0sD96ewDVV2kj8W4y1dqdaNh_pFw_Qki1_U">

上图中，如果我把“名称”一栏清空，然后启动新的会话，这时候不会自动填充会话标题，并且切换其他会话之后，这个没有名称的会话会消失

**Comment by kangfenmao** [comment]
> > 你说的是这个吗 @randbitxx
> > <img alt="image" width="1075" src="https://private-user-images.githubusercontent.com/8253512/351977207-091352c8-dc5a-4eb9-a159-02ab9ec2909a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODY4MTUsIm5iZiI6MTcyMTg4NjUxNSwicGF0aCI6Ii84MjUzNTEyLzM1MTk3NzIwNy0wOTEzNTJjOC1kYzVhLTRlYjktYTE1OS0wMmFiOWVjMjkwOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMDU0ODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjdhZmY0ODljOTlmZjdlYWZkOGI4ZGZmN2Y2YTMzOWMzNjNkZTNhMGMxNWJjODJiZWIyMzVkNzIwNDE4Zjk5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5Cu8w4vs0sD96ewDVV2kj8W4y1dqdaNh_pFw_Qki1_U">
> 
> 上图中，如果我把“名称”一栏清空，然后启动新的会话，这时候不会自动填充会话标题，并且切换其他会话之后，这个没有名称的会话会消失

哈哈哈，这个是个 bug

**Comment by kangfenmao** [comment]
左侧放的是智能体，右侧是会话，类似这张图。右侧这个你能看到吗 @randbitxx 

<img width="1388" alt="image" src="https://github.com/user-attachments/assets/9f4d3995-2724-44fd-bba0-640990798140">

**Comment by kangfenmao** [comment]
是的，和其他产品有些差异。把话题和智能体进行关联，特别适合重度用户，能够整理自己的话题记录。可以用鼠标拖拽进行排序。

新手引导功能还没有开发出来，所以使用上对新用户其实不太友好，等我后续做帮助功能的时候加上引导。

@randbitxx

**Comment by randbitxx** [comment]
这个看AI的使用场景了。作为智能助手，那么他的问题会比较散乱，整理排序的意义不是特别大。如果是电子宠物或者问答知识图谱，那么分类整理以及时间线是挺重要的。
