### ISSUE TITLE
建议新增类似LibreChat的分叉功能

### ISSUE THREAD

**Issue by 3377** [kangfenmao/cherry-studio#70]
场景：某些对话很长，此时需要根据某一个输入或者输出进行独立对话。
优点：节省api，加快响应，避免AI不必要的理解。

**Comment by kangfenmao** [comment]
有没有一些选择界面做参考

**Comment by 3377** [comment]
![image](https://github.com/user-attachments/assets/f67be244-2790-4a99-a30a-4fa28f0f449f)
**模式：**然后会自动新建一个话题，基于截止到此的回复。
**场景利好：**比如写代码的时候想回溯，那么从某个功能点的时候分叉出去重新继续生成即可。
我试过不下20个web的，客户端的。此前一直用openwebui截止目前，这个客户端是我满意的一个了。希望优化的越来越好。

**Comment by kangfenmao** [comment]
这是个好想法，等于是从某个消息进行复制一份对话，好点子

**Comment by 3377** [comment]
另外说个小小的需求，看下能否后续支持，就是生成一堆代码后，几乎所有的客户端，web端都是在生成的框的右上角去点击复制。但是代码有的时候上万的token，生成后必须得一点点的网上滚到点击复制的地方。所以有没有可能在代码的最右下角可以 点击复制？？？？这个真的是无语，找遍全网没有一个支持的。

**Comment by kangfenmao** [comment]
> 另外说个小小的需求，看下能否后续支持，就是生成一堆代码后，几乎所有的客户端，web端都是在生成的框的右上角去点击复制。但是代码有的时候上万的token，生成后必须得一点点的网上滚到点击复制的地方。所以有没有可能在代码的最右下角可以 点击复制？？？？这个真的是无语，找遍全网没有一个支持的。

这个容易实现，可以判断代码文本长度，如果超过某个临界条件就在底部也加一个复制按钮方便操作

**Comment by 3377** [comment]
也可以来个选择框，只要是代码块，让大家自行选择位置。
来个在线求等更新？这个我真的是无语？好像没人提过。

**Comment by kangfenmao** [comment]
这个需求估计下个版本就能上，到时候我会在这里留言

**Comment by 3377** [comment]
感谢，感谢，大佬给力。

**Comment by kangfenmao** [comment]
显示所有话题，如果话题已经显示了，点击就没有效果了。

**Comment by Yizhouuu** [comment]
我感觉按钮那些其实默认放在文本下方挺好的？因为大多时候鼠标都是放在文本框附近吧，这样也能减少鼠标移动的距离

**Comment by kangfenmao** [comment]
> 我感觉按钮那些其实默认放在文本下方挺好的？因为大多时候鼠标都是放在文本框附近吧，这样也能减少鼠标移动的距离

因为人看文本通常都是从上往下看，上面有代码标题可以很清楚知道这一段是什么代码，所以头其实也挺重要的

**Comment by Yizhouuu** [comment]
> > 我感觉按钮那些其实默认放在文本下方挺好的？因为大多时候鼠标都是放在文本框附近吧，这样也能减少鼠标移动的距离
> 
> 因为人看文本通常都是从上往下看，上面有代码标题可以很清楚知道这一段是什么代码，所以头其实也挺重要的

那或许可以 标题在上面、按钮在下面？
不过确实就 UI 占用总面积变大了😂

**Comment by kangfenmao** [comment]
长代码的话在右下角加一个悬浮的按钮就可以了 @Yizhouuu

**Comment by Yizhouuu** [comment]
> 长代码的话在右下角加一个悬浮的按钮就可以了 @Yizhouuu

确实，唉😂脑子没转过来了

**Comment by 3377** [comment]
看来还是有相同需求的人啊，一般用ai生成的代码不会从头往下看的，都是复制粘贴进ide，再去看的。

**Comment by corwin1949** [comment]
> 场景：某些对话很长，此时需要根据某一个输入或者输出进行独立对话。 优点：节省api，加快响应，避免AI不必要的理解。

确实会有这个需求

**Comment by kangfenmao** [comment]
1. 增加了底部复制按钮
2. 优化了消息重复渲染问题，提升加载速度
3. 修复了生成过程中无法复制的问题

<img width="630" alt="image" src="https://github.com/user-attachments/assets/d3bdb548-725e-4ff1-86ba-4dc0d2f97513">

**Comment by 3377** [comment]
给力 给力，话说这个字体没法调用系统的吗

**Comment by kangfenmao** [comment]
> 给力 给力，话说这个字体没法调用系统的吗

中文用的是系统字体，英文用的 Ubuntu 字体，系统差异很大，如果不设定字体，有些系统显示出来的效果非常难看

**Comment by kangfenmao** [comment]
新分支

<img width="623" alt="image" src="https://github.com/user-attachments/assets/1b207023-435b-41e3-b29e-adf3168c7051">

**Comment by ZzzzRyan** [comment]
> 因为人看文本通常都是从上往下看，上面有代码标题可以很清楚知道这一段是什么代码，所以头其实也挺重要的

说到长代码和从上往下看，有一个需求是能否在回复消息的底部添加一个按钮（或者用悬浮按钮的形式？）：快速滚动到本条消息顶部。因为有的回复消息太长，每次需要滚动好一会才能看到开头，滚太快还可能滚过头了。

**Comment by corwin1949** [comment]
> > 因为人看文本通常都是从上往下看，上面有代码标题可以很清楚知道这一段是什么代码，所以头其实也挺重要的
> 
> 说到长代码和从上往下看，有一个需求是能否在回复消息的底部添加一个按钮（或者用悬浮按钮的形式？）：快速滚动到本条消息顶部。因为有的回复消息太长，每次需要滚动好一会才能看到开头，滚太快还可能滚过头了。

这个的话，是不是让文字吐满屏幕高度，就不要滚动了。用户已经可以阅读了，后面继续吐字，就在屏幕下方吐，不要滚动显示了。

这样也不用滚到顶部再阅读了，因为可以直接读了。

**Comment by 3377** [comment]
**_不得不说高效给力，昨天提的想法需求，今天就全部落地。_**
### 后续想法

## 多平台
我看源码是typejavscipt编写的，比较好跨平台。是否可以生成一个web版的，ios版的等。然后加个多端同步api设置，同步历史话题，
## 同步备份
加入webdav存储机制，开发者就不用承担服务器压力，同时避免隐私问题。

这样就完美了。

**Comment by kangfenmao** [comment]
webdav 已经在做了。数据同步功能也在做准备。

多平台有规划，ts 代码是可以迁移的到其他平台的，但是多平台不是今年的计划。

**Comment by 3377** [comment]
貌似生成web端是最简单的，同时web端也是所有的基础吧。感觉样式功能都不用改变。更改一下安装方式就可以。现在web端用的openwebui，实在臃肿。速度也慢。

**Comment by ZzzzRyan** [comment]
> 这个的话，是不是让文字吐满屏幕高度，就不要滚动了。用户已经可以阅读了，后面继续吐字，就在屏幕下方吐，不要滚动显示了。

这个可以通过在生成的时候稍微用鼠标滚动一下消息框来让消息停住，目前我是这么使用的。

添加 “滚动到顶部” 按钮是因为我还有一个场景，就是查看以前的一些对话的时候，默认进入对话就在最顶部，所以需要向上滚动。

**Comment by Yizhouuu** [comment]
> 这个可以通过在生成的时候稍微用鼠标滚动一下消息框来让消息停住，目前我是这么使用的。

能减少用户多余操作自然是最好的，个人感觉，现在的 LLM 生成速度比人类阅读速度快多了，停在上端、不跟随滚动应该是个没什么副作用的方案

> 添加 “滚动到顶部” 按钮是因为我还有一个场景，就是查看以前的一些对话的时候，默认进入对话就在最底部，所以需要向上滚动。

这个也是一个大多 LLM 客户端或者 WebUI 都没有的功能

**Comment by 3377** [comment]
### 深度使用又发现了一个不是问题的问题，只影响体验，不影响使用。
翻译设置目标语言没有记忆功能。每次都是目标语言为英文。设置好过后，关闭软件重启后又默认为英文。我想大部分人使用翻译都是想其他语言翻译为中文吧。

**Comment by kangfenmao** [comment]
新版本已发布，需要有编程基础的朋友们帮忙测试一下。具体需要测试内容如下：

https://github.com/kangfenmao/cherry-studio/discussions/75

@3377 @corwin1949 @Yizhouuu @Aimer52000 Aim

**Comment by Aimer52000** [comment]
> ### 深度使用又发现了一个不是问题的问题，只影响体验，不影响使用。
> 翻译设置目标语言没有记忆功能。每次都是目标语言为英文。设置好过后，关闭软件重启后又默认为英文。我想大部分人使用翻译都是想其他语言翻译为中文吧。

翻译部分目前不完善，后续会添加记忆功能文档翻译等等。

**Comment by kangfenmao** [comment]
@ZzzzRyan 能否加我一下微信，kangfenmao，需要你帮个小忙

**Comment by 3377** [comment]
怎么是404

**Comment by kangfenmao** [comment]
> 怎么是404

查到了影响用户数据的问题，先删除了，等我修复好再发

**Comment by 3377** [comment]
好的，在线等你更新

**Comment by ZzzzRyan** [comment]
> @ZzzzRyan 能否加我一下微信，kangfenmao，需要你帮个小忙

OK👌

**Comment by kangfenmao** [comment]
> 好的，在线等你更新

你也试试这个，看看启动后有没有数据异常

方便的时候再安装一下这个试试吧，这次应该会提示升级成功

https://github.com/kangfenmao/cherry-studio/releases/tag/v0.7.1

**Comment by 3377** [comment]
> > 好的，在线等你更新
> 
> 你也试试这个，看看启动后有没有数据异常
> 
> https://github.com/kangfenmao/cherry-studio/releases/tag/v0.7.1

体验了，目前使用正常，但输入输出的token计算没了，应该是挡住了
![image](https://github.com/user-attachments/assets/2846269c-ea21-4026-9159-0deac1eabdb4)

**Comment by kangfenmao** [comment]
> > > 好的，在线等你更新
> > 
> > 
> > 你也试试这个，看看启动后有没有数据异常
> > https://github.com/kangfenmao/cherry-studio/releases/tag/v0.7.1
> 
> 体验了，目前使用正常，但输入输出的token计算没了，应该是挡住了 ![image](https://private-user-images.githubusercontent.com/15319161/367723474-2846269c-ea21-4026-9159-0deac1eabdb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODM2MDMsIm5iZiI6MTcyNjQ4MzMwMywicGF0aCI6Ii8xNTMxOTE2MS8zNjc3MjM0NzQtMjg0NjI2OWMtZWEyMS00MDI2LTkxNTktMGRlYWMxZWFiZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEwNDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZTQ5ODk5YTJjMDFkMTUwNDExODVhMGVlYjhiZTI2ZmVjY2U0ZDhlNDRiODQyZmY0NjgyZGI4MTI1N2Q0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dx4aJgGl_xeCZiiS4iGJ73VycNfpOS2ci-jLBY55jMw)

那说明基本上升级是没啥大问题了，我修复一下这个问题

**Comment by 3377** [comment]
> > > > 好的，在线等你更新
> > > 
> > > 
> > > 你也试试这个，看看启动后有没有数据异常
> > > https://github.com/kangfenmao/cherry-studio/releases/tag/v0.7.1
> > 
> > 
> > 体验了，目前使用正常，但输入输出的token计算没了，应该是挡住了 ![image](https://private-user-images.githubusercontent.com/15319161/367723474-2846269c-ea21-4026-9159-0deac1eabdb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODM2MDMsIm5iZiI6MTcyNjQ4MzMwMywicGF0aCI6Ii8xNTMxOTE2MS8zNjc3MjM0NzQtMjg0NjI2OWMtZWEyMS00MDI2LTkxNTktMGRlYWMxZWFiZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEwNDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZTQ5ODk5YTJjMDFkMTUwNDExODVhMGVlYjhiZTI2ZmVjY2U0ZDhlNDRiODQyZmY0NjgyZGI4MTI1N2Q0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dx4aJgGl_xeCZiiS4iGJ73VycNfpOS2ci-jLBY55jMw)
> 
> 那说明基本上升级是没啥大问题了，我修复一下这个问题。从图中好像看不出来出现了什么问题呀

这是以前的效果，给你张新的效果你就明白了
![image](https://github.com/user-attachments/assets/8e974b5c-73e6-4837-85ec-e7e962aab5fd)

**Comment by 3377** [comment]
我看了下，有的有，有的没有。你的逻辑是api没返回token就不输出吗？还是如果api没有返回值，自己会计算。

**Comment by kangfenmao** [comment]
> 我看了下，有的有，有的没有。你的逻辑是api没返回token就不输出吗？还是如果api没有返回值，自己会计算。

这个是 API 返回的数据，API 没有返回的情况，我的重新找个方案计算一下

**Comment by kangfenmao** [comment]
新版本已经发布

**Comment by 3377** [comment]
![image](https://github.com/user-attachments/assets/dc5a4a5e-1d05-4d69-bb32-ac60a18d8fd5)
话说这个分支不能都放一个位置吗？差点没找到。

**Comment by kangfenmao** [comment]
> ![image](https://private-user-images.githubusercontent.com/15319161/367744001-dc5a4a5e-1d05-4d69-bb32-ac60a18d8fd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODg1NzksIm5iZiI6MTcyNjQ4ODI3OSwicGF0aCI6Ii8xNTMxOTE2MS8zNjc3NDQwMDEtZGM1YTRhNWUtMWQwNS00ZDY5LWJiMzItYWM2MGExOGQ4ZmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEyMDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NjdjMDlmZGQ3YzU2NDVhY2JkOTBlM2E2YWQzNzIxNmNlN2YwNjQxNTVhYmE0NGExZjNiM2QzZjM4Y2I2OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cslMVay1gQnC4scPmYgunk4TR3X5aLDluUf5ALOHXyk) 话说这个分支不能都放一个位置吗？差点没找到。

这个让我再考虑考虑，如果放在左下角默认不隐藏情况下，界面会比较乱。如果隐藏的话，要留一些空白空间，布局又不紧凑
