### ISSUE TITLE
文心千帆

### ISSUE THREAD

**Issue by jiangyouwang6** [kangfenmao/cherry-studio#72]
开发者大大，能不能加个文心千帆的模型提供商，附带api文档，然后自己能选定模型，最好再加个限制携带会话数的选项，节省一下tokens。
https://cloud.baidu.com/doc/WENXINWORKSHOP/s/flxwku3ea

**Comment by kangfenmao** [comment]
合并到这个 issue 里面了，最新进展在这里查看

https://github.com/kangfenmao/cherry-studio/issues/68#issuecomment-2351950605

**Comment by jiangyouwang6** [comment]
> 合并到这个 issue 里面了，最新进展在这里查看
> 
> [#68 (comment)](https://github.com/kangfenmao/cherry-studio/issues/68#issuecomment-2351950605)

感谢

**Comment by thxcn** [comment]
怎样用文心千帆啊，我看他有个ak和sk来着...模型服务里边也没有
