### ISSUE TITLE
功能请求：添加「流式传输」的开关选项

### ISSUE THREAD

**Issue by Theigrams** [kangfenmao/cherry-studio#73]
当前聊天默认开启流式传输，但 OpenAI 最新的模型「o1」不支持流式传输，因此希望能添加一个选项，能手动开启或关闭

**Comment by kangfenmao** [comment]
o1 我还没有测试过，能对话吗

**Comment by Theigrams** [comment]
> o1 我还没有测试过，能对话吗

<img width="878" alt="image" src="https://github.com/user-attachments/assets/cafe6f25-5552-466b-b016-8ba6a5e58007">

需要关闭流式传输，再把温度设为1，就可以调用 o1 的 API 进行对话了

**Comment by kangfenmao** [comment]
下个版本加上 @Theigrams

**Comment by kangfenmao** [comment]
增加了 o1 模型支持，你可以试试
