### ISSUE TITLE
有一个显示错误

### ISSUE THREAD

**Issue by jiangyouwang6** [kangfenmao/cherry-studio#77]
当我输入0.03 * 1024 * 12 * 10时，结果是对的，但在用户输入的显示上 有错误。
![Uploading 1.png…]()

**Comment by jiangyouwang6** [comment]
![1](https://github.com/user-attachments/assets/b740c15c-ed50-42b2-86ea-f2e495b12cf4)

**Comment by kangfenmao** [comment]
当做 markdown 语法处理了，这个我得想想怎么弄

**Comment by Komorebi-yaodong** [comment]
![image](https://github.com/user-attachments/assets/baf002d9-cc76-4418-96b9-92e6b8ade610)
对于markdown语法也有点错误

**Comment by kangfenmao** [comment]
新版本发布了，不知道这个问题是否解决了

**Comment by kangfenmao** [comment]
<img width="794" alt="image" src="https://github.com/user-attachments/assets/df2f723e-db28-4f34-9e94-5667be65a785">
