### ISSUE TITLE
话题展示和话题新建的优化建议

### ISSUE THREAD

**Issue by 3377** [kangfenmao/cherry-studio#79]
## 话题展示

>  当前智能体和话题显示在左边的时候，点击智能体。话题无法自动联动，必须点击一下才能显示话题。

## 话题新建

> 当前的话题新建需要在任意一个话题的内部左边点击新建话题，不符合用户操作习惯和逻辑

1. **建议设置为在智能体和话题的下面提供快捷按钮**
2. **建议添加快捷键**

**Comment by kangfenmao** [comment]
<img width="1217" alt="image" src="https://github.com/user-attachments/assets/c523e0a7-00c3-42ec-86cc-4b8a320346d3">

下个版本发布

**Comment by kangfenmao** [comment]
快捷键问题移交到了这里：https://github.com/kangfenmao/cherry-studio/issues/85
