### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by wf58585858** [kangfenmao/cherry-studio#8]
> 所有模型提供商把接口地址改为可手动自定义，现在的地址就默认填里面，类似 openai 这样的接口，可能别人是使用的其他平台兼容openai的接口，也可能是需要设置反向代理openai 地址，直接写上 openai 的官方地址在国内环境注定了就用不了

> 还有ollama，可能服务器端不一定是安装在客户端上，可能安装在其他机器上

> 添加自定义的模型提供商时，后面加个备注，提示别人接口保持与openai 兼容，这样体验好一些
比如这个地址是应该是 `http://127.0.0.1:11434/v1/chat/completions` , 这种格式，还是 `http://127.0.0.1:11434` 像这样写个域名就行，地址后面加不加 斜线 等

> 其他的类似多模态的这些功能最好也有，可以慢慢加

**Comment by kangfenmao** [comment]
建议采纳，今天修改。

目前的解决办法是添加一个自定义的

<img width="912" alt="image" src="https://github.com/user-attachments/assets/eb22d2e5-0132-43bc-80e2-aaaa995c9481">

**Comment by kangfenmao** [comment]
<img width="653" alt="image" src="https://github.com/user-attachments/assets/ca7fbaf2-399d-4f13-94de-c91027370a92">

**Comment by kangfenmao** [comment]
@wf58585858 更新到 v0.3.7 这个问题已解决

**Comment by wf58585858** [comment]
感谢，十分高效，祝项目越来越成功
