### ISSUE TITLE
添加 midjourney 支持 

### ISSUE THREAD

**Issue by Lala-0x3f** [kangfenmao/cherry-studio#80]

**Comment by kangfenmao** [comment]
这个提议已经有了，文生图。这个已经在计划列表里，我只能按照优先级一点一点去做。

https://github.com/kangfenmao/cherry-studio/issues/28

具体进展，需要到上面帖子里面看，如果完成，我会在帖子里通知

**Comment by chad0708** [comment]
哈哈哈，所以还没添加midjourney吗？
