### ISSUE TITLE
更新后通过OneAPI接入的deepseek模型请求错误

### ISSUE THREAD

**Issue by wsyzxjn** [kangfenmao/cherry-studio#83]
![image](https://github.com/user-attachments/assets/d1cef549-c546-435f-bb6f-f8aca5494b96)
更新前使用一切正常，在0.7.2版本更新后出现该错误，其他模型使用测试正常。
已在其他应用中测试可以正常使用确认不是oneapi的问题。

**Comment by kangfenmao** [comment]
能否截一张完整的图片看一下

**Comment by wsyzxjn** [comment]
> 能否截一张完整的图片看一下

![image](https://github.com/user-attachments/assets/93ebaa0e-f28d-420f-88cb-1ec9f7bc40c8)

**Comment by kangfenmao** [comment]
能否加我微信私聊一下，我用你的 key 测试一下，我的微信：kangfenmao

@wsyzxjn

**Comment by kangfenmao** [comment]
https://github.com/kangfenmao/cherry-studio/releases/tag/v0.7.3

请你来测试一下这个版本是否修复了这个问题 @wsyzxjn

**Comment by wsyzxjn** [comment]
> https://github.com/kangfenmao/cherry-studio/releases/tag/v0.7.3
> 
> 请你来测试一下这个版本是否修复了这个问题 @wsyzxjn

问题已解决，效率太高了
![image](https://github.com/user-attachments/assets/ea94a192-e068-4668-9a1f-a6a86defabf1)

**Comment by kangfenmao** [comment]
这个问题原因是 deepseek 只能支持单个文本信息，不完全支持 OpenAI 的 SDK.目前 deepseek 对话不能选择文件，后面我要调整一下，针对 deepseek 禁用文件选择
