### ISSUE TITLE
deepseek无法使用文件问答功能，不上传文件可以正常问答

### ISSUE THREAD

**Issue by Jontyshaw** [kangfenmao/cherry-studio#84]
![image](https://github.com/user-attachments/assets/1c29a858-77c1-4570-9e14-d43629f4ed1d)

**Comment by kangfenmao** [comment]
发现了，下个版本给文件按钮禁用了

**Comment by kangfenmao** [comment]
或者，我在想个办法，让那些不支持文件的模型也能附加上文件内容进去。下个版本兼容一下

**Comment by Jontyshaw** [comment]
> 或者，我在想个办法，让那些不支持文件的模型也能附加上文件内容进去。下个版本兼容一下

deepseek有点神，openai和qwen系列都可以使用

**Comment by Jontyshaw** [comment]
> 或者，我在想个办法，让那些不支持文件的模型也能附加上文件内容进去。下个版本兼容一下

或者软件内置个类似chromadb向量数据库，embedding模型让用户自己填api key和baseurl，走RAG

**Comment by kangfenmao** [comment]
RAG 正在做

**Comment by kangfenmao** [comment]
这个修复掉了，明天发布新版本
