### ISSUE TITLE
Speed up background wake-up

### ISSUE THREAD

**Issue by missuo** [kangfenmao/cherry-studio#86]
[Bug] Window goes blank for 1-2 seconds when waking up from the background

<img width="1192" alt="image" src="https://github.com/user-attachments/assets/19fe8a1a-c563-419f-a248-2505aa49a4d3">

Window goes blank for 1-2 seconds when waking up from the background

**Comment by kangfenmao** [comment]
This is because after the app enters the background, it destroys the page to save memory. I'll try to find a way to speed up the display.
