### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by xzxlove** [kangfenmao/cherry-studio#88]
1. 右侧聊天栏可以自定义缩小，修改宽度
2. 聊天框增加删除按钮，一点就删除，方便批量删除

![image](https://github.com/user-attachments/assets/ef2f46b0-8a6e-4cc3-a8c8-54d15e674e84)

3. 模型服务可以直接复制，方便当有多个openAI地址时候，方便配置，现在点击添加还要一个一个加模型

![image](https://github.com/user-attachments/assets/a44abc8a-05fc-48af-8d5c-87747b294770)

**Comment by 3377** [comment]
> 1. 右侧聊天栏可以自定义缩小，修改宽度
> 2. 聊天框增加删除按钮，一点就删除，方便批量删除
> 
> ![image](https://private-user-images.githubusercontent.com/49681654/369241437-ef2f46b0-8a6e-4cc3-a8c8-54d15e674e84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDI1MDEsIm5iZiI6MTcyNjgwMjIwMSwicGF0aCI6Ii80OTY4MTY1NC8zNjkyNDE0MzctZWYyZjQ2YjAtOGE2ZS00Y2MzLWE4YzgtNTRkMTVlNjc0ZTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAzMTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZTI3YWFiZGY0MGEzMzVjMWYzOWZjN2IwYTUxMzVkMTE1YjZjZDNlYmIwNmM4MWU5NjhhYWMxYmE0YTNkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2ngz23JXpTy1nulHPLzQ5KDlA-nwC0HpfN_PAxroIEo)
> 
> 3. 模型服务可以直接复制，方便当有多个openAI地址时候，方便配置，现在点击添加还要一个一个加模型
> 
> ![image](https://private-user-images.githubusercontent.com/49681654/369241628-a44abc8a-05fc-48af-8d5c-87747b294770.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDI1MDEsIm5iZiI6MTcyNjgwMjIwMSwicGF0aCI6Ii80OTY4MTY1NC8zNjkyNDE2MjgtYTQ0YWJjOGEtMDVmYy00OGFmLThkNWMtODc3NDdiMjk0NzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAzMTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NWNmYzlkNzQyNGZhMTA3N2ZlZTFlODdkYjIyMDJkOTc0ZjBlNGY3Yzc1MTRiNDMyZDU5YTY4OWI1M2MzNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fg7DfMdkg39sBVvXAmjOUQy04JGkAbAehAZ9FalRjwQ)

赞同1，2。第3点你不如用自己的new-api或其他的去中转，效果更好。还可以自定义权重，轮询，重试。

**Comment by kangfenmao** [comment]
批量删除消息就是现在有的这个清理按钮的功能吗 @xzxlove 
<img width="337" alt="image" src="https://github.com/user-attachments/assets/fce161e9-ddb8-43ab-ba49-41ec7b81c436">

**Comment by xzxlove** [comment]
> 批量删除消息现在有这个清理按钮的功能吗？@xzxlove <img alt="图像" width="337" src="https://private-user-images.githubusercontent.com/8253512/369248638-fce161e9-ddb8-43ab-ba49-41ec7b81c436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjQxMzEsIm5iZiI6MTcyNjgyMzgzMSwicGF0aCI6Ii84MjUzNTEyLzM2OTI0ODYzOC1mY2UxNjFlOS1kZGI4LTQzYWItYmE0OS00MWVjN2I4MWM0MzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMDkxNzExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGI4NGI5ZjhhMmY3MDg5ZGIwOGUwODdhYTgxMWI5MmYyMjNlMDU3OWFmODAyNzg2NGU0NGYyNWZmNDE2MmYxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nST77GCneWxvJJeAuizk3gS-f16K3qSXNnGhCt7AhJs">

不是这个，我圈起来的红色聊天框

**Comment by kangfenmao** [comment]
<img width="321" alt="Google Chrome 2024-09-20 17 25 07" src="https://github.com/user-attachments/assets/fc862216-6d94-4a7e-bd61-a525c6ba64b9">

@xzxlove 这个是不是你想要的

**Comment by ZzzzRyan** [comment]
> 1. 右侧聊天栏可以自定义缩小，修改宽度
> 2. 聊天框增加删除按钮，一点就删除，方便批量删除
> 
> 3. 模型服务可以直接复制，方便当有多个openAI地址时候，方便配置，现在点击添加还要一个一个加模型


1. 赞同。

2. 或许你的使用方式和软件设计的不太一样，一般来说，这里的**智能体**是不会频繁增删的。

    选定了**智能体**后，更多的是 新建/删除 智能体下的**话题**。

    ![image](https://github.com/user-attachments/assets/bfd081d2-79f5-4158-863b-00d725f43ab5)

3. 很多服务商的模型命名都不太一致，这里的复制粘贴感觉不太实用。
    
   一般来说只要你的服务商比较靠谱，实现了/model接口，点击“**管理**”按钮都能够直接选择该服务商支持的模型。不需要一个个添加。

**Comment by kangfenmao** [comment]
issue 合并到这里：https://github.com/kangfenmao/cherry-studio/issues/99
