### ISSUE TITLE
文件能否删除

### ISSUE THREAD

**Issue by Mymoliy** [kangfenmao/cherry-studio#92]
![Clip_2024-09-20_15-39-14](https://github.com/user-attachments/assets/513dcecb-8d6f-4e4d-bbb6-82dfeaab4601)
  输入窗口能否高一些，或者允许自己拉伸。
还有就是文件能否支持删除

**Comment by kangfenmao** [comment]
文件支持删除，只需要删除掉你聊天附带的消息，或者删除话题就可以了

**Comment by kangfenmao** [comment]
窗口暂时不能调整，我会在做个性化功能阶段增加这个功能
