### ISSUE TITLE
更新窗口信息与 Release 界面信息不一致

### ISSUE THREAD

**Issue by ZzzzRyan** [kangfenmao/cherry-studio#94]
在弹出更新窗口时，窗口内的信息和实际此版本的更新信息不一致，容易造成版本混淆，让用户不清楚是否需要更新。

![PixPin_2024-09-20_00-34-39](https://github.com/user-attachments/assets/7c28d8ac-21af-4794-b0dc-ffc3950486e4)

![PixPin_2024-09-20_17-41-17](https://github.com/user-attachments/assets/4fa5dff0-8cb8-4bc6-81d5-48eb86b0acee)

或许可以在窗口上把更新的版本号也加上。

以及如果跳过了多个版本进行更新，可以直接合并罗列中间版本的所有更新历史（限制一定长度）。

**Comment by kangfenmao** [comment]
很好的建议，我后面改造一下

**Comment by kangfenmao** [comment]
这个问题需要发布版本的时候手动写，只需要我每次发布写好更新提示内容即可。
