### ISSUE TITLE
Assistant 的 Prompt 过长时会超出组件

### ISSUE THREAD

**Issue by ZzzzRyan** [kangfenmao/cherry-studio#95]
如图所示，点击 Assistant 查看 Prompt 时会发现超出组件限制，同时没有换行。

![image](https://github.com/user-attachments/assets/cb0ade7a-4a68-4d10-b711-cee87199e8a7)

**Comment by kangfenmao** [comment]
@Aimer52000 这个你来看一下吧

**Comment by Aimer52000** [comment]
> @Aimer52000 这个你来看一下吧

马上搞定

**Comment by xvweirong** [comment]
能增加编辑提示词功能吗？新建的时候没给图标，再想编辑就只能删了重来。提示词原来的格式也没有保留，以后想来这复制也不行了。

**Comment by kangfenmao** [comment]
> 能增加编辑提示词功能吗？新建的时候没给图标，再想编辑就只能删了重来。提示词原来的格式也没有保留，以后想来这复制也不行了。

<img width="866" alt="image" src="https://github.com/user-attachments/assets/b524fa5d-c2fc-4e33-a70c-f4983e49a91b">

**Comment by xvweirong** [comment]
> > 能增加编辑提示词功能吗？新建的时候没给图标，再想编辑就只能删了重来。提示词原来的格式也没有保留，以后想来这复制也不行了。
> 
> <img alt="image" width="866" src="https://private-user-images.githubusercontent.com/8253512/369678088-b524fa5d-c2fc-4e33-a70c-f4983e49a91b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNjE0NzUsIm5iZiI6MTcyNzA2MTE3NSwicGF0aCI6Ii84MjUzNTEyLzM2OTY3ODA4OC1iNTI0ZmE1ZC1jMmZjLTRlMzMtYTcwYy1mNDk4M2U0OWE5MWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDMxMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODZkN2UyMjRmM2QzNzg4ZGI0MGI1YTg1OWExODA4YzMwZDk5ZjI4N2I2NzcwNzJiMDIzZjM1N2Y5MjE3NzkwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kL8b1Sazz9HB8CXXF14L7cQTf3szaII-dD7CIqd2ojE">

谢谢。会用了。

**Comment by kangfenmao** [comment]
这里整个界面后面都要更新了，这个问题在未来不会造成困扰了

**Comment by ZzzzRyan** [comment]
这个 issue 关闭了，但最新版上该问题仍然存在。请问近期是否会计划修复此问题，还是等待界面重构？

**Comment by ZzzzRyan** [comment]
此问题依旧存在，重点不在于截断文本（因为高度超出了还可以滚动查看），而在于宽度超出了控件——可能是这个控件存在一定的bug。

经测试发现，如果prompt中存在**不带空格的长英文（含斜杠）**，就会出现超出控件的情况。

![image](https://github.com/user-attachments/assets/b51c0eff-b40d-4a8c-bc6a-2e86cd448aa7)
