### ISSUE TITLE
使用用户提问的话题前几个字作为话题名，也许是更好的选择

### ISSUE THREAD

**Issue by fresh-men** [kangfenmao/cherry-studio#96]
使用用户提问的话题前几个字作为话题名，也许是更好的选择，都是“默认话题”都不好区分哪个问题了，如图：
![image](https://github.com/user-attachments/assets/ec28e92a-48ef-48b9-affe-893d4edccf6a)

**Comment by kangfenmao** [comment]
去设置一下话题命名的模型
