### ISSUE TITLE
Bug: Anthropic has an extra v1"

### ISSUE THREAD

**Issue by brucel11qwe** [kangfenmao/cherry-studio#97]

**Comment by brucel11qwe** [comment]
![Uploading 8361726838891_.pic.jpg…]()

**Comment by brucel11qwe** [comment]
![8361726838891_ pic](https://github.com/user-attachments/assets/7f3a6f45-5bb8-4551-a4c2-3a296914501a)

**Comment by kangfenmao** [comment]
需要你帖一下你的 API 地址

**Comment by brucel11qwe** [comment]
不是我贴的问题。 我的api 在chat-next-web dify 都能用， 你自己抓包看下  我用这种http://example.com:80  补全了两个/v1/v1

**Comment by kangfenmao** [comment]
http://example.com:80/

后面加条斜线，下个版本修复这个问题
